### ISSUE TITLE
Thank you!

### ISSUE THREAD

**Issue by flowt-au** [TheBrainFamily/cypress-cucumber-preprocessor#105]
Just saying thanks!
I discovered Cypress today as I was looking for a better way to use Gherkin / Cucumber for web apps (not node). I was on the verge of building something myself so between Cypress and yourselves I do not have to. So good.
:-)

**Comment by lgandecki** [comment]
Thank you so much! We appreciate the kind words. How is this package working for you so far? Any feedback?

**Comment by flowt-au** [comment]
So far so good. :-)
I just tested the CucumberJS browser example:

    Feature: Simple maths
        In order to do maths
        As a developer
        I want to increment variables

        Scenario: easy maths
            Given a variable set to 1
            When I increment the variable by 1
            Then the variable should contain 2

        Scenario Outline: much more complex stuff
            Given a variable set to <var>
            When I increment the variable by <increment>
            Then the variable should contain <result>

            Examples:
                | var | increment | result |
                | 100 | 5         | 105    |
                | 99  | 1234      | 1333   |
                | 12  | 5         | 18     |
                | 1   | 9         | 10     |

Step defs:

    var CustomWorld = {
        variable : 0,
        setTo : function (number) {
            this.variable = parseInt(number);
        },
        incrementBy : function (number) {
            this.variable += parseInt(number);
        }
    };

    Given('a variable set to {int}', function (number) {
        CustomWorld.setTo(number);
    });

    When('I increment the variable by {int}', function (number) {
        CustomWorld.incrementBy(number);
    });

    Then('the variable should contain {int}', function (number) {
        expect(CustomWorld.variable).to.eql(number)
    });

And all works as expected. This is great! Thank you. I will be sure to contribute if I do have any ideas.
Murray

**Comment by jcundill** [comment]
@flowt-au if "all works as expected." then we are good.

Closing this issue, please reopen if you are still experiencing problems
