### ISSUE TITLE
How can I pass values containing newline characters?

### ISSUE THREAD

**Issue by TheGeminii** [TheBrainFamily/cypress-cucumber-preprocessor#106]
I have the following feature:
```
Given show the page 
Then the user sees the following "branch" records in the section "branches":
            | Branch name  | Branch information |
            |  Branch 1 | Company name\nCompany address line 1\nCompany address line 2 |
            |  Branch 2 | Company2 name\nCompany2 address line 1\nCompany2 address line 2 |
```
This gives me a parse error, it parses the newline character not as part of the value but as part of the file. Is there a way around this? Can I escape my values in some way so the newlines actually make it to the step definition?

Kind regards,

Hendri

**Comment by xeger** [comment]
Just a note that I too was defeated by this. It seems to be a bug (or difference) between the `gherkin` JS parser and the `gherkin` Ruby parser.

My work around was to use a token `{enter}` in place of newline, since my developers are already accustomed to Cypress-style keycode tokens.

**Comment by lgandecki** [comment]
@xeger are you saying this is how it wotk with gherkin js even outside of this project? Then I think we could close the issue having your comment with workaround as a solution to people that also stumble upon the same problem

**Comment by xeger** [comment]
Initially I thought this was a bug in `gherkin` JS .. however, I just did an experiment, and it seems like the gherkin parser is correctly parsing `\n` as a newline character. See this gist for proof:

https://gist.github.com/xeger/9c24ab07818ee4495fdc6093e8cb545a

So, my new hypothesis is that the bug _is_ in `cypress-cucumber-preprocessor`. Unfortunately I don't know enough about your architecture to  understand the issue.

Do you have a "code generator" step that translates `.feature` files into `.js`? Maybe this `.js` or intermediate representation, needs to escape `\` escape sequences in data tables.

**Comment by lgandecki** [comment]
Cool! Thanks for the debugging. Knowing this is on our side makes it easier to think it through. I will take a look next week :) I hope to spend a day or two on squashing some of the bugs in this project

**Comment by xeger** [comment]
Thank you for your attention and effort; this cypress plugin is an important part of our dev workflow! It's not perfect, but it enables something very useful (Cypress + Cucumber).

**Comment by lgandecki** [comment]
@xeger @TheGeminii do you guys want to take a look at https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/249 ? As far as I know this is fixing the problem, and I'm happy to merge and release :)

**Comment by xeger** [comment]
Yup! That is exactly the fix I had in mind. 🙌
