### ISSUE TITLE
Using TypeScript causes ENOENT error

### ISSUE THREAD

**Issue by piemasters** [TheBrainFamily/cypress-cucumber-preprocessor#107]
When I try to run a feature file I get:
```
Error: ENOENT: no such file or directory, lstat 'C:\...\cypress\integration\integration' at realpathSync (fs.js:1669:15)
```

I'm currently using Angular-cli 7 and Node.js 10.12.0 on Windows with:
    "cypress": "3.1.0",
    "cypress-cucumber-preprocessor": "1.6.0",
    "tsify": "4.0.0",
    "typescript": "3.1.3"

I have followed the instructions on the README:

- npm install --save-dev cypress-cucumber-preprocessor tsify @cypress/webpack-preprocessor
- npm link 
- npm link cypress-cucumber-preprocessor
- Edit the typescript plugins/index.js
- feature file stored in 'cypress/integration'
- steps file stored in 'cypress/support/step_definitions'

My tsconfig in the cypress dir looks like:

```
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"]
  },
  "include": [
    "**/*.ts",
    "../node_modules/cypress"
  ]
```

with my root tsconfig looking like:
```{
  "compileOnSave": false,
  "compilerOptions": {
    "baseUrl": "./",
    "outDir": "./dist/out-tsc",
    "sourceMap": true,
    "declaration": false,
    "module": "es2015",
    "moduleResolution": "node",
    "emitDecoratorMetadata": true,
    "experimentalDecorators": true,
    "target": "es5",
    "typeRoots": [
      "node_modules/@types"
    ],
    "lib": [
      "es2017",
      "dom"
    ]
  }
}
```

I also have the 'plugins\cy-ts-preprocessor.js' file:
```const wp = require('@cypress/webpack-preprocessor');

const webpackOptions = {
  resolve: {
    extensions: ['.ts', '.js']
  },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: 'ts-loader'
          }
        ]
      }
    ]
  }
};

const options = {
  webpackOptions
};

module.exports = wp(options);
```

If I create a copy of the file and put it into the nested directory it's looking for it seems to actually run that file. Unfortunately I then get this error: 
```
TypeScript error: node_modules/@types/jasmine/index.d.ts(13,18): Error TS2300: Duplicate identifier 'describe'.
```
This is obviously a seperate issue, I need to look to see if its possbile to use Jasmine for unit testing or if I'll have to remove it completely.

**Comment by piemasters** [comment]
A quick update: when using the cucumber-preprocessor independently to the typescript-preprocessor it works fine with js files. I don't know if it's the use of browserify causing the problem?

**Comment by lgandecki** [comment]
So sorry! This issue somehow slipped through all the other ones. 
Since the way we work with typescript is very different now, and I'm pretty sure you either solved the issue or decided not to ever use this project again, I'm closing it.
But, feel free to create a new one or comment here, if this is still something you are struggling with.
