### ISSUE TITLE
SyntaxError: Unexpected token (TypeScript)

### ISSUE THREAD

**Issue by johnknoop** [TheBrainFamily/cypress-cucumber-preprocessor#108]
I'm having trouble making ts stepdefinition files working. If I add tsify like you suggest in the guide, then I get this error:

> TypeScript error: node_modules/@types/bluebird/index.d.ts(859,32): Error TS2304: Cannot find name 'IterableIterator'.

If I dont, then I get "SyntaxError: Unexpected token".

Any ideas?

**Comment by johnknoop** [comment]
If I change extension of my stepdefinitions file to .js instead of .ts then it works as expected. This is a shame though, since Cypress is able to read ts files out of the box.

**Comment by johnknoop** [comment]
If I follow your guide to make it support ts, I get this error:
> TypeScript error: node_modules/@types/bluebird/index.d.ts(859,32): Error TS2304: Cannot find name 'IterableIterator'.

**Comment by lgandecki** [comment]
I'm closing this one, as I don't know how to reproduce it. We have two different examples how to use the preprocessor with typescript (with and without webpack):

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#typescript-support

if that still doesn't work for you (or any other lost googler), please create a new issue.
