### ISSUE TITLE
npm ERR! Could not resolve dependency: when trying to install cypress 13

### ISSUE THREAD

**Issue by pat-convex** [TheBrainFamily/cypress-cucumber-preprocessor#1084]
### Current behavior
I tried to update my cypress version to 13 but i get an npm error below

npm ERR! Could not resolve dependency:
npm ERR! peer cypress@"^10.0.0 || ^11.0.0 || ^12.0.0" from @badeball/cypress-cucumber-preprocessor@18.0.4
npm ERR! node_modules/@badeball/cypress-cucumber-preprocessor

### Desired behavior

User should be able to upgrade to the cypress 13 version and use the test replay feature
### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

### Checklist

- [ ] I've read the [FAQ](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/faq.md).
- [ ] I've read [instructions for logging issues](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#bug-reports).
- [ ] I'm not using `cypress-cucumber-preprocessor@4.3.1` (package name has changed and it is no longer the most recent version, see [#689](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689)).

**Comment by badeball** [comment]
This has been fixed with v18.0.5.
