### ISSUE TITLE
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by ludmilanesvitiy** [TheBrainFamily/cypress-cucumber-preprocessor#112]
Operating System: Linux
Cypress Version: latest
Browser Version: latest
BUG/Question

###Current behavior:
I'm trying to create e2e tests with Cypress + Cucumber + Typescript + cypress/webpack-preprocessor
When step-definition file don't have imports/exports - everything works well
But when I'm trying to use PageObjects in TS, using export-import statement, then I got an error like 'import' and 'export' may appear only with 'sourceType: module'

I don't have the possibility to change imports and exports to require and module.export because in my current project I have a lot of PO's and I want to save 2 approaches in tests: default approach and BDD approach

###Desired behavior:
Possibilities to use import and export

###How to reproduce:
[](https://github.com/ludmilanesvitiy/cypress-cucumber-example/pull/1/files)
In this PR you can see how to reproduce the issue https://github.com/ludmilanesvitiy/cypress-cucumber-example/pull/1
In the main repository all works well. https://github.com/ludmilanesvitiy/cypress-cucumber-example

**Comment by ludmilanesvitiy** [comment]
@lgandecki Thank you for the reply. Yes, in my case looks like TS just ignored, but in your example for compiling is used browserify-preprocessor. But I need webpack-preprocessor. Any ideas how to solve? And what could be wrong here https://github.com/ludmilanesvitiy/cypress-cucumber-example/blob/master/cypress/plugins/index.js?

**Comment by drewloomer** [comment]
@ludmilanesvitiy Have you found a fix for this? I'm seeing the same error using a similar setup to what you have in your repo.

**Comment by ludmilanesvitiy** [comment]
@drewloomer No, I don't have a fix for this. Maybe @lgandecki could advice) According to his comments in #114 "I (and most people) used typescript with import/export." - he should know the secrets)

**Comment by mkusher** [comment]
@drewloomer @ludmilanesvitiy take a look on #115, it should solve your issue

**Comment by lgandecki** [comment]
Guys, please confirm and close the issue or tell us if you still have problems.

**Comment by alveshelio** [comment]
Hi,

I'm still having the same issue. 

in plugins/index.ts I have

**Comment by ludmilanesvitiy** [comment]
@lgandecki I've tried recommendations from #115 but have same problems, for quick reproducing I've added this commit: https://github.com/ludmilanesvitiy/cypress-cucumber-example/pull/1/commits/924b98c3407534428912c2d588bc91fbd453fe77

**Comment by mkusher** [comment]
@ludmilanesvitiy https://github.com/ludmilanesvitiy/cypress-cucumber-example/commit/924b98c3407534428912c2d588bc91fbd453fe77#diff-4bcea4966f5e62ded90298c2b0907445R22 
same as above: pass everything to webpack, not only js/jsx

**Comment by lgandecki** [comment]
We now have an example for typescript working with webpack:
https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/

and without it:

https://github.com/TheBrainFamily/cypress-cucumber-typescript-example/


I'm closing this thread for now, if you have a specific issue, after veryfing that the examples work, and that your configuration is in line with them, or if you need to somehow configure things differently - please create a new one and I will be glad to take a look.

**Comment by s4ms00n9** [comment]
@lgandecki So you have examples with and without webpack, but where do you have an example with "out-of-the-box support", described here, in your readme section:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#with-out-of-the-box-support
Because I don't think I have ever seen this working with `tsconfig.json` and imports / exports.
