### ISSUE TITLE
Did tags behavior changed between 1.8.0 and 1.9.0?

### ISSUE THREAD

**Issue by zadigus** [TheBrainFamily/cypress-cucumber-preprocessor#123]
Hi,
I have the following feature file:

```
# language: fr

@initial-release @login
Fonctionnalité: Identifier un utilisateur

[...]
```

With `cypress-cucumber-preprocessor` version 1.8.0, if I run 

```
cypress open
```

and then run that feature, then everything runs fine, i.e. the tests are launched. If I, however, do the very same with version 1.9.0, then cypress complains that it can't find any tests for the feature:

![image](https://user-images.githubusercontent.com/8761254/49686377-e1609400-faf3-11e8-94a4-a78f3181008b.png)

Removing the tags from the feature lets the tests run back again. Is that on-purpose?

All my features have tags. How do I run e.g. all my features, i.e. how do I run the tests corresponding to all the tags?
Thanks in advance!

**Comment by lgandecki** [comment]
If I understand properly that would be a bug - would you be able to create a simple reproduction? I wonder whether the language makes any difference, but I think it probably shouldn't. 
There are some significant changes around tags. Great that you caught this problem so quickly, thanks for letting us know!.

**Comment by lgandecki** [comment]
Ok, I was able to reproduce this easily, so no need for reproduction from you - I should have a fix for this later today.

**Comment by lgandecki** [comment]
Hello @zadigus  Please try 1.9.1 :)

**Comment by zadigus** [comment]
@lgandecki very nice, it is working again! Thanks a lot!!!
