### ISSUE TITLE
<parameter> doesn't work in scenario outline table

### ISSUE THREAD

**Issue by TheGeminii** [TheBrainFamily/cypress-cucumber-preprocessor#127]
When using a `<parameter>` in a sentence in a scenario outline it works as expected: The `<parameter>` gets replaced by a value from the example table. 

However when a `<parameter>` is used in a table in a Scenario outline it does not work as expected: The preprocessor correctly guesses the number of examples but for every run it does not replace the <parameter> with a value from the examples table.

I've also tried `"<parameter>"` and `'<parameter>'` and all sorts of escape characters, but I guess this use case just isn't implemented in the preprocessor. The cucumberjs framework or cucumber for java frameworks do support this use case as it is valid gherkin.

Example scenarios, the first one works, the second one does not:
```gherkin
Feature: variable test

    Scenario Outline: test if <parameters> work in a sentence in a Scenario Outline
        Given something
        When I use "<parameter>" in a sentence
        Then it should work
        Examples:
        | parameter |
        | a parameter |

    Scenario Outline: test if <parameters> work in a table in a Scenario Outline
        Given something
        When I use the parameter in a table:
        | parameter |
        | <parameter> |
        Then it will fail
        Examples:
            | parameter |
            | a parameter |
```

**Comment by lgandecki** [comment]
Could you make a repo with this working in cucumber? Preferably with a scenario that makes sense at least a little bit. I'm not even sure what to expect from the second scenario to be honest

**Comment by TheGeminii** [comment]
I created a github repository that illustrates the issue:
[https://github.com/TheGeminii/cucumber-test](https://github.com/TheGeminii/cucumber-test)

**Comment by bkostrowiecki** [comment]
I have issues with that too. As far as I understand, the problem occurs because after expanding the examples into scenarios steps aren't parsed, so each example is treated as a completely different scenario... Which, of course, is not implemented.

When you add a step definition with specific example data, the cypress understands it.

**Comment by holgergp** [comment]
This should work by now as https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/137 was merged. 
At least my usecase at https://github.com/holgergp/cypressioCucumberExample works now with this change. 
Could you try it with version 1.11.0 of the preprocessor?

**Comment by lgandecki** [comment]
I hope @holgergp is right here and it works. If it doesn't please comment here and tag me, or create a new issue.
