### ISSUE TITLE
Question: Is it possible to install globally and run per project

### ISSUE THREAD

**Issue by flowt-au** [TheBrainFamily/cypress-cucumber-preprocessor#133]
Hi.
I only want one global install of Cypress and Cypress Cucumber, then use it via config per project. I have installed both globally via npm. I can go to my project folder where there is a cypress.json config file and start Cypress from command line, select the project (first time via Windows Explorer, after that Cypress has a list of recent projects) and all is well so far.

Now, in the Cypress app, when I click a feature file, Cypress-Cucumber fails because it is looking for 'gherkin' module in the project folder node-modules, not the global install. If I install cypress-cucumber in my project folder all works fine.

I tried changing the plugin path from
    `const cucumber = require('cypress-cucumber-preprocessor').default` 
to 
    `const cucumber = require('C:\\Users\\myusername\\AppData\\Roaming\\npm\\node_modules\\cypress-cucumber-preprocessor').default` 

which is where the global install is but still got the error:

    Error: Cannot find module 'gherkin' from '{path to my project}\tests\features'

Is it possible?

Thanks,
Murray

**Comment by flowt-au** [comment]
More on this...
Following the docs, in my project root I have 

![screen shot 2019-01-06 at 1 13 43 pm](https://user-images.githubusercontent.com/37637590/50731295-027cd900-11b5-11e9-8865-6f3ca3397ef9.png)

My start.feature is

    Feature: Start cPanel
        As a user I want start the Survey Control Panel
        Scenario: Start Survey Control Panel
            Given I start the app
            Then I should see myFunc

When I run that start.feature, Cypress cant find my step definition `startapp.js`

![screen shot 2019-01-06 at 1 17 05 pm](https://user-images.githubusercontent.com/37637590/50731305-715a3200-11b5-11e9-955d-23499c6dedea.png)

It seems I also needed to add to my package.json file:

    "cypress-cucumber-preprocessor": {
      "step_definitions": "cypress/integration/"
    }

and add the default `support` folder and files to `cypress` folder in my project:

![screen shot 2019-01-06 at 1 27 53 pm](https://user-images.githubusercontent.com/37637590/50731372-f2fe8f80-11b6-11e9-91ea-1b9cff8e399a.png)

Et voila... the test successfully failed. Cool.

Did I do something wrong initially or do the docs need clarification?

Thanks,
Murray

**Comment by lgandecki** [comment]
You skipped the part that tells you about the configuration of the nonGlobalStepDefinitions
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#configuration

so it used the default one, the usage of is explained here:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#step-definition-location-configuration

Feel free to clarify the docs, but I think the problem is that you skipped a step.
