### ISSUE TITLE
Webstorm intermittently resolving step defs

### ISSUE THREAD

**Issue by miteshpatel1** [TheBrainFamily/cypress-cucumber-preprocessor#134]
Hello,

I am new to cypress, as I have previously been using cucumber for JVM. I need some help...

I wanted to know if there is a particular version or configuration required for Webstorm, in order for it to resolve feature files to step defs? I have cloned the cypress-cucumber-example and opened it using Webstorm 2018.1.5, however none of my feature files are able to resolve the underlying step definitions. A few hours ago, it was all fine! The tests all seem to pass when I run them.

Alternatively, can someone recommend a better IDE? A lot of the stuff on teh internet suggests Webstorm isn't best placed for cucumber based tests.

Thanks,

**Comment by miteshpatel1** [comment]
Hello - I made those updates, and still see the same behaviour. I assume this isn't something you are experiencing, and that you are using the Cypress Cucumber Preprocessor Style (recommended!)?

**Comment by lgandecki** [comment]
Both styles should work the same way, yeah. Sorry :( if you can make a repro I could take a look, but it seems like a webstorm issue

**Comment by miteshpatel1** [comment]
Yes I think its webstorm as well. Any chance you can share the version of webstorm you are using?

**Comment by kayvanbree** [comment]
Webstorm is awesome, it would be a shame if you'd have to use something else. For me, to get Webstorm to recognize my steps I need to use a capitalized Given When and Then, but also, you have to use the `/^your step?/` instead of comma's. Cucumber expressions don't work at all. I have noticed that it might not be the most stable solution.

**Comment by miteshpatel1** [comment]
Yes, I like Webstorm too!

Maybe I didn't make my issue clear - I can get webstorm to resolve step defs when I am using the Oldschool/Legacy Cucumber style (where all the step defs are under a single folder). However when I move to Cypress Cucumber Preprocessor Style (where we set nonGlobalStepDefinitions is true), then it doesn't seem to work.

I'll keep chipping away...hopefully I'll find a solution.

**Comment by miteshpatel1** [comment]
Well I literally:

1. downloaded Webstorm 2018.3
2. cloned the latest cypress-cucumber-example
3. npm install

Step defs did not resolve. So I then decided to apply the changes requested here:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#webstorm-support

Still no luck!


________________________________

**Comment by lgandecki** [comment]
Ok you are right!

This is extremely weird.

I tried to remove an openingFacebook.js file (I copied the source code of it to a clipboard ), then created a openingFacebook.js file in the same exact place,pasted the source code, and webstorm got it. 

they might have broken the cucumber integration, they've recently updated it... :)

**Comment by lgandecki** [comment]
so what I'm saying, webstorm didn't match the .feature file to the .js file initially, unless I made it from inside webstorm (instead of just using the one I just pulled from a repo).

**Comment by kayvanbree** [comment]
I'm also on WebStorm 2018.3. WebstormSupport.feature recognizes the steps in webstormSupport.steps.js. I tried adding a step definition through Notepad++ and still the step was recognized. 

When I change single quotes ( `\'I do something\'` ) to ticks ( `\`I do something`\` ) (and use Given etc instead of given), WebStorm starts to recognize steps. So yeah, can't reproduce the problem here. Are you using ticks, regex stuff ( `/^I do something?/` ) or normal single quotes?

**Comment by jamime** [comment]
I'm experiencing the same thing. It started happening after restarting WebStorm.
> cypress.json
````json
{
  "ignoreTestFiles": "*.js"
}
````

>cypress/integration/Login.feature
````cucumber
Feature: Login Page

  This login page is a page which allows an unauthenticated user to enter credentials to
  gain access to restricted parts of the system

  Background:
    Given I am on the login page
````
> cypress/integration/login.steps.js
````js
import { Given, When, Then, defineParameterType } from "cypress-cucumber-preprocessor/steps";
const url = 'http://localhost:3000/';
Given(/I am on the login page/, () => {
    cy.visit(url);
});
````
