### ISSUE TITLE
Possibilty to set another path for commons step definition

### ISSUE THREAD

**Issue by EmmanuelDemey** [TheBrainFamily/cypress-cucumber-preprocessor#136]
For the moment, commons step definitions should be located inside a `common` folder. 
One of my client would like to define another folder in order to reuse some step definitions of other projects. 
I think it is quiet an easy feature to implement. 

We just need to add an extra options to the preprocessor. If this option is undefined, we can use as the default value the current path (`common/`)

What do you think?

**Comment by lgandecki** [comment]
I guess we could make this configurable, but I don't feel the advantage yet, could you give me an example? Do you want to do something like "../../otherProject/cypress/integration/common" ?

**Comment by EmmanuelDemey** [comment]
Yes. In fact they have something like a monorepo based on TFS. So they would like to share some common step definition between multiple projects.

**Comment by lgandecki** [comment]
Sure, I'm happy to take a PR here if this is something you would be interested in doing, as you said, should be pretty easy

**Comment by EmmanuelDemey** [comment]
Thanks. Let's me send you PR asap :p

**Comment by EmmanuelDemey** [comment]
I think we can close this one.
