### ISSUE TITLE
Scenario Outlines and data-tables

### ISSUE THREAD

**Issue by holgergp** [TheBrainFamily/cypress-cucumber-preprocessor#137]
Hi all,

I'm encountering a problem while using Scenario Outlines and data-tables.
If I provide sth like:
```   
    Scenario Outline: Some Title
    When someone sets field to "<value>"
    Then the application shows the following
      | Goods | Value in Euro | 
      | Bike  | <value>       | 
    Examples:
      | value | 
      | 0.10  |
      | 1.10  | 
      | 2.51  | 
      | 5.00  |  
```
then I get the error
```
Timed out retrying: expected '<input#value>' to have value '<value>', but the value was '0.10'
CypressError: Timed out retrying: expected '<input#value>' to have value '<value>', but the value was '0.10'
```

It seems that the example values don't get pulled into the data-table.
This works when using plain cucumber.js

The concrete example can be found [here](https://github.com/holgergp/cypressioCucumberExample/blob/master/cypress/integration/bohnen.feature) (though I'm using german syntax there).
The testrun can be found [here](https://dashboard.cypress.io/#/projects/be5671/runs/1/specs).

**Comment by holgergp** [comment]
I made a smaller example in your test suite and I can reproduce this behavior:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/compare/master...holgergp:scenarioOutlineAndDataTables?expand=1

**Comment by lgandecki** [comment]
yes, this was probably never implemented. @dweller23 would you like to take a stab at it?
@holgergp you are also more than welcome to give it a try. :-) You have a failing test already, not it's just a matter of making it pass... ;-)

**Comment by holgergp** [comment]
Thx! I will have a look!
