### ISSUE TITLE
beforeEach recommendation not working as intended 

### ISSUE THREAD

**Issue by cookiescrumbs** [TheBrainFamily/cypress-cucumber-preprocessor#139]
It looks like the beforeEach hook is running before every feature and not just the one it's suppose to be related to... Please see screen shot from the example repo.

![image](https://user-images.githubusercontent.com/1229271/52184045-50ade800-2806-11e9-8a96-75c59144bac7.png)

**Log: "This will run before every scenario of GoogleNews.feature test, but NEVER for Facebook/Google feature files"**

**Comment by lgandecki** [comment]
oh wow, you are right - this happens when you run all feature files together in the cypress open GUI. 
But, when I create two js files:

```
beforeEach(() => {
  cy.log("This only before the first one");
});

describe("abcd", () => {
  it("dfsdfs", () => {});
});

```

and
```
beforeEach(() => {
  cy.log("This only before the second one");
});

describe("abc", () => {
  it("dfsdf", () => {});
});
```

it runs both befores when I run them together, but only one, when separately. I don't think this is how cypress should work. It makes little sense for the same test to behave the same when:
1) run separately
2) run with cypress run
but differently with
- running with cypress open when doing the "run all specs"

**Comment by lgandecki** [comment]
@cookiescrumbs cypress team acknowledged it as a bug on their side: https://github.com/cypress-io/cypress/issues/3323 . Thank you for the report, I'm closing this one for now as it is not related to our plugin. :-(

**Comment by joshiste** [comment]
As workaround you could guard the test, e.g:
```
beforeEach(() => {
  if (Cypress.spec.name !== 'Landingpage/travellerselection.feature') {
    return;
  }
  cy.visit('/');
  cy.get('#traveller-toggle').click();
});
```

**Comment by avikhazra** [comment]
@lgandecki : we are getting cucumber JSON as output.  How to use this JSON as an HTML cucumber report. Multiple cucumber report is recommended in github but it is creating report before the test starts. Could please help me with that.

**Comment by Avik-Guha** [comment]
> @lgandecki : we are getting cucumber JSON as output. How to use this JSON as an HTML cucumber report. Multiple cucumber report is recommended in github but it is creating report before the test starts. Could please help me with that.

I am also facing same issue. Multiple cucumber report is creating report before the test starts. Is there any solution for this?

**Comment by lgandecki** [comment]
Sorry, this is not a use-case me or any of our clients have. Feel free to create another issue, and one of the other maintainers might help you. 
We are always happy to take PRs as well. :)
