### ISSUE TITLE
On launch, spawns servers infinitely. 

### ISSUE THREAD

**Issue by MarinaTov** [TheBrainFamily/cypress-cucumber-preprocessor#140]
After npm install --save-dev cypress-cucumber-preprocessor

I've gotten

when yarn is working this error appears
`warning cypress-cucumber-preprocessor > @cypress/browserify-preprocessor > cjsxify > coffee-script@1.12.7: CoffeeScript on NPM has moved to "coffeescript"`

and after that

```Launching Flow server for /home/travis/build/Kufar/kufar-fe-re
Spawned flow server (pid=6283)
Logs will go to /tmp/flow/zShomezStraviszSbuildzSKufarzSkufar-fe-re.log
Launching Flow server for /home/travis/build/Kufar/kufar-fe-re
Spawned flow server (pid=6371)
Logs will go to /tmp/flow/zShomezStraviszSbuildzSKufarzSkufar-fe-re.log
Launching Flow server for /home/travis/build/Kufar/kufar-fe-re
Spawned flow server (pid=6459)
Logs will go to /tmp/flow/zShomezStraviszSbuildzSKufarzSkufar-fe-re.log
Launching Flow server for /home/travis/build/Kufar/kufar-fe-re
Spawned flow server (pid=6547)
Logs will go to /tmp/flow/zShomezStraviszSbuildzSKufarzSkufar-fe-re.log
Launching Flow server for /home/travis/build/Kufar/kufar-fe-re
Spawned flow server (pid=6638)
........

**Comment by lgandecki** [comment]
Hello MarinaTov, thanks for sing our software. It doesn't really seem related. Could you make a reproduction?

**Comment by MarinaTov** [comment]
Yes, I've reproduced it many time. The  problem disappears after `uninstall --save-dev cypress-cucumber-preprocessor` 

Adding /node_modules/cucumber/ in .flowconfig [ignore] doesn't help me. Maybe any conflict with other dependencies in my project? But I can't predict what can it be.

**Comment by lgandecki** [comment]
I would need a reproduction to try to understand what's going on. like a GitHub repo where this happens. Simplified is fine, I don't need your code

**Comment by MarinaTov** [comment]
I'm afraid It's impossible. I can copy some files from project, but this won't reproduce the problem

**Comment by lgandecki** [comment]
you have to put at least a bit of work, and try to reproduce it in a clean repo, otherwise I can't help you here. The coffeescript warning is probably not related (you can verify by removing the cypress-cucumber-preprocessor and installing @cypress/browserify-preprocessor itself).
There is a possibility that just having flow + cypress cucumber preprocessor causes some problems.

Also, I don't really understand where is this error coming from:

```
Spawned flow server (pid=6283)
Logs will go to /tmp/flow/zShomezStraviszSbuildzSKufarzSkufar-fe-re.log
Launching Flow server for /home/travis/build/Kufar/kufar-fe-re
........```

is it doing this during npm install? if it's npm start - please tell me how your start script looks like in the package.json

**Comment by MarinaTov** [comment]
The problem appears after `yarn validate` and build in Travis is failed. The same situation on a local machine

**Comment by k15a** [comment]
If it's still a problem for you try to add:

```
[ignore]
.*/node_modules/module-deps/test/invalid_pkg/package.json
```

to you .flowconfig

**Comment by lgandecki** [comment]
Stale issue, sorry to say but I don't know how to reproduce, the issue seems coupled to a specific project configuration. I'd be happy to take another look if someone has a similar problem. A reproduction would be great :)
