### ISSUE TITLE
let/ this usage

### ISSUE THREAD

**Issue by gituser3000** [TheBrainFamily/cypress-cucumber-preprocessor#141]
Hello!
I have a problem using 'let\this' in tests with plugin.
Accoring to docs of cypress(https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Variables), i can define variable, assign a value during tests and then use it.
As i see it right now, tests are 'precompiled', so assigning doesn't work.
Example:

```
  let testVar;
  Given('assigning, function () {
    cy.get("[data-qa=userName]").invoke("val").then(data=>{ testVar= data })
  })
  Given('using, function () {
    cy.get("whatever").contains(testVar)       // fail as testVar is null
  })
```

Same example with 'this.';

```
  Given('assigning, function () {
    cy.get("[data-qa=userName]").invoke("val").as("myVar");
  })
  Given('using, function () {
    cy.get("whatever").contains(this.myVar)       // fail
  })
```

Pre-compiling ?
```
  Given('assigning, function () {
   console.log("wtf")   // called before tests run ?
    cy.get("[data-qa=userName]").invoke("val").as("myVar");
  })
```
"cypress-cucumber-preprocessor": "^1.9.1",

**Comment by lgandecki** [comment]
what you are trying wouldn't work with cypress as well. The tests "precompile" with pure cypress as well :) They queue the commands on the "initial run through the code", so using variables the way people are used to doesn't work.

what you show here:

```javascript
 let testVar;
  Given('assigning, function () {
    cy.get("[data-qa=userName]").invoke("val").then(data=>{ testVar= data })
  })
  Given('using, function () {
    cy.get("whatever").contains(testVar)       // fail as testVar is null
  })
```
is not really the same as cypress example:

```
cy.get('#num').then(($span) => {
  // capture what num is right now
  const num1 = parseFloat($span.text())

  cy.get('button').click().then(() => {
    // now capture it again
    const num2 = parseFloat($span.text())

    // make sure it's what we expected
    expect(num2).to.eq(num1 + 1)
  })
})
```

Please try this : 
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#sharing-context

and let me know if it helps

**Comment by gituser3000** [comment]
Sure, my fault. Already ended up with the example from the main page.
What about using 'this'?

**Comment by lgandecki** [comment]
As per their example:

beforeEach(function () {
  // alias the $btn.text() as 'text'
  cy.get('button').invoke('text').as('text')
})

it('has access to text', function () {
  this.text // is now available
})

treat all your steps in a scenario as one it (we can't change it unfortunately, till cypress allows us to keep state between tests in a specific group).

So, if you do set up beforeEach that sets something to `this`, you can access that this in a given/when/then steps. But not between given/when/then, the same way you couldn't do:

```javascript
it('has access to text', function () {
  cy.get('button').invoke('text').as('text')
  this.text 
})
```
