### ISSUE TITLE
Is the "Rule" keyword supported?

### ISSUE THREAD

**Issue by NielsInc** [TheBrainFamily/cypress-cucumber-preprocessor#143]
In the Gherkin v6 [spec](https://docs.cucumber.io/gherkin/reference/#rule), the `Rule` keyword was added. 

When I add this keyword, a parsing exception is thrown: 

    CompositeParserException: Parser errors:
    (12:3): expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, 
    #ScenarioOutlineLine, #Comment, #Empty, got 'Rule: 

Are there any plans to include the keyword, or is it not yet on the roadmap since it hasn't been incorporated into all implementations of Cucumber yet?

**Comment by lgandecki** [comment]
It's not, and no immediate plans as we don't need it at the moment. Happy to take a PR!

**Comment by badeball** [comment]
The Rule keyword was introduced in v6 of Gherkin and this version of the JavaScript implementation has quite different API and is built on top of a shared Go executable (IE. can't work in a browser at all. Not sure if parsing of features happens in Node or browser context). The native JavaScript implementation of Gherkin is however being [restored](https://github.com/cucumber/cucumber/pull/689), which will allow the Rule keyword to more easily be implemented here.

**Comment by ngalluzzo** [comment]
Any thoughts when you'll get around to merging a PR? Really excited for the rules feature!

**Comment by irahov** [comment]
I'd like to emphasize the importance of Rule support, especially in big projects.
If you think that cypress-cucumber-preprocessor is suitable for enterprise projects please do add that support or at least provide some feedback when this can be expected.

The current behavior is a bit strange.
I add just one `Rule:` and `Background:` in it. - OK
I  add two rules - NOT OK
I add `Feature:` `Background:` `Rule:` -  NOT OK

By NOT OK I mean there is a parse error:
```
Error: Webpack Compilation Error
./cypress/integration/edge-gateway-l2vpn.feature
Module build failed (from ./node_modules/cypress-cucumber-preprocessor/loader.js):
CompositeParserException: Parser errors:
```

**Comment by badeball** [comment]
> If you think that cypress-cucumber-preprocessor is suitable for enterprise projects please do add that support or at least provide some feedback when this can be expected.

This is a MIT-licensed project and I think I can say firmly now that none of the authors would like you think anything. Use it at your own will.

**Comment by badeball** [comment]
Closed as duplicate, with multiple issues referenced.

**Comment by irahov** [comment]
Hi,
With my previous note, I didn't mean to be harsh. I'm sorry for that.
My frustration came from the fact that people were asking questions and there had been no responses for months even for more than half a year. Also when I used 'enerprise' I didn't mean 'a company', but rather something serious.
Also a MIT project doesn't mean lots of features and fulfilling everybody's desires, but it also does not exclude accountability, where the maintainers answer questions.
Once again I'm sorry if I had been harsh.
