### ISSUE TITLE
ReferenceError: Unknown option: .caller.

### ISSUE THREAD

**Issue by uchoaaa** [TheBrainFamily/cypress-cucumber-preprocessor#144]
Hi there,

I'm getting this error on my Quasar Framework (Vue.js) app. What am I doing wrong? 🤔 

Any help will be appreciated.

Cheers

**Comment by lgandecki** [comment]
Hello, unfortunately that's not enough details for us. Could you show us the whole stack trace? And preferably - a small reproduction?

**Comment by xanke** [comment]
Upgrade @babel/core to 7.5.5
