### ISSUE TITLE
Unable to specify configuration in lerna repo with hoisted packages

### ISSUE THREAD

**Issue by akatechis** [TheBrainFamily/cypress-cucumber-preprocessor#146]
I've got a lerna repo with packages/* packages and apps/* packages. In one of my apps, I've added `cypress` and `cypress-cucumber-preprocessor`. When I go through the example, I'm able to get my .feature file detected by the cypress runner, but when I execute it, it doesn't detect any step definitions.

I added some logs to see where the issue might be, and I can see that the cosmiconfig is not finding any configuration even though I've tried adding the section to `package.json` as well as in an external file. I suspect the issue is with the fact that the cosmiconfig package has been hoisted out of my app directory's `node_modules` and put into the root `node_modules`.

Is there some other way to configure the preprocessor without relying on cosmiconfig, or alternatively, "dumping" all the paths that the tool searches for step definitions in order to just put them in the right place without configuration?

Please let me know if you require additional info.

Thanks.

**Comment by lgandecki** [comment]
Hello @akatechis. Thanks for using our package (or at least trying!)
Could you make a small repro for us?

**Comment by akatechis** [comment]
Hi @lgandecki, I was able to get past this issue, seems like I was neglecting some configuration. Now, when I click on the feature file, I see that the runner seems to be requesting the step definitions correctly, as seen in the console below:

```
GET /__/ 200 109.588 ms - -
GET /__cypress/runner/cypress_runner.css 200 36.809 ms - -
GET /__cypress/runner/cypress_runner.js 200 353.462 ms - -
GET /__cypress/runner/fonts/fontawesome-webfont.woff2?v=4.7.0 200 2.766 ms - 77160
GET /__cypress/iframes/integration/Registration.feature 200 7.572 ms - 737
[ 'C:/Users/Alexandros/workspace/pefin/web/apps/classic/cypress/support/step_definitions/common/Common.js',
  'C:/Users/Alexandros/workspace/pefin/web/apps/classic/cypress/support/step_definitions/Registration/Registration
.js' ]
GET /__cypress/tests?p=cypress%5Csupport%5Cindex.js-444 200 1191.530 ms - 625
GET /__cypress/tests?p=cypress%5Cintegration%5CRegistration.feature-699 200 3633.608 ms - -
HEAD / 500 4508.345 ms - -
HEAD / 500 4506.053 ms - -
HEAD / 500 4505.590 ms - -
```

I still get the same issue, in the automation UI, mentioning no steps defined.
![image](https://user-images.githubusercontent.com/1058931/53823253-61559900-3f3f-11e9-820e-7bc7a793eccc.png)

My .feature file looks like:

```

I'll try to put together a repro, and see if that helps.

**Comment by akatechis** [comment]
Sorry for the multiple edits, I fat-fingered some of the code snippets as I was pasting

**Comment by akatechis** [comment]
Finally figured this out, I was iterating on the phrase in my feature file, and without realizing it, the matcher in the step definition did not match what was in the feature file.

Apologies for taking up your time, and thank you so much for such an awesome tool. I was only recently made aware of cucumber and cypress, and using them together unlocks so many possibilities for us. I'm really excited to get the rest of my team on board with this.

Thanks!

**Comment by lgandecki** [comment]
Thank you for kind words @akatechis ! Feel free using this space if you need any help. :-)
