### ISSUE TITLE
Better way to run a implementation with different expressions

### ISSUE THREAD

**Issue by paurakhsharma** [TheBrainFamily/cypress-cucumber-preprocessor#148]
I want to run certain implementation with different expressions.
I have some step which is `given` step for certain scenario but `when` step for other scenario

For example:
In one scenario I have 
`When a user has browsed to the homepage`
On the other scenario I might use it in `given` step
`Given the user has browsed to the homepage`

I want same implementation to run in both cases,
My current solution looks like this:
![image](https://user-images.githubusercontent.com/20378877/53869331-1e1f2700-4020-11e9-88b9-e77d9a05bbe1.png)

But It would be impractical to do this for longer implementations (then I might define a new function an call the same function from both implementations) I don't think this is also a good idea.

So, my question is can we have something like this:
![image](https://user-images.githubusercontent.com/20378877/53869919-46f3ec00-4021-11e9-821a-8ae27a212187.png)

I know the syntax looks funny but there can be a better way.

This is how it's done in PHP Behat.
![image](https://user-images.githubusercontent.com/20378877/53869590-a1407d00-4020-11e9-838b-e52869005c63.png)

But I was wondering if I can do something similar in Cypress.

**Comment by lgandecki** [comment]
try
```javascript
const adminLogsInUsingTheWebUi = () => { cy.visit("/") }

Given('the user has browsed to the home page', adminLogsInUsingTheWebUi);
When('the user browses to the home page', adminLogsInUsingTheWebUi)
```

**Comment by paurakhsharma** [comment]
@lgandecki Yeah, this seems to be the best way. Thank you
