### ISSUE TITLE
Typescript: "Uncaught Error: Your OS "browser" is currently not supported by node-cachedir."

### ISSUE THREAD

**Issue by Dragon160** [TheBrainFamily/cypress-cucumber-preprocessor#149]
When using Cypress with the cypress-cucumber-preprocessor plugin it works pretty good until I switch to typescript.
So 'normal' cucumber with stepdefinitions written in *.js is working.

### Expected behaviour

Should work also with typescript.

### Actual behaviour 

After executing the test via `cypress run` or `cypress open` the test stops with the following error message:

> Uncaught Error: Your OS "browser" is currently not supported by node-cachedir. This error originated from your test code, not from Cypress. When Cypress detects uncaught errors originating from your test code it will automatically fail the current test. Cypress could not associate this error to any specific test.

### My Setup

Node version: v11.10.1
Npm version: 6.8.0
Cypress version: 3.1.5

#### package.json
`{
  "name": "bddtests",
  "version": "1.0.0",
  "description": "Contains all behaviour and acceptance tests",
  "main": "index.js",
  "scripts": {
    "test:ci": "cypress run",
    "test": "cypress open"
  },
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@types/node": "^11.10.4",
    "cypress": "^3.1.5",
    "cypress-cucumber-preprocessor": "^1.11.0",
    "tsify": "^4.0.1",
    "typescript": "^3.3.3333"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
}
`

#### cypress.json
`{
    "ignoreTestFiles": ["**/*.ts", "**/*.js"],
    "video": false,
    "fixturesFolder": false
}
`

#### cypress/tsconfig.json
`{
  "compilerOptions": {
    "strict": true,
    "baseUrl": "../node_modules",
    "target": "es5",
    "lib": ["es5", "dom"],
    "types": ["cypress"]
  },
  "include": [
    "**/*.ts"
  ]
}`

#### cypress/plugins/index.js
```
const cucumber = require("cypress-cucumber-preprocessor").default;
const browserify = require("@cypress/browserify-preprocessor");

module.exports = (on) => {
  const options = browserify.defaultOptions;
  options.browserifyOptions.plugin.unshift(['tsify', {project: '../tsconfig.json'}]);
  on("file:preprocessor", cucumber(options));
};
```

#### Test structure

cypress/Login.feature
cypress/Login/Login.ts

Is anybody capable of reproducing this error?

**Comment by lgandecki** [comment]
Can you try setup like here: https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example  ? Maybe we should just suggest webpack for typescript  if that's less problematic.

For the code above - could you make a reproduction and push to github?

**Comment by lgandecki** [comment]
@Dragon160 @sabaansari86 @persistence911 @misamisk @syedfaizanalef if this is still an issue for any of you, please try the setup provided in the example configuration. If that works - can you try to follow the configuration pattern from there? If you don't want to use webpack, there is another example here:
https://github.com/TheBrainFamily/cypress-cucumber-typescript-example/

If things still don't work for you, please create a reproduction (based on the example would be great and quick to do!), and I will do my best to fix. Closing for now as I haven't heard from any of you for months, but I will be happy to reopen once someone adds some more information here.
