### ISSUE TITLE
Running Cypress in headless mode only shows "Scenario"

### ISSUE THREAD

**Issue by jaterlwj** [TheBrainFamily/cypress-cucumber-preprocessor#151]
Hi cypress-cucumber-preprocessor team,

I would like to first express my thanks on such a wonderful work that you guys done and contributed.I am recently using cypress-cucumber-preprocessor as part of my workflow to write tests in Cucumber. 

However, I have noticed that reporters are only reporting pass/fail cases as a whole "Scenario" and not for each step definitions (Given, When Then). Is this a normal behaviour or an issue? I have noticed it in both "spec" reporter and the "mocha-allure-reporter" reporter. I would love to be able to view each step as an individual test spec rather than just the scenario as a whole in the reporter. 

If there is a recommended or specific reporter to exhibit this behaviour that I'm interested in, please do point me in the right direction. I have uploaded my [sample project here](https://github.com/jaterlwj/Cypress-Cucumber-Test).

Kind regards,
Jater

**Comment by lgandecki** [comment]
Thanks @jaterlwj !

Unfortunately, I don't have good news for you. We are still waiting for
https://github.com/cypress-io/cypress/issues/686
to be implemented.

Please read here for more details:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/44
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/90

**Comment by jaterlwj** [comment]
Thanks for your response @lgandecki ! 

Appreciate the clarifications and I understand the reasoning behind it now.
