### ISSUE TITLE
Ability to ignore the feature file that does not have the tag to run?

### ISSUE THREAD

**Issue by smithabethi** [TheBrainFamily/cypress-cucumber-preprocessor#159]
I have feature files:
a.feature
@smoketest
scenario

b.feature
@regtest

c.feature
@smoketest

Now when i pass tag as @smoktest (cypress run --env tags=@smoketest) it should just pick a.feature and c.feature as b.feature doesnt have @smoketest tag. But cypress still opens up browser for b.feature file and closes. Can we ignore feature files which does not have tag.

**Comment by lgandecki** [comment]
That would be preferable, yes. Currently not supported. I'd be happy to take a PR.

**Comment by lgandecki** [comment]
We've added a new wrapper that allows this, please take a look here:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#tagging-tests

and at the example provided in that section.

Thanks!
