### ISSUE TITLE
Tags not working as expected

### ISSUE THREAD

**Issue by elisa-dc** [TheBrainFamily/cypress-cucumber-preprocessor#161]
Hello, 
I have the following feature files and tags:

Feature1.feature:
@regression 
Scenario: Scenario1 
....

Scenario: Scenario2
....

Feature2.feature:
Scenario: Scenario3
...

------------------------------------------------
I run my tests with the following command: 
cypress run --env tags=@regression --browser chrome

Expected: only Scenario1 is run
Actual: all 3 scenarios are run

Is my command correct? 

Thanks a lot

**Comment by anilkoithara** [comment]
please read this might help you https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/156

**Comment by lgandecki** [comment]
@elisa-dc please check if everything works properly when you clone our example repo - https://github.com/TheBrainFamily/cypress-cucumber-example , if it does, and yours still doesn't, please make a simple reproduction. I played around with tags extensively, and I'm 100% confident they do work in general, so there is not enough details in your issue for me to figure out what's possibly wrong.

**Comment by lgandecki** [comment]
I'm closing this for now. @elisa-dc if you still need help please try to use the example repo with tags and see if they work properly for you. Playing around with it you might be able to explain what's the difference between the example and what you are trying to do - and we might be able to fix the issues.
