### ISSUE TITLE
Provide defineStep to define generic steps

### ISSUE THREAD

**Issue by josselinbuils** [TheBrainFamily/cypress-cucumber-preprocessor#172]
Hello,

First, thank you for your work 🙏

Could it be possible to have access to the cucumber defineStep method to be able to create generic steps as some of them could either be used in a Given or a When for example ?

**Comment by lgandecki** [comment]
Hello, thanks!

You can define your steps with any keyword and they will be usable (For example - define with Given and use as When).
If you feel there should be another method that defines but is not one of the exposed functions, please feel free to add a PR that adds this command (it should internally do exactly the same thing that Given/When/Then/And/But are doing). Should be rather trivial to do :)

Thanks.

**Comment by lgandecki** [comment]
This is released now, thanks!
