### ISSUE TITLE
Unable to create different steps(.ts) files for different feature files using typescript 

### ISSUE THREAD

**Issue by dfawole** [TheBrainFamily/cypress-cucumber-preprocessor#174]
@lgandecki 
Need your assistance , I have different feature files that is testing different part of the system and I wanted to create different steps in .ts files to test each features, following the examples you gave , I can only create on step file(.ts) for all the feature files, when I created a folder for other steps, I got the below error

```
 ./cypress/integration/Mobile/mobile.ts
Module not found: Error: Can't resolve 'cypress-cucumber-preprocessor/mobile' in '/Users/myUser/Documents/game-test/cypress/integration/Mobile'
resolve 'cypress-cucumber-preprocessor/mobile' in '/Users/myUser/Documents/game-test/cypress/integration/Mobile'
Parsed request is a module
using description file: /Users/myUser/Documents/game-test/package.json (relative path: ./cypress/integration/Mobile)
Field 'browser' doesn't contain a valid alias configuration
resolve as module
/Users/myUser/Documents/game-test/cypress/integration/Mobile/node_modules doesn't exist or is not a directory
```
I did set

```
"cypress-cucumber-preprocessor": {
   "nonGlobalStepDefinitions": true
 }
```

And when I use the same step file ( .ts ) for different feature files i got :
`Error: Step implementation missing for: I am on mobile`

I have created a repo for you to have a look :[https://github.com/dfawole/tests.git]( https://github.com/dfawole/tests.git
)
Please what am i doing wrong and Thanks in advance

**Comment by lgandecki** [comment]
@dfawole  the repo seems to be private, could you make it public?

**Comment by dfawole** [comment]
@lgandecki 
I have given you access now 
[https://github.com/dfawole/tests/invitations](https://github.com/dfawole/tests/invitations)

**Comment by dfawole** [comment]
Thanks for your quick response

**Comment by lgandecki** [comment]
I would still prefer you made it public - why do you want to limit the audience just to yourself. Someone might stumble upon the same problem and they will end up hitting a dead link. Not very nice, especially if you are asking for a free help :)

but anyway, the problem is that you can't use const {something} = require('module') in multiple files,
I will tweak this in the example repo. 

https://github.com/dfawole/tests/pull/1

is your solution,

 btw, please do not install cucumber and cucumber types :)

**Comment by dfawole** [comment]
@lgandecki 

Thanks for your help .... I have made it public and it was an oversight from my side
