### ISSUE TITLE
How to fix the problem with tags that doesn't work (windows)!

### ISSUE THREAD

**Issue by gabrielcartelli** [TheBrainFamily/cypress-cucumber-preprocessor#175]
In windows, the tags doesn't work because there is a problem in \node_modules\cypress-cucumber-preprocessor/cypress-tags.js.

For to fix, you need to alter the line 50 of the cypress-tags.js

how is:
${__dirname}/../.bin/cypress,

how have to be:
process.platform == 'win32' ? ${_dirname}/../.bin/cypress.cmd : ${_dirname}/../.bin/cypress,

https://github.com/gabrielcartelli/cucumber-fixed-up.git

**Comment by lgandecki** [comment]
Hey thanks, would you be able to create a PR with this change ? :)

**Comment by gabrielcartelli** [comment]
> Hey thanks, would you be able to create a PR with this change ? :)

Of course!
https://github.com/gabrielcartelli/cucumber-fixed-up.git

**Comment by nickdunn** [comment]
I've created a PR: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/178

**Comment by lgandecki** [comment]
This is released now, thanks to both of you!
