### ISSUE TITLE
Works on Windows, fails on Linux

### ISSUE THREAD

**Issue by edoloughlin** [TheBrainFamily/cypress-cucumber-preprocessor#186]
I opened [issue 4557](https://github.com/cypress-io/cypress/issues/4557) on the main Cypress repo but thought I'd link it here in case anyone has seen this. 

I'm using cypress-cucumber-preprocessor on a new Angular 8 project. Cypress runs fine on Windows. The logs show that it's using `browersify` to run its `plugins/index.js` file. On Linux, it's using `webpack` and the `plugins/index.js` file doesn't get run. I don't know why it's picking webpack on Linux...

**Comment by lgandecki** [comment]
I asked a question on https://github.com/cypress-io/cypress/issues/4557 about this issue, please tag me there or here when you answer. The preprocessor repo runs on linux on circleCI (with webpack, typescript, and this repo itself), and on countless installations by people using it, so we know it works on Linux. :) 
We need more info.
