### ISSUE TITLE
Parse error when the feature file has Examples

### ISSUE THREAD

**Issue by ldsenow** [TheBrainFamily/cypress-cucumber-preprocessor#187]
Hi there,

I am having issue in the feature file as long as I put in the Examples section.
Below is my feature file

Feature: Login
    Background:
        Given I am in Login page

    Scenario: User with 2FA enabled should encounter 2FA challenge during authentication
        And I enter a valid "<username>"
        And I enter a valid "<password>"
        When I click the "Log In" button
        Then I should encounter 2FA challenge

    Scenario: User with 2FA disabled should not encounter 2FA challenge during authentication
        And I enter a valid "<username>"
        And I enter a valid "<password>"
        When I click the "Log In" button
        Then I should not encounter 2FA challenge

    Examples:
    | username  | password  |
    | user1    | 123456 |

The exception is below
expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Examples:'

Anyone having this issue and a solution for it?

**Comment by akaan** [comment]
This is a Gherkin parse error. Examples need to be embedded in Scenario outlines blocks : see https://cucumber.io/docs/gherkin/reference/#scenario-outline

**Comment by colinwirt** [comment]
> This is a Gherkin parse error. Examples need to be embedded in Scenario outlines blocks : see https://cucumber.io/docs/gherkin/reference/#scenario-outline

on this topic @akaan are you aware if Gherkin  v6 will be supported by the preprocessor?

That will make it much easier to teach the syntax to new starters as tens like Scenario Outline will no longer be required.

**Comment by lgandecki** [comment]
Not sure how those two things are connected but I don't think there is any reason to NOT support gherki v6. We haven't got around to it yet, but it should be a straightforward update. I'd be happy to take a PR as well :) 

Closing this for now, thanks @akaan for helping out @colinwirt !
