### ISSUE TITLE
Does tags and hooks work?

### ISSUE THREAD

**Issue by jlin412** [TheBrainFamily/cypress-cucumber-preprocessor#19]
I don't mentioning anyway mentioning if tags and hooks work.
Also, I like to mention that multiple features execution seem to be a problem.
https://github.com/TheBrainFamily/cypress-cucumber-example/issues/2

**Comment by lgandecki** [comment]
@jlin412 I answered there about the multiple features - I don't think that is actually a problem - this repo uses multiple features execution as a CI step.

As for tags/hooks. It's not that they don't work. They are not implemented, this is a very new project - we would love to accept a PR :) 
I'm going to keep this open and eventually someone will pick it up.

**Comment by lgandecki** [comment]
Btw, actually, it would be great, if not PR, if you could create separate separate issues for:
1) tags
2) hooks

and explain in both what functionality would you expect, if possible with external examples or links to cucumber documentation, that would greatly help whoever decides to implement it.

**Comment by jlin412** [comment]
You can close issue now if you want.
I create two separate issues for tags and hooks.
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/25
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/26

**Comment by lgandecki** [comment]
Thanks!
