### ISSUE TITLE
[feature request]: allow tagged template expressions in Scenario Outline

### ISSUE THREAD

**Issue by daniellizik** [TheBrainFamily/cypress-cucumber-preprocessor#194]
When running cypress tests that looks something like this

```cucumber
Feature: Some Foo

  Scenario Outline: Can foo my bar
    Given some <amount> of foobar where <condition>

    Examples:
    | amount | condition
    | 12     | "my dog is brown"
    | 1      | "my banana is also brown"
```
The logged output will be

```
  Some foo

    ✓ Can foo my bar (example #1) (5ms)

    ✓ Can foo my bar (example #2) (5ms)
```
I think it'd be more helpful if we could use tagged template expressions in the scenario outline title like you can in [`jest.each`](https://jestjs.io/docs/en/api#2-testeach-table-name-fn-timeout). For example:

```cucumber
Feature: Some Foo

  Scenario Outline: Can foo $amount times when my bar is $condition
    Given some <amount> of foobar where <condition>

    Examples:
    | amount | condition
    | 12     | "my dog is brown"
    | 1      | "my banana is also brown"
```
output
```
  Some foo

    ✓ Can foo 12 times when my bar is "my dog is brown" (5ms)

    ✓ Can foo 1 times when my bar is "my banana is also brown" (5ms)
```

Might just need to modify [this bit](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/ff1f41ff53036356ee682253b88cdccdb77b0bd5/lib/createTestFromScenario.js#L102) a bit.

**Comment by jcundill** [comment]
I think that this is partially correct. The (example #N) bit should probably just be removed from the scenarioName, it got added on the cucumber.json generation pull request.

However tagged template expressions are already supported

For the example Scenario Outline test in the distribution

<img width="532" alt="Screenshot 2019-07-29 at 20 05 46" src="https://user-images.githubusercontent.com/49795386/62076003-86c0a780-b23e-11e9-9c6f-0ce44e65e366.png">

You can see that the second scenario outline has tags in the name, but the first one has no tags in the name 

When run, we get

<img width="401" alt="Screenshot 2019-07-29 at 20 07 00" src="https://user-images.githubusercontent.com/49795386/62075981-73add780-b23e-11e9-92d3-d5e8236be427.png">

You can see the tags replaced in the use juicer with .. examples.


I agree that this looks a lot neater reverted to

<img width="551" alt="Screenshot 2019-07-29 at 20 17 41" src="https://user-images.githubusercontent.com/49795386/62075931-54af4580-b23e-11e9-9d59-c350c5aac16f.png">

 
In the jest example given, couldn't that just be written as

```
Feature: Some Foo

  Scenario Outline: Can foo <amount> times when my bar is <condition>
    Given some <amount> of foobar where <condition>

    Examples:
    | amount | condition
    | 12     | "my dog is brown"
    | 1      | "my banana is also brown"
```
Or did you have something else in mind?

**Comment by daniellizik** [comment]
Ah it's already available, awesome! Thanks for your help.
