### ISSUE TITLE
vscode extension to map implementation with steps in feature file

### ISSUE THREAD

**Issue by amitguptagwl** [TheBrainFamily/cypress-cucumber-preprocessor#199]
Do we have or working on (if not then its a feature request) some vscode extension to traverse to step implementation when I Ctrl + click on a step in feature file?

**Comment by jcundill** [comment]
It already exists - search for 'Cucumber (Gherkin) Full Support' in extensions

To wire it up to recognise cypress cucumber features and their corresponding steps, you'll need something like the following in settings.json

```
    "cucumberautocomplete.steps": [
        "cypress/integration/*/*.js"
     ],
    "cucumberautocomplete.syncfeatures": "cypress/integration/*.feature",
    "cucumberautocomplete.strictGherkinCompletion": false,
    "cucumberautocomplete.smartSnippets": true,
    "cucumberautocomplete.stepsInvariants": true
```

**Comment by amitguptagwl** [comment]
thanks. It works. But can't I avoid hardcoding path in settings. For example, if I open some java project having feature file, will it not cause issue?

**Comment by jcundill** [comment]
https://vscode.readthedocs.io/en/latest/getstarted/settings/

Maybe workspace scope is what you are looking for?

**Comment by amitguptagwl** [comment]
changes in `settings.json` are not working properly. They work for some step definitions and not for others. :( Will try with workspace scope.

**Comment by lgandecki** [comment]
Maybe the problems are similar to the ones explain in Webstorm section, could you doublecheck?
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#webstorm-support

Also, @jcundill thanks so much for all your support recently! I've added you as a collaborator to this repo, so feel free to work directly on this one, make branches, send PRs, and review others. Seems like you are using this project a lot so I want to enable you as much as possible to not be blocked by  me and the rest of the team here.

**Comment by amitguptagwl** [comment]
@lgandecki I'm using the vscode actually. And I'm using capitalized Given/When/Then function names.

**Comment by amitguptagwl** [comment]
I created a `.vscode/settings.json` and used `**` for folder name in the path and it solved the problem for the time being. Thanks for your attention.
