### ISSUE TITLE
Extra irrelevant code in test report instead of the steps written in feature file

### ISSUE THREAD

**Issue by amitguptagwl** [TheBrainFamily/cypress-cucumber-preprocessor#200]
### Current behavior:

![Screenshot from 2019-08-06 14-21-28](https://user-images.githubusercontent.com/7692328/62525725-897e5680-b855-11e9-8a95-6ce649d1b211.png)

Adding this piece of code in report with every scenario.
```js
if (backgroundSection) {
  backgroundSection.steps.forEach(step => stepTest.call(this, step));
}
scenario.steps.forEach(step => stepTest.call(this, step));
```
### Desired behavior:
It should show the list of steps instead of the code

**Comment by jcundill** [comment]
@amitguptagwl 

I'm not seeing the behavior mentioned above, when I define a Scenario with missing step

<img width="551" alt="Screenshot 2019-08-07 at 20 20 24" src="https://user-images.githubusercontent.com/49795386/62651794-b3b53e80-b951-11e9-8e6b-e00899ce5c77.png">

Here the underlined step is not defined

And then run that scenario through` npx cypress open` then I see the following in the runner

<img width="692" alt="Screenshot 2019-08-07 at 20 20 49" src="https://user-images.githubusercontent.com/49795386/62651862-d8a9b180-b951-11e9-95c3-f8ada68e3494.png">

If I generate cucumber.json files and push this into a cucumber report, I see

<img width="804" alt="Screenshot 2019-08-07 at 20 24 57" src="https://user-images.githubusercontent.com/49795386/62651910-f6771680-b951-11e9-8477-8aab94481280.png">

This looks as expected to me - maybe you can post an example with more details to help me reproduce the issue you are seeing.

Are you using the cypress dashboard service - is that the only place where you are seeing this behavior, or does it cause this problem locally as well?

**Comment by amitguptagwl** [comment]
In my case, all the steps are implemented. However, I'm generating the report using mochawesome. That can be the issue. I'm not able to generate `cucumber.json` as per the guidelines given on the README.md

```json
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/report",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  }
```

**Comment by jcundill** [comment]
mochawesome reporter is a known issue - see https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/155#issue-428861156 - can you maybe close this as a duplicate of that issue.

cucumber.json file generation isn't in    `"cypress-cucumber-preprocessor": "1.11.2"` you'd need to upgrade to ^1.13.0

**Comment by amitguptagwl** [comment]
Thanks for your help. I'm able to generate the report now. However, it is generating one report for each feature file. So do we have some utility which can combine them.

**Comment by amitguptagwl** [comment]
Thanks a lot for your help.
