### ISSUE TITLE
global context for end to end test

### ISSUE THREAD

**Issue by amitguptagwl** [TheBrainFamily/cypress-cucumber-preprocessor#201]
I'm writing the end-to-end tests to test scenarios where I start my journey from one page and traverse through other pages. I'm creating some page object who knows how to select particular element on the page. Eg
```js
export default class PageName extends BasePage{
     //..
    subtab = heading => cy.get(`[data-qa-sub-tab-name="${heading}"] > a`)
}
```
I'm setting the object of above page class in `global.currentPage` at the time loading a page. so that I can access it in the implementation of other steps and call particular method. Eg

```js
Then(/subtab "(.*)" is  selected/, (subTabHeading) => {
  currentPage.subtab(subTabHeading).should("have.class","active");
});

And(/I select "(.*)" subtab/, (subTabHeading) => {
  currentPage.subtab(subTabHeading).click();
});
```
However, I feel this is not the correct approach. Because, though not sure, cypress can run multiple tests at a time. Every test can set the page object. So a step implementation can get the wrong page object.

This problem doesn't come in mocha style testing because all the steps are under one `describe` section. But in case of cucumber style, steps can be written on different place.

So have you provided some mechanism to set scenario scoped global object ? The alternate solution is to create a pool of page objects and every step take the page object from the pool. Eg

```js
Then(/subtab "(.*)" is  selected/, (subTabHeading) => {
  pages("pagename").subtab(subTabHeading).should("have.class","active");
});

And(/I select "(.*)" subtab/, (subTabHeading) => {
  pages("pagename").subtab(subTabHeading).click();
});
```

I don't find it good.

**Comment by jcundill** [comment]
> I'm setting the object of above page class in global.currentPage at the time loading a page. so that I can access it in the implementation of other steps and call particular method

Does this [discussion of reusable step definitions](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#reusable-step-definitions) help, or maybe see [this cypress discussion on the role of PageObjects](https://docs.cypress.io/faq/questions/using-cypress-faq.html#Can-I-use-the-Page-Object-pattern) in cypress tests

**Comment by amitguptagwl** [comment]
I checked both links. But they don't fit here.

We need the page object so if there is any change in the DOM structure, actual steps will not be changed as the logic is abstracted to one place. 

In addition, in the world of react programming where we can use the same component on multiple pages, there is a possibility to use the same steps for the scenarios of different pages. Hence, the second suggestion I gave in the above example `pages("pagename")` is not correct.

So I believe we need a scenario level variable. which can be injected to the Given\When\Then method.

**Comment by lgandecki** [comment]
Sorry, I'm not sure I'm following as well, but have you tried this:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#sharing-context ?

Also, cypress won't run multiple tests at the same time, so you don't have to worry about that.

**Comment by amitguptagwl** [comment]
sharing context is related to an element return by cypress itself. But in my context, it is a custom object.

> Also, cypress won't run multiple tests at the same time, so you don't have to worry about that.

If this is true then I'm doubtful that why don't they start multiple tests at the same time? And there is always a chance they can do it in future. So it'll break my implementation.

**Comment by amitguptagwl** [comment]
My requirement is similar to this

https://www.youtube.com/watch?v=hMiBundGmNA

**Comment by amitguptagwl** [comment]
Is it possible to inject the scenario context to each method as method param? Eg

```js
Then(/click (.*) button/, (context, buttonLabel) => {
    //some implementation
});
```

**Comment by jcundill** [comment]
you can achieve what you are trying to do using Cypress.state() or cy.state() https://github.com/cypress-io/cypress-documentation/pull/805/commits/0036ec9495420909f8de26ce00107370ce3953f9

But, honestly, I would read https://semaphoreci.com/community/tutorials/using-page-objects-with-protractor-and-cucumber-in-angular-applications to understand a more javascript way of doing this.

They are page objects - no need to make class, or if you really want a class instantiate it in the that classes module export - then just require require in your step definitions file.

**Comment by amitguptagwl** [comment]
Thanks for highlighting `cy.state`. It may be useful in this case. I didn't find it in their docs. Will give it a try.
