### ISSUE TITLE
Cypress Custom Commands

### ISSUE THREAD

**Issue by OlaFawole** [TheBrainFamily/cypress-cucumber-preprocessor#202]
@lgandecki  Gandecki
Apologies to have tagged you with this issue but would really appreciate your help. I am trying to create Cypress Commands in other to use it in my step definitions but not working, Do I need to import it to all my steps definition files?  I don't know what am doing wrong... thanks in advance for your help. below is the snippet i add in my cypress/support/commands.js file 

``` javascript
Cypress.Commands.add("setNumber", ({set_number}) => {
   let newFleet = set_number.split(" ", 3)
   let fleel = Cypress._.without(newleet, '&')
   let sets_number = Cypress._.chain(fleel).map(function(o) {
     return "37"+ o
   }).head().value()
 })
```

**Comment by lgandecki** [comment]
first get it working without cucumber, once that works you should be able to use it in cucumber the same way.
If it works without cucumber, but not with it, please show an error.

**Comment by OlaFawole** [comment]
@lgandecki  
Thanks it did work but my text editor(WebStorm) couldn't resolve it

**Comment by lgandecki** [comment]
not sure what you mean, but if it works, I'm closing :)  if not, please reopen.
