### ISSUE TITLE
Scenario outlines not pulling variables from examples if same variable is used more than once

### ISSUE THREAD

**Issue by nipunsaini** [TheBrainFamily/cypress-cucumber-preprocessor#203]
Suppose you have a below usecase ->

```
Scenario Outline: Multiple variables <here> and <here>
   When I pass variable "123-<here>" and "<here>"
   Then I only see variable is replaced at first index only
Examples:
   | here |
   | abc  |
   | xyz  |
```

Then Scenario Title is resolved as `Multiple variables abc and <here> (example #1)` and similar is the case with steps.

It should resolve the variables at all indices in steps/scenario outline. i.e `Multiple variables abc and abc (example #1)`

**My Research:**

I checked the method which is doing this manipulation i.e `replaceParameterTags`  at [here](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/createTestFromScenario.js#L6)

So I tested the method with below code:
```
const rowData = {
  "here": "abc"
};

const text = "Multiple variables <here> and <here>";

const replaceParameterTags = (rowData, text) =>
  Object.keys(rowData).reduce(
    (value, key) => value.replace(`<${key}>`, rowData[key]),
    text
);

const scenarioName = replaceParameterTags(rowData, text);

console.log(scenarioName);
```
and it outputs:
`Multiple variables abc and <here>`

Hope this will help resolving this issue.

**Comment by lgandecki** [comment]
yeah, makes sense.. we should replace all instead of the first one. should be easy. @nipunsaini maybe you would like to work on this, since you got so close already?
We should start with a failing .feature file, similar to the example you've pasted

**Comment by nipunsaini** [comment]
@lgandecki  Yeah, definitely, Will raise a PR soon.

**Comment by jcundill** [comment]
Fixed by pull request from @nipunsaini
