### ISSUE TITLE
Error: Step implementation missing for: I open Google page

### ISSUE THREAD

**Issue by Nodeocrat** [TheBrainFamily/cypress-cucumber-preprocessor#208]
<img width="1676" alt="Screenshot 2019-08-20 at 20 35 23" src="https://user-images.githubusercontent.com/10661106/63378944-2cbd8880-c38b-11e9-95ab-2b482c6e079c.png">

I have followed the guide in the README.md word for word but I keep getting this error. My feature file is at `cypress/integration/google.feature` and my step file is at `cypress/support/step_definitions/google.js` Would appreciate if anyone could help.

Thanks

**Comment by lgandecki** [comment]
it would be great if you could push what you have to github and link here, otherwise it's hard ot guess, especially for such basic usage.

**Comment by Nodeocrat** [comment]
sure will do, i'll isolate the problem into its own project on Friday

**Comment by lgandecki** [comment]
Great, thanks!

**Comment by Nodeocrat** [comment]
ok so I understand what the problem is now... it's because my cypress tests are in a `test` folder so I need to change the `step_definitions` with cosmiconfig, but I am confused with how to use cosmiconfig, is there an example anywhere I can see of where it has been used with `cypress-cucumber-preprocessor`?

**Comment by Nodeocrat** [comment]
Ah it's ok, I managed to guess around and fix it. I thought there was more required after I read the cosmiconfig docs. Maybe some further clarifications would be nice for the README, something along the lines of "install cosmiconfig, and add options to the package.json"? Saying 'please *use* cosmiconfig' makes me think i need to head over to the cosmiconfig docs and learn how to use it first.
Anyway, this issue can be closed.

**Comment by shweta8996** [comment]
![image](https://user-images.githubusercontent.com/49246189/66076146-63ee9000-e51a-11e9-8c10-0b3e5f2b2040.png)
 i have same problem, i am not able to setup it. I am getting this `Error: Step implementation missing for: I open Google page`

**Comment by Samobey** [comment]
@shweta8996 
Try to delete: 
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  } 
from package.json

**Comment by gustavoafonso** [comment]
I am facing the same issue, bur this didn't work to me @Samobey

**Comment by senthkum** [comment]
Hi Mate,

I am also facing the same issue, even after deleting the below code from cypress.json it's not working. Could you please me here I have added the feature file and code?

"cypress-cucumber-preprocessor": {
"nonGlobalStepDefinitions": true
}


![Scenariooutline not working](https://user-images.githubusercontent.com/46837197/77601689-87d9de00-6f5f-11ea-912d-ea46433bd783.jpg)




  Scenario Outline: Buy books worth
    Given I am logged in to demowebshop
    And I click on signin
    When I enter a username <Username> and password <Password>
    Then Verify the logout is enabled

Examples:
|Username	|Password|
|boy@mail.com	|Boy123|
|rekha@mail.com	|Boy123|
|test@mail.com	|Boy123|

Code:
-----
/// <reference types="Cypress" />
import {Given, When, Then, And} from "cypress-cucumber-preprocessor/steps"

Given('I am logged in to demowebshop',()=>{
    cy.visit('http://demowebshop.tricentis.com/');
})


And('I click on signin', () =>{
    cy.get('.ico-login').click()
    cy.wait(3000)
})

When('I enter a username {string} and password {string}',(a, b)=>{

    cy.get('#Email').type(a.Username)
    cy.get('#Password').type(b.Password)        
    cy.get('.button-1.login-button').click()    
})

Then('Verify the logout is enabled', ()=>{
    cy.get('.ico-logout').should('have.text', 'Log out')
})

**Comment by badeball** [comment]
This just isn't how scenario outlines work. Check out the official [reference](https://cucumber.io/docs/gherkin/reference/#scenario-outline) and the [tests](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/v2.0.1/cypress/integration/ScenarioOutline.feature), which ultimately is the source of truth (valid for v2.0.1, which might not be your specific version whenever you're reading this comment).

**Comment by Olubolar614** [comment]
I'm still getting Error: Step implementation missing for: Please find below error logs

Error  Step implementation missing for: I open basic mortgage calculator page  View stack trace Error: Step implementation missing for: I open basic mortgage calculator page
	•	    at Context.resolveAndRunStepDefinition (https://react-redux.realworld.io/__cypress/tests?p=cypress/integration/mortgage.feature-207:24485:11)
	•	    at Context.<anonymous> (https://react-redux.realworld.io/__cypress/tests?p=cypress/integration/mortgage.feature-207:23851:35)
	•	From previous event:
	•	    at Context.thenFn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:132380:26)
	•	    at Context.then (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:132819:21)
	•	    at Context.<anonymous> (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144927:21)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144402:33
	•	From previous event:
	•	    at runCommand (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144381:14)
	•	    at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144524:14)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144552:16
	•	From previous event:
	•	    at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144524:34)
	•	From previous event:
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144565:37
	•	From previous event:
	•	    at run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144558:19)
	•	    at Object.cy.<computed> [as then] (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:144970:11)
	•	    at Context.runnable.fn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:145202:24)
	•	    at callFn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88335:21)
	•	    at Test.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88322:7)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149207:28
	•	From previous event:
	•	    at Object.onRunnableRun (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149195:20)
	•	    at $Cypress.action (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:141473:61)
	•	    at Test.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:148003:13)
	•	    at Runner.../driver/node_modules/mocha/lib/runner.js.Runner.runTest (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88994:10)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:89120:12
	•	    at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88903:14)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88913:7
	•	    at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88815:14)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88876:7
	•	    at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149131:16)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149152:11
	•	From previous event:
	•	    at onNext (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149149:57)
	•	    at done (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88275:5)
	•	    at callFn (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88358:7)
	•	    at Hook.../driver/node_modules/mocha/lib/runnable.js.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88322:7)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149207:28
	•	From previous event:
	•	    at Object.onRunnableRun (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:149195:20)
	•	    at $Cypress.action (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:141473:61)
	•	    at Hook.Runnable.run (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:148003:13)
	•	    at next (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88837:10)
	•	    at https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:88881:5
	•	    at timeslice (https://react-redux.realworld.io/__cypress/runner/cypress_runner.js:82807:27)

**Comment by Olubolar614** [comment]
#### Feature file ####

Feature: Ultimate Mortgage Calculator  Basic Mortgage Calculator successful submit

   Scenario: Check if Ultimate Mortgage Calculator  Basic Mortgage Calculator returns successful messages
      
      Given I open basic mortgage calculator page
      When I enter the values for amount and term
       |amount|term|
       |250000| 27 |
       |300000| 28 |

      And I enter the values for interest rate and mortgage fees
       |rate  | fee  |
       |1.41  | 1198 |
       |1.60  | 2500 |
      Then I submit the form

### Step definitions file code ###

import {Given, When, Then} from "cypress-cucumber-preprocessor/steps"


Given('Given I open basic mortgage calculator page', () => {

    cy.visit('https://www.moneysavingexpert.com/mortgages/mortgage-rate-calculator/')

});

   When('I enter the value for mortgage debt', datatable => {

    datatable.hashes().forEach [element => {
        cy.get('#amount').clear(element.amount) 
        cy.get('#amount').type(element.amount)
        cy.get('#term').clear(element.term) 
        cy.get('#term').type(element.term)
        
    }]

    When('I enter the values for interest rate and mortgage fees', datatable => {

           datatable.hashes().forEach[row => {
            cy.get('#rate').clear(row.rate) 
            cy.get('#rate').type(row.rate)
            cy.get('#fees-value').clear(row.fee) 
            cy.get('#fees-value').type(row.fee)
            
        }];
    
    Then('I submit the form')
        cy.get('.btn--default').click()
    
    
      })

   })

#### Package JSON #####

{
  "name": "cypressger",
  "version": "1.0.0",
  "description": "mortgage cypress test",
  "main": "index.js",
  "scripts": {
    "test": "test"
  },
  "author": "oluseun",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^4.5.0"
  },
   
   "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
  
}

**Comment by marianamon** [comment]
> #### Archivo de características
> Característica: Calculadora de hipotecas definitiva Calculadora de hipotecas básica con éxito
> 
> Escenario: verificar si la calculadora de hipotecas definitiva calculadora de hipotecas básica devuelve mensajes exitosos
> 
> ```
>   Given I open basic mortgage calculator page
>   When I enter the values for amount and term
>    |amount|term|
>    |250000| 27 |
>    |300000| 28 |
> 
>   And I enter the values for interest rate and mortgage fees
>    |rate  | fee  |
>    |1.41  | 1198 |
>    |1.60  | 2500 |
>   Then I submit the form
> ```
> 
> ### Código de archivo de definiciones de paso
> importar {Dado, Cuándo, Entonces} desde "cypress-cucumber-preprocessor / steps"
> 
> Given ('Dado que abro la página básica de la calculadora de hipotecas', () => {
> 
> ```
> cy.visit('https://www.moneysavingexpert.com/mortgages/mortgage-rate-calculator/')
> ```
> 
> });
> 
> Cuando ('Ingreso el valor de la deuda hipotecaria', datatable => {
> 
> ```
> datatable.hashes().forEach [element => {
>     cy.get('#amount').clear(element.amount) 
>     cy.get('#amount').type(element.amount)
>     cy.get('#term').clear(element.term) 
>     cy.get('#term').type(element.term)
>     
> }]
> 
> When('I enter the values for interest rate and mortgage fees', datatable => {
> 
>        datatable.hashes().forEach[element => {
>         cy.get('#rate').clear(element.rate) 
>         cy.get('#rate').type(element.rate)
>         cy.get('#fees-value').clear(element.fee) 
>         cy.get('#fees-value').type(element.fee)
>         
>     }];
> 
> Then('I submit the form')
>     cy.get('.btn--default').click()
> 
> 
>   })
> ```
> 
> })
> 
> #### Paquete JSON
> {
> "nombre": "ciprés",
> "versión": "1.0.0",
> "descripción": "prueba de ciprés hipotecario",
> "principal": "index.js",
> "scripts": {
> "prueba": "prueba "
> },
> " author ":" oluseun ",
> " license ":" ISC ",
> " devDependencies ": {
> " cypress ":" ^ 4.5.0 "
> },
> 
> "cypress-cucumber-preprocessor": {
> "nonGlobalStepDefinitions": true
> }
> 
> }

lo he solucionado de la siguiente manera compañero:
modificando las rutas de la siguiente manera, según el valor que indique en el archivo package.json para "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false
  }
cypress/integration cuando nonGlobalStepDefinitionses sea igual a true
cypress/support/step_definitionscuando nonGlobalStepDefinitionses sea igual a false

**Comment by Vikas481** [comment]
Hello ,
Experimentaion Configuration,create context and Context Model
Under Configuration create context and context modelfailed
TEST BODY
1
Given John access the experimentation home page
2
then{}, function(){}
Error
Step implementation missing for: John access the experimentation home page
[node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js:199:1](http://localhost:57696/__/#)
  197 |       );
  198 |     }
> 199 |     throw new Error(`Step implementation missing for: ${stepText}`);
      | ^
  200 |   },
  201 |   Given: (...args) => {
  202 |     stepDefinitionRegistry.runtime(...args); 
View stack trace
 Print to console


ChromeChrome 113

1920x1080
(43%)
Getting this error 
not able to get rid of it. can somebody help me on this.
feature file :
Feature: Experimentaion Configuration,create context and Context Model

    Scenario: Under Configuration create context and context model
        Given John access the experimentation home page
        When John click on configuration menu
        And Click on context and add a new context
        And Click on context model and add new context model
        Then Link context with context model and save it

Step def 

import { before, Given, When, And, Then } from "cypress-cucumber-preprocessor/steps";
import { navigateTo } from "../page_objects/navigationPage.cy";
import { contextTo } from "../page_objects/contextPage.cy";
import { addContextAndContextModelTo } from "../page_objects/addContextAndContextModel.cy";

Given('John access the experimentation home page', () => {
  cy.visit(URL);
  cy.viewport('macbook-13');
  cy.url().should('contain', 'experimentation-admin-ui');
  cy.title().should('eq', 'Experimentation Admin');
});

When('John click on configuration menu', () => {
  cy.wait(2000);
  navigateTo.contextPage();
  contextTo.verifyHeadingTitle();
});

And('Click on context and add a new context', () => {
  contextTo.addContext();
  addContextAndContextModelTo.createNewContext();
  cy.wait(2000);
});

And('Click on context model and add new context model', () => {
  navigateTo.contextModelPage();
  contextTo.addContextModel();
  cy.wait(2000);
});

Then('Link context with context model and save it', () => {
  addContextAndContextModelTo.createNewContextModel();
  cy.wait(2000);
  addContextAndContextModelTo.clickOnCreatedContextModel();
});

**Comment by Vikas481** [comment]
@lgandecki Łukasz Gandecki can you please help me here
