### ISSUE TITLE
Feature file Background section issue

### ISSUE THREAD

**Issue by mgalindo** [TheBrainFamily/cypress-cucumber-preprocessor#21]
The Background section in the feature files is treated as an Scenario, in other words it is only executed once and should be executed before each scenario.
This is coming from the cucumber.io docs
"_Occasionally you'll find yourself repeating the same Given steps in all of the scenarios in a feature file. Since it is repeated in every scenario it is an indication that those steps are not essential to describe the scenarios, they are incidental details.
You can literally move such Given steps to the background by grouping them under a Background section before the first scenario_"

**Comment by lgandecki** [comment]
yeah, this is not implemented. Feel free to send a PR :-) working with this code is rather fun :)
@mbaranovski or @rshaikh mentioned they might want to give it a try, but as far as I know this is not in the works currently

**Comment by lgandecki** [comment]
Fixed in 0.5.0 by @jmozgawa :-)

If it doesn't work the way you'd expect please create another issue or comment in this one. Thanks!
