### ISSUE TITLE
Problem running ScenarioOutline.feature

### ISSUE THREAD

**Issue by caznew277bw** [TheBrainFamily/cypress-cucumber-preprocessor#22]
Re raising issue here:

When I attempt to run the ScenarioOutline.feature I get errors

<img width="662" alt="screen shot 2018-03-09 at 09 51 04" src="https://user-images.githubusercontent.com/34125342/37201385-7382bd06-237f-11e8-8c52-97a5880eb0df.png">

Could it be missing some dependencies? All the others run ok.

When I run: node -v 
I get: v8.9.0

**Comment by caznew277bw** [comment]
I reinstalled everything and now its all good. Sorry for inconvenience.

**Comment by lgandecki** [comment]
No problem! Thanks for using the plugin, please let us know if you have any more problems :-)
