### ISSUE TITLE
non latin (i.e. arabic) characters cause a confusing error

### ISSUE THREAD

**Issue by lgandecki** [TheBrainFamily/cypress-cucumber-preprocessor#221]
We need to think if there is a different way to encode the string for error. If not, at least 
```
     Error: Failed to execute 'btoa' on 'Window': The string to be encoded contains characters outside of the Latin1 range.
```

This seemed to do the trick:
```
        let data;

        try {
          data = btoa(err.message.toString());
        } catch (e) {
          data = `could not encode the error message ${err.message.toString()}`;
        }
```

And produced:

```
     CypressError: Timed out retrying: expected 'فيسبوك - تسجيل الدخول أو الاشتراك' to include 'Facebook'
```

but I'm not sure what was the point of serialization in the first place

**Comment by jcundill** [comment]
@lgandecki good point - the serialisation is in there as I added a text/plain attachment of the error message string into the cucumber.json as well as adding the error itself and attachments need to be base64 encoded.

It probably makes sense to just remove this attachment block entirely. The message doesn't really add anything.

I was looking at attachments at the time as one of the things on my list is to add support for putting things like cy.screenshot attachments into the generated cucumber reports.

I'll raise a PR to remove it
