### ISSUE TITLE
run particular test

### ISSUE THREAD

**Issue by amitguptagwl** [TheBrainFamily/cypress-cucumber-preprocessor#223]
1. Is there any vscode plugin / mechanism to right click on a scenario and run the test?
2. Is there any way to run particular test from cypress dashboard? Currently it runs all the test from the selected feature file?

**Comment by lgandecki** [comment]
Thank you for the interest in the cypress preprocessor
1 - I'm not aware of any vscode plugins, if there is none, it should be relatively easy to write your own. 
2 - https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#smart-tagging

**Comment by amitguptagwl** [comment]
Thanks for your quick response. Yeah I figured out the way of `focus`.
