### ISSUE TITLE
The documentation got too large - we need a table of contents

### ISSUE THREAD

**Issue by lgandecki** [TheBrainFamily/cypress-cucumber-preprocessor#224]
It would be nice to have a list of topic in the documentation in a clikable form, so people can look through all the other options instead of having to scroll through the whole documentation

I'm leaving this mainly as a TODO for myself :) unless someone with maybe less coding skills but liking this project would like to add his/her first contribution.

**Comment by laistomazz** [comment]
Since I'll be working on documenting [this feature](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/219), I can add the table of contents too.

**Comment by laistomazz** [comment]
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/226

**Comment by lgandecki** [comment]
:)
