### ISSUE TITLE
TypeError: Cannot read property 'indexOf' of undefined

### ISSUE THREAD

**Issue by jimmy882** [TheBrainFamily/cypress-cucumber-preprocessor#225]
When I'm skipping a test using `this.skip()` I get this error:
`TypeError: Cannot read property 'indexOf' of undefined`
The reason why I'm skipping test is that we are visiting some url and maybe 1 % of those visits are hanging. I don't want to have this as a failed test in my report, because I'm testing the app, not the server and skipping a test in case of visit time out looks better in reports.
Example is here: [https://stackoverflow.com/questions/54530318/skipping-a-test-in-cypress-conditionally](https://stackoverflow.com/questions/54530318/skipping-a-test-in-cypress-conditionally)

**Comment by lgandecki** [comment]
Hey @jimmy882  Could you please show us the whole error stack trace?

**Comment by jimmy882** [comment]
Hi @lgandecki 
I Hope this helps
`TypeError: Cannot read property 'indexOf' of undefined
    at CucumberDataCollector.onFail.err [as onFail]`
pointing to this file:
[https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/cukejson/cucumberDataCollector.js](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/cukejson/cucumberDataCollector.js)
(Ln 67, Col 22)
If needed, I can copy paste the rest of the output, but there are just generated files

**Comment by jimmy882** [comment]
After some debugging I found out, that when I skip the test, then `testError` doesn't have any message, therefore I just tried `if (err.message && err.message.indexOf("Step implementation missing for")`  and line 76: `data: btoa(err.message && err.message.toString())` and it seems that it works. Maybe there is something behind, but I don't see any other failures, and test results are nice (I see there skipped tests)

**Comment by lgandecki** [comment]
@jimmy882 what version are you using? the btoa is no longer there, but the check here:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/cukejson/cucumberDataCollector.js#L67

would make sense, even in the most current version, if you want to make a small PR that would be great :) we can release today

**Comment by jimmy882** [comment]
@lgandecki I'm sorry, it was 1.12.0
But for the check I can make a small PR :)
