### ISSUE TITLE
Feature request: Allowing bailing out on first error

### ISSUE THREAD

**Issue by reaktivo** [TheBrainFamily/cypress-cucumber-preprocessor#23]
Pretty self descriptive, but currently when I run a feature test with multiple steps and one of them fails, they don't bail. I wasn't able to find a way to force the tests to bail, is this possible?

**Comment by lgandecki** [comment]
You would like the scenario to fail, not the whole feature, right?
That should be doable.. it will make the code a bit more complex on our side but I think this is a must have

**Comment by lgandecki** [comment]
@reaktivo Please install 0.3.0 and verify if that's what you meant - if yes, please close this issue. Thanks!

**Comment by reaktivo** [comment]
@lgandecki At first I thought it was not working as expected but I had forgotten to do `npm link`, I've double checked and it works fine. Thanks!
