### ISSUE TITLE
Is the cypress-tags script really necessary?

### ISSUE THREAD

**Issue by laiscoolblue** [TheBrainFamily/cypress-cucumber-preprocessor#233]
When implementing the new bundle option in a project, I wanted to also have the option to filter by tags and then be able, for example, to skip a test.

Looking into the preprocessor code, I've noticed the `createTestsFromFeature` already runs the checks from `tagsHelper` to decide if a feature file or which from its scenarios will run by getting the environment variable TAGS.

I was able to make it work with the command: `cypress run --spec **/*.features --env TAGS='not @skipped'`

That being said, am I right to think that using the `cypress-tags` script results in doing the same check twice?

**Comment by lgandecki** [comment]
If you have a feature tagged "@slow" and you only want to run features "not @slow", Cypress would start a session for that feature file and then decide there is nothing there to run. With the extra script the files that would result with an empty run are not even passed to Cypress. 
Do you observe a different behavior?

**Comment by lgandecki** [comment]
Oh, with the bundle option it wouldn't make a difference I guess

**Comment by laiscoolblue** [comment]
I understand, thanks for clarifying ;)

**Comment by lgandecki** [comment]
You are welcome to clarify the documentation if you think there is a better way to explain it.. 😉
Feel free to close the issue unless there is something you are still missing about the cyprees-tags
