### ISSUE TITLE
unable to log in side Then and given

### ISSUE THREAD

**Issue by vospascal** [TheBrainFamily/cypress-cucumber-preprocessor#235]
up to date to the latest version 1.16.0 (2019-08-28)

When doing. 

`Given('some description', () => { 
    cy.log("12321");
     Cypress.log({message: '123213'});
      console.log('sdfsdf'); 
});`
or
`
When('some description', () => {
     cy.log("12321");
     Cypress.log({message: '123213'});
     console.log('sdfsdf');
});
`
nothing gets logged anywhere... any idea's ? or is this a bug?

**Comment by lgandecki** [comment]
Thanks for the report. I don't have a way to verify today but Could you please try 1.12.0? Just change it in the package.json and run npm install 
That will give me something to start thinking about ;)

**Comment by vospascal** [comment]
i will now will report in few min

**Comment by vospascal** [comment]
no succes :-1: not with  1.16.0 or with 1.12.0

**Comment by vospascal** [comment]
seem to be something else non issue thnx mistake on my end
