### ISSUE TITLE
Smart tagging does not work if other tags are specified

### ISSUE THREAD

**Issue by ioana-gln** [TheBrainFamily/cypress-cucumber-preprocessor#238]
cypress-cucumber-preprocessor version: 1.11.2

I have this configuration in the cypress.json file: 
```
  "env": {
        "TAGS": "not @ignore"
    },
```
It seems that smart tagging doesn't work if other tags are specified. 
I have a feature file with scenarios with @focus tag like: 
```
Feature: Delete Image with the Public API
    As a user
    I want to be able to delete an image from the Image library
    So that I can easily remove unwanted content

    @focus
    Scenario: Deleting an image from a folder in the Image library
        Given ...
        When ...
        Then ...
        And ...

    Scenario: Error message when trying to delete a non-existing image
        Given ...
        Then ...
```

Expected behavior: Only the first scenario is run.
Actual behavior: Both scenarios are run. 
This happens no matter how we execute the tests (from cypress application or command line).

**Comment by jcundill** [comment]
By design rather than a bug
See https://github.com/TheBrainFamily/cypress-cucumber-example#smart-tagging
