### ISSUE TITLE
To support tags

### ISSUE THREAD

**Issue by jlin412** [TheBrainFamily/cypress-cucumber-preprocessor#24]
tags is not a supported feature yet.

**Comment by jmozgawa** [comment]
@lgandecki, @jlin412 Hey guys! We need to discuss how do we want to pass tags to the plugin. Unfortunately, the most obvious way of doing it (IMO), by passing arguments in command line `cypres run --tags tag_A tag_B tag_C` is not possible to achieve. AFAIK cypress does not accept any custom arguments. 
So, that leaves us two options:
1. pass tags in an environment variable, or
2. propose a change in cypress that will allow passing arguments to the plugins

What do you think? Maybe you've got better idea? :)

**Comment by BenoitAverty** [comment]
I think 2. should be done anyway. and in the meantime we can find a solution to make it work by another means.

**Comment by lgandecki** [comment]
Knowing the response time from cypress I think it's much safer to just work on 2. environment variables are not too bad for things like that :)

**Comment by michelle-lim** [comment]
@lgandecki How would you run tags using an environment variable?

**Comment by PointmanDev** [comment]
@lgandecki I think this feature would be great. I would expect it to essentially work the inverse of the RP for the @ignore tag. A list of tags would be suppled in an environment variable and the preprocessor would ignore any tests that did not have a matching tag.

```

<code>
@login 
Feature: Login
Background:
 Given I go to the login page
 ...

@user_login
Scenario: Login as a user
...

@admin_login
Scenario: Login as an admin
...

```

@login as a tag only runs tests in feature files that have the @login tag. @user_login only runs the background of the feature and the "Login as a user" scenario
