### ISSUE TITLE
Cannot run test due to fs.readFileSync

### ISSUE THREAD

**Issue by MariusBog** [TheBrainFamily/cypress-cucumber-preprocessor#241]
Hi, 
I just install ypress-cucumber-preprocessor and i have this error : 

Uncaught TypeError: fs.readFileSync is not a function

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.

Check your console for the stack trace or click this message to see where it originated from.

Do you know where I can look to fix it ?

thanx

**Comment by MariusBog** [comment]
Never mind, I duplicate the config in both index.js

**Comment by kaweesi** [comment]
move the functionality causing that into cypress/support/ such as in commands.js
