### ISSUE TITLE
Uncaught TypeError: Cannot read property 'city' of null    Can not find element 

### ISSUE THREAD

**Issue by MariusBog** [TheBrainFamily/cypress-cucumber-preprocessor#243]
It happen some type thant I can't click on some element.
I have this error :
Uncaught TypeError: Cannot read property 'city' of null
I have been redirected to the cypress documentation : 
https://docs.cypress.io/api/events/catalog-of-events.html#Uncaught-Exceptions
But it appears that there is conflict with the plug in.
Any idea how to conturn it ?

by copying that in the index.js (as ask by documentation)
Cypress.on('uncaught:exception', (err, runnable) => {
  // returning false here prevents Cypress from
  // failing the test
  return false
})

The gerhkin in my .feature files is not working anymore

**Comment by lgandecki** [comment]
are you able to make a small reproduction?
Just looking at the issue I don't think we can help much.

**Comment by MariusBog** [comment]
Hello @lgandecki 
Thanks for the message but I just used the wrong folder index.js :)
My bad aha
