### ISSUE TITLE
Tags not working as expected with multi --env option 

### ISSUE THREAD

**Issue by mnesti** [TheBrainFamily/cypress-cucumber-preprocessor#244]
Hi,

## Case 
My project have multi features and my bug occure when I use sub-scenario with multi --env option (with personal variables)

## Example
I have a feature with multi tags as : 

**Feature: check forms**

@formAC
  Scenario: ...
    
@formVE
  Scenario...

@formBK
  Scenario: ...

## Behavior 

- If I used this command  `npx cypress-tags run -e TAGS=@formVE` it's ok, only this sub-scenario is called

- If I used this command  `npx cypress-tags run -e TAGS=@formVE, myEnv=value` it's not ok, all features  are called but without test.

- If I used this command  `npx cypress-tags run -e TAGS=@formVE -e myEnv=value` The feature "check forms" is called but with all sub-scenario

### Behavior Expected with multi --env option 
how is possible to launch one sub-scenario on the cypress-tag with feature containing sub-scenario and personal  environment variables ?

**Comment by jdvegmond** [comment]
I have the same problem. I can use only tags, and then all (required) tests run fine. But if I use something besides 'TAGS' the behavior becomes unexpected. In my case none of the tests is run if I use something like --env "TAGS='@SAT',env=acc"

**Comment by ojizero** [comment]
This is similar to this issue #335, PR#352 should fix it (we have a similar version of this running internally and it works properly).
