### ISSUE TITLE
Variable use with cuncumber cypress

### ISSUE THREAD

**Issue by MariusBog** [TheBrainFamily/cypress-cucumber-preprocessor#246]
Hello, 

I wanted to know if its possible to manage a variable threw then.js , when.js and xxx.features files ?

In my case I enter an element in my xxx.feature with this way :

`When I enter "23 Rue du Marche des Blancs Manteaux" as a street and "75004 Paris 4e Arrondissement" as area for the adresse mission information` 

In the when.js I get back the adresse in that way : 

```javascript
When("I enter {string} as a street and {string} as area for the adresse mission information", (addressemission,arrondissementmission) => {
    cy.xpath('//input[starts-with(@id,"react-select")]').type(addressemission+", "+arrondissementmission,{ force: true });
    cy.get("#react-select-3-option-0").click();
    cy.get(".MuiButton-contained").click();
    cy.wait(1000);
});
```

But now I want to get addressemission and arrondissementmission in a then.js with the info from xxxx.feature

How to i proceed ?

**Comment by lgandecki** [comment]
@jcundill mentioned state https://github.com/cypress-io/cypress-documentation/commit/0036ec9495420909f8de26ce00107370ce3953f9 in this comment: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/201#issuecomment-520312504

Sounds like this might be something that could help you?

**Comment by Shelex** [comment]
In order to not duplicate step parameters you can save this data to alias i  `when` step and then get it in `then` step

**Comment by jcundill** [comment]
Closing as either aliasing or directly accessing the cypress state should get you what you need.
Please re-open if these are not sufficient
