### ISSUE TITLE
Extra help with generating cucumber.json

### ISSUE THREAD

**Issue by ShanWehttam** [TheBrainFamily/cypress-cucumber-preprocessor#247]
Thanks for this great tool... great to be able to use cucumber with Cypress.

Only having one issue and its generating the cucumber.json file for reporting purposes.
I've added the following to the package.json file, but havn't been able to generate the json file:
  "cypress-cucumber-preprocessor": {
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }
  }
The tests are passing, but nothing generated.  Is there anything that i could be missing.  Do you know of an example project i can look at for guidance?  Many Thanks

**Comment by sagorla** [comment]
@ShanWehttam 
what is the version of your cypress-cucumber-preprocessor ?
Please create a small repo and give us the link.

**Comment by ShanWehttam** [comment]
Hi there,
I created a new project with a fresh install.
    "cypress": "^3.4.1",
    "cypress-cucumber-preprocessor": "^1.16.1"
Cucumber.json file is now created successfully on each test run
