### ISSUE TITLE
Error: Step implementation missing for: ...

### ISSUE THREAD

**Issue by csuzw** [TheBrainFamily/cypress-cucumber-preprocessor#267]
Whatever I do I cannot get any step implementations to be found.  I'm using VS Code and the Cucumber (Gherkin) Full Support extension and it is finding the step implementations so the problem isn't with names or anything like that.

I have the following folder structure: cypress > integration > features > myfeature.feature and then the step definitions in cypress > integration > features > myfeature > myfeature.js.  I have also tried putting the step definitions in cypress > integration > common > myfeature.js.  I have also tried adding the everything in the root integration folder  instead of the features subfolder and nothing is working.

My plugins > index.js file is set up as in the readme and I don't have any other plugins to conflict.  

Everything else is left as default.  What am I missing? (using cypress-cucumber-preprocessor: ^1.16.2)

**Comment by lgandecki** [comment]
Hello @csuzw .

Have you tried to use one of the examples we created? Do they work? If they do - maybe try to see what the differences are between them and your setup? You might just copy things from them to your project and go from there. If they do not work - please create an issue.

This package is used by multiple companies, including some of our clients, has 30k installs a week, so it's a given that the basic functionality works. This board is for issues, not for support requests :) sorry... If anything you could try stackoverflow. 

If you feel there is a problem with the package and it SHOULD work the way you are setting it up - please create a reproduction that we could take a look at. 

I will close this in a couple days unless you dad more details / reproduction.

**Comment by csuzw** [comment]
@lgandecki  Sorry, I made this just before I went home, after a frustrating few hours and of course you're right, it's not a good question or the right place.  

As soon as I got into work this morning, I found the problem:  I missed the config bit: `"cypress-cucumber-preprocessor": {"nonGlobalStepDefinitions": true}`.  I did read this however, but I didn't think it was necessary as the table below says this is the default value.  I missed the comment saying that it would be the default in a future version.  Perhaps it would be worth updating to the table to say the default is false until the future version is here.

**Comment by paulgibbs** [comment]
I've just run into this very same thing as well - the readme as it is written is misleading for a total newbie. :)

**Comment by lgandecki** [comment]
Sorry - you guys are definitely right! The README states that you have to put it in if you want to use the non global style, but the defaults in the table was indeed stated incorrectly, so I get where the confusion was coming from now.. Just fixed it. Thanks for letting me know!

**Comment by BhuvanTE** [comment]
Hi,
i am new to Cypress trying to integrate Cucumber with cypress tool hence written small feature file however getting error Step implementation missing for: I open google page
 and find the screenshot and other details in attached doc
[CucumberError.docx](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/files/5873197/CucumberError.docx)

**Comment by badeball** [comment]
Don't post word documents here. Attach screenshots to your post and show us relevant code in code-blocks. Or better, provide us with an example repository that illustrates your error.

**Comment by mrpimpita** [comment]
> Don't post word documents here. Attach screenshots to your post and show us relevant code in code-blocks. Or better, provide us with an example repository that illustrates your error.

![image](https://user-images.githubusercontent.com/23713539/106530402-3f157e80-64ba-11eb-9a0a-5329442c3026.png)
![image](https://user-images.githubusercontent.com/23713539/106530471-61a79780-64ba-11eb-89ed-6182c4d9e7e7.png)
![image](https://user-images.githubusercontent.com/23713539/106530533-83088380-64ba-11eb-93af-aaf0f2e89cc9.png)
![image](https://user-images.githubusercontent.com/23713539/106530552-8bf95500-64ba-11eb-9c0f-a5bbd141c1fd.png)
![Uploading image.png…]()

**Comment by badeball** [comment]
Move `cypress/integration/RegisterUser.js` into `cypress/integration/RegisterUser/RegisterUser.js`.
