### ISSUE TITLE
Please take file/directory locations from `cypress.json`

### ISSUE THREAD

**Issue by leegee** [TheBrainFamily/cypress-cucumber-preprocessor#27]
Please take file/directory locations from `cypress.json` so that we don't have to root our Cypress install in a directory called `cypress`

**Comment by lgandecki** [comment]
Hello @leegee is this basically the same issue mentioned here - https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/16 ? That one I promised to resolve this week, I'm waiting a few more days for the cypress guys to give us some feedback.
If you feel like this issue will be closed by the other one, please close this one, thanks!

**Comment by leegee** [comment]
yes, I think it is. thank you!
