### ISSUE TITLE
title current test (Given, Then, When) 

### ISSUE THREAD

**Issue by vospascal** [TheBrainFamily/cypress-cucumber-preprocessor#278]
How do i get the title of the current Given, Then, When in side a cypress support/command
Cypress.mocha.getRunner().suite.title
Cypress.mocha.getRunner().test.title

doenst seem to work

any tips

**Comment by jcundill** [comment]
window.testState.currentScenario.steps[window.testState.currentStep - 1].text

Does this do what you want?

**Comment by jcundill** [comment]
@vospascal I'm closing this for now. If the workaround doesn't help you out then please reopen

**Comment by Jean-CS** [comment]
I would like to do something similar as in: 
- On a given step definition, I call a custom Cypress command and in there I access the current step text (as defined in the feature file). 

This would ideally include background steps too. So something like:

```
Cypress.Commands.add('step', { prevSubject: false }, () => {
  const {
    testState: { scenarioSteps, currentScenario, currentStep },
  } = window;
  const step = scenarioSteps[currentScenario.name][currentStep];
});
```

I have tried this approach but it only returns the finished state of the test (after all steps have passed), no matter what step it's called.

**Comment by viengiang** [comment]
>edit: actually, it's working now. What changed was that I had commented the cy. command in that implementation. I ran it with the command uncommented and it worked. I guess running your code again expecting different results sometimes works :)

Hi Jean-CS, could you please share with me the way you apply this command in your test? I already tried to put the command "cy.step()"  for each step on my JS file, but it seems doesn't work. Thank you.

![image](https://user-images.githubusercontent.com/61610632/97656144-59922300-1a99-11eb-832d-91b9688d56e7.png)

**Comment by viengiang** [comment]
> `window.testState.currentScenario.steps[window.testState.currentStep - 1].text`
> 
> Does this do what you want?

Hi @jcundill, can you share with me the way to use that? Thank you.
