### ISSUE TITLE
--config-file param not working with this plugin

### ISSUE THREAD

**Issue by fragsalat** [TheBrainFamily/cypress-cucumber-preprocessor#283]
Hey there,

I figured out that the --config-file parameter isn't working anymore with this plugin. The following exception shows that this plugin tries to determine the location of the step definitions and fails because nodejs's path.join method expected a String rather than a Boolean.

My execution command: `./node_modules/.bin/cypress run --config-file "config/cypress/cypress.json"`

```
TypeError [ERR_INVALID_ARG_TYPE] [ERR_INVALID_ARG_TYPE]: The "path" argument must be of type string. Received type boolean
    at validateString (internal/validators.js:105:11)
    at Object.resolve (path.js:978:7)
    at module.exports (/var/www/thunder/web-order/node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.js:11:14)
    at getStepDefinitionsPaths (/var/www/thunder/web-order/node_modules/cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.js:15:38)
    at module.exports (/var/www/thunder/web-order/node_modules/cypress-cucumber-preprocessor/lib/loader.js:25:36)
    at Stream.end (/var/www/thunder/web-order/node_modules/cypress-cucumber-preprocessor/lib/index.js:25:18)
    at _end (./node_modules/through/index.js:65:9)
    at Stream.stream.end (./node_modules/through/index.js:74:5)
    at DestroyableTransform.onend (./node_modules/readable-stream/lib/_stream_readable.js:577:10)
    at Object.onceWrapper (events.js:282:20)
    at DestroyableTransform.emit (events.js:199:15)
    at endReadableNT (./node_modules/readable-stream/lib/_stream_readable.js:1010:12)
    at processTicksAndRejections (internal/process/task_queues.js:81:17)
```

I looked into the file cypressExecutionInstance.js and checked the result of ps-node's lookup function. It returns the the arguments in the wrong order and this leads to wrong value assignment and the --config-file argument is considered as flag (boolean).

```
[ { pid: '3714',
    command: '/home/fragsalat/.cache/Cypress/3.6.1/Cypress/Cypress',
    arguments:
     [ '--run-project',
       '--config-file',
       '--cwd',
       '--no-sandbox',
       '/path/to/app',
       'config/cypress/cypress.json',
       '/path/to/app' ],
    ppid: '3544' } ]
```

This results in the following config
```
{ _:
   [ '/path/to/project',
     'config/cypress/cypress.json',
     '/path/to/project' ],
  'run-project': true,
  'config-file': true,
  cwd: true,
  sandbox: false }
```

I could open the bug also in ps-node I guess but may you find a better alternative to get the process arguments.
Thanks upfront for looking into this and for your work on this plugin :)

**Comment by lgandecki** [comment]
@fragsalat did it work before?
@gpincheiraa could you maybe add some feedback here?

**Comment by fragsalat** [comment]
What do you mean with before? Before adding the plugin you mean? I actually didn't tried it as I was setting it up all together. But I can say that it worked while I had the cypress.json in the root path and didn't used the --config-file parameter

**Comment by lgandecki** [comment]
Ok my bad. :)
I thought that it maybe stopped working after merging this in - https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/pull/279 . I was wondering whether this somehow worked before and we broke it, or whether it was never working. Seems like it's the latter. 

Feel free to try to fix this, I'd be happy to take a PR. I don't have any suggestions right away. Sounds like maybe a different package in place of ps-node could help, or maybe we are using it in a wrong way.

**Comment by fragsalat** [comment]
My bad as well, I digged now deeper and found out it is neither this plugins nor ps-node's fault. It is my operating system or the ps command which changes the order of arguments.

How I executed manually
```
```
How ps is reporting it
```
/home/fragsalat/.cache/Cypress/3.7.0/Cypress/Cypress --run-project --config-file --cwd --no-sandbox /path/to/project config/cypress/cypress.json /path/to/project
```

All parameters were put to the beginning of the argument list. If I add the config file param like this `--config-file="path"` it stays together. I have no clue if this is actually a intended behavior. I'm using Linux Mint 19. Can you reproduce this on you machine?

**Comment by fragsalat** [comment]
Btw: Why don't you take the config while loading the plugin like this
```
const cucumber = require('cypress-cucumber-preprocessor').default;

module.exports = (on, config) => {
  console.log(config);
  on('file:preprocessor', cucumber(config))
};
```

You wouldn't then need to parse the cypress.json at all.

**Comment by lgandecki** [comment]
I don't know why :) I guess I didn't realize I could do that :) do you want to give this a try and if it works send a PR? I think you will be able to remove quite a bit of code this way (that always feels good). You will have to make sure that we can also pass the other options that we are passing currently (I think browserify options?). Also, it will have to work with webpack loader (but maybe it will be the same?)

**Comment by fragsalat** [comment]
I locally tried it out and it works. I'll go ahead and create a backward compatible PR adding the cypressConfig as second parameter to the preprocessor init function. Will come in some minutes

**Comment by gpincheiraa** [comment]
Hi !!!
Sorry for the late.
My first approach was use the config and pass it through cucumber function but it is not compatible with the webpack loader way for use typescript
check this file --> https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/blob/master/cypress/plugins/index.js#L7

**Comment by fragsalat** [comment]
Hey, thanks for your input but I don't get the point. How would a config with webpack and cucumber look like? This file just adds the webpack preprocessor. Is it done by having multiple `on()` calls?

**Comment by gpincheiraa** [comment]
I think that the real solution for this it is remove all the config related to cypressExecutionInstance and deprecate read the config from cypress.json. 
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/lib/stepDefinitionPath.js#L39

make the config compatible with webpack and cucumber function it is harder and the benefit for read cypress.json file from file system it is only for make compatible with older versions of this plugin.
What do you think @lgandecki ??

**Comment by lgandecki** [comment]
yeah I'm definitely in favor of removing the fileServerFolder option, but we still need the configuration file for reading the integrationFolder , don't we?  Not sure I understand what do you propose.
@fragsalat what did you mean with the eslint? :D

**Comment by fragsalat** [comment]
Hey guys, I've created a small PR to do what I mentioned earlier. Could you do me a favor, review it and check or explain me the issue with the webpack preprocessor more detailed?

**Comment by lgandecki** [comment]
I like it! I appreciate you took care to make sure it's backward compatible. I don't think I will have time to properly test it before the weekend (Flying Dubai -> Warsaw Thursday/Friday and swamped with work till the very flight) 

But I can see it didn't break the build, including getting the run through the webpack-typescript example https://circleci.com/gh/TheBrainFamily/cypress-cucumber-preprocessor/293 , so I think we are fine? @gpincheiraa What are you thinking?

**Comment by fragsalat** [comment]
I have no issues when this will be released on monday. Our sprint is ending next wednesday and until then I can work locally with a link to my local cucumber preprocessor :)

Better test it properly to don't break anything^^

**Comment by lgandecki** [comment]
yup! quite a lot of people using this small library, so I want to make sure I can't break the new version even if I try ;)

**Comment by gpincheiraa** [comment]
The problem that I mentioned before with this file --> https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/blob/master/cypress/plugins/index.js#L7

it is that the function exposed by   `@cypress/webpack-preprocessor` does not support pass the 
 `config`
https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/blob/master/cypress/plugins/index.js#L1

So if I use typescript and I have a different folder set for integration folder in my cypress.json file, maybe this could be fail -->https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/8d7d996b2ea5ed09443705012c896eb4738b2aa3/lib/stepDefinitionPath.js#L20

**Comment by fragsalat** [comment]
Ahh now I got it. To be honest it wouldn't work right now as well in this constellation and I rather see the issue on the webpack plugin than on the cucumber one :)
May there is some possibility to set the config for the cucumber plugin from the webpack config

**Comment by fragsalat** [comment]
Confirmed! Thank you :)
