### ISSUE TITLE
Not able to create cucumber.json

### ISSUE THREAD

**Issue by mohitsingla1** [TheBrainFamily/cypress-cucumber-preprocessor#286]
using below

 "dependencies": {
    "cypress": "^3.3.0",
    "cypress-cucumber-preprocessor": "1.14.0"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
      }
    
  },

**Comment by pravynandas** [comment]
It appears the report made optional starting v1.14.0 release. Not sure if something is causing issues there (w.r.t cypress version 3.3.0). Can you try updating plugin version to something 1.16.2. or 1.17.0 and see if that works?

My working configuration is here:
{
	"dependencies": {
		"cypress": "3.7.0",
		"cypress-cucumber-preprocessor": "1.16.2",
	},
	"cypress-cucumber-preprocessor": {
		"nonGlobalStepDefinitions": true,
		"cucumberJson": {
		  "generate": true,
		  "outputFolder": "cypress/cucumber-json",
		  "filePrefix": "",
		  "fileSuffix": ".cucumber"
		}
	}
}

**Comment by jcundill** [comment]
closing as should work as expected with later versions. @mohitsingla1 is this still an issue for you or did @pravynandas comment sort things out
