### ISSUE TITLE
Running tests in parallel

### ISSUE THREAD

**Issue by amitguptagwl** [TheBrainFamily/cypress-cucumber-preprocessor#299]
I'm not sure if it'll work but if I group feature files based on the tags and run the cypress command in background then they should save time to run all the tests

```bash
npx cypress-tags run -e TAGS='@group1' &
group1=$!
npx cypress-tags run -e TAGS='@group2' &
group2=$!
npx cypress-tags run -e TAGS='@group3' &
group3=$!

wait $group1; wait $group2; wait $group4
```

I was wondering if we can have some feature, where we can give some configuration to run tests in parallel. Like number of parallel tasks, or max tests per task. In background, if this plugin can collect all the scenarios, group them as per the given configuration, and run the cypress command in parallel.

Please let me know your view.

**Comment by DanAtSpark** [comment]
Hello, @amitguptagwl, just for your information, [official cypress documentation](https://docs.cypress.io/guides/guides/parallelization.html#Overview) do not recommend running multiple cypress instances on the single machine. You can find configuration options for parallel running there.

**Comment by amitguptagwl** [comment]
@DanAtSpark I'm looking for a free feature. Currently, my team is running only 250 tests and they take approx 2h30m to run all. We already have a good hardware so consumig that should not be an issue.

**Comment by AhmedOsamaBarghash** [comment]
@amitguptagwl I did use Cypress parallel paid feature with cypress-cucumber-preprocessor and can run over 200 in 13 minutes this is the only way.

**Comment by benjaminknauer** [comment]
You also can try https://github.com/agoldis/sorry-cypress
Its basically the same as the paid dashboard. Just less fancy.

**Comment by amitguptagwl** [comment]
Feeling the need of this, I have wrote a framework to achieve this without any external configuration. I hope to publish it soon. So closing this issue.

**Comment by akbarchandani** [comment]
@AhmedOsamaBarghash do you have any repository with the example where you have run cypress-cucumber-preprocessor in parallel with the paid version.

Currently, my test is throwing the below error when I try to run the test in parallel:

You passed the --parallel flag, but we do not parallelize tests across different environments.

This machine is sending different environment parameters than the first machine that started this parallel run.

I am using Azure cloud infrastructure.

**Comment by amitguptagwl** [comment]
@Francllin I've created another framework which works almost in same way. But internally it allows to run tests in parallel. I'll update on that soon.

**Comment by PavelA85** [comment]
Any update on running tests in parallel?

**Comment by badeball** [comment]
Parallelization isn't in the scope of a preprocessor. There are other options, such as

- https://github.com/sorry-cypress/sorry-cypress, for mimicking the paid dashboard service
- https://github.com/tnicola/cypress-parallel, for runnnig tests in parallel on the same machine
- https://github.com/badeball/cypress-parallel, for running tests in parallel on multiple machines (EG. in CI)

**Comment by amitguptagwl** [comment]
@PavelA85 @Francllin You may check want to check [Parallel run with Cytorus](https://github.com/NaturalIntelligence/cytorus/blob/master/docs/8.ParallelRun.md)

**Comment by SnehithaN** [comment]
@amitguptagwl , Can I configure Cytorus with CI/CD Pipeline? And will it work if I just add cy2 dependency to my existing framework using the below commands?
$ npm install cy2
$ export CYPRESS_API_URL="http://localhost:1234/"
$ npx cytorus run -p true

**Comment by amitguptagwl** [comment]
@SnehithaN When I run the tests in parallel on local, it works fine. However, same was not working on jenkins. Not sure why. So I'm not promoting that feature much. You can give it a try and let me know if it works for you.

To get it work, you'll have to pull sorry-cypress docker image as well.

**Comment by SnehithaN** [comment]
@amitguptagwl ,
Do you think it will work on GitHub pipeline rather than Jenkins?
To run docker image iOS this the command $ docker run -d --rm  -p 1234:1234 agoldis/sorry-cypress-director:2.0.0-beta.12 ?

**Comment by amitguptagwl** [comment]
I believe this is right thread to discuss about cytorus. However, I've not tried with github pipeline yet. With free account, I'm not sure if I can test it better. But you can give it a try. Here, is the [test-repository](https://github.com/NaturalIntelligence/cytorus/tree/master/test-repository) if you want to save time to create tests.

**Comment by umaQA1311** [comment]
Hi All,
Looking for parallel execution of cucumber file with tags(smoke and regression).I am using cypress with cucumber for web automation and integrated with Circle ci.

Currently we configured in circle ci with sequential job for smoke and regression tag which are mentioned in feature file.

Requirement: 
for example ;
Need to run Smoke tags of feature file needs to run llel 
Need to run regression tags of feature file needs to run llel 
I tried  cypress cloud with circle ci -Not working with cucumber feature tags..
Any one please help me out
