### ISSUE TITLE
Use cypress-tags as main binary

### ISSUE THREAD

**Issue by matzeeable** [TheBrainFamily/cypress-cucumber-preprocessor#301]
Hi!

I want to use `cypress-tags` as main binary of `cypress` because it nicely wraps the execution. I do the following in `package.json`:

```json
{
    "scripts": {
        "cypress": "cypress-tags"
    }
}
```

With that step above I can always run `yarn cypress` and it should respect `TAGS` environment variable, too. But, if I do `yarn cypress run` I get the following error:

```
const envTags = found.replace(/.*=/, "");
                      ^

TypeError: Cannot read property 'replace' of undefined
    at Object.<anonymous> (/d/Programme/VSCode Workspace/wp-reactjs-starter/node_modules/cypress-cucumber-preprocessor/cypress-tags.js:34:23)
```

The implementation does not allow optional `TAGS`:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/152ccdd8952abbf0bcc33c108d12305f83e9fd99/cypress-tags.js#L32

Would it be possible to make it optional, too, like `GLOB`?

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/152ccdd8952abbf0bcc33c108d12305f83e9fd99/cypress-tags.js#L20-L26

Regards,
Matthew 🙂

**Comment by lgandecki** [comment]
This is an interesting use-case. I never thought that someone would use cypress-tags without actually specyfing any tags. 
Could you explain, just for my curiosity, a little more that part that "it nicely wraps the execution"?
