### ISSUE TITLE
Effect the name of Scenario Outline examples

### ISSUE THREAD

**Issue by alastair-todd** [TheBrainFamily/cypress-cucumber-preprocessor#305]
I am using the [cypress snapshot plugin](https://github.com/cypress-io/snapshot).

Currently when running multiple scenario outlines from the same feature files, the _examples_ share the same name and they then get grouped together in the snapshot file - this makes it fiddly to delete a whole scenario outline snapshot.

e.g. 

```json
  "__version": "3.8.2",
  "Staff Filters - the ability to apply filters to the Staff data grid": {
    " (example #1)": {
      "surnameFilter": "...",
      "knownAsFilter": "..."
    },
    " (example #2)": {
      "surnameFilter": "...",
      "knownAsFilter": "..."
    }
  }
}

```

If we could see e.g. `scenario outline #1 - example #1` this would ensure them not being grouped in the outline above. It should be:

```json
  "__version": "3.8.2",
  "Staff Filters - the ability to apply filters to the Staff data grid": {
    " (scenario outline #1 - example #1)": {
      "surnameFilter": "..."
    },
    " (scenario outline #1 - example #2)": {
      "surnameFilter": "..."
    },
    " (scenario outline #2 - example #1)": {
      "knownAsFilter": "..."
    },
    " (scenario outline #2 - example #2)": {
      "knownAsFilter": "..."
    }
  }
}

```

**Comment by lgandecki** [comment]
Sounds fair, but this is not something the companies we work with or me personally need, so it'd be great if you could try to make a PR for this. :) We need to make sure also that the output in the gui doesn't get unnecessary long
