### ISSUE TITLE
cannot find module common.js

### ISSUE THREAD

**Issue by thiggins826** [TheBrainFamily/cypress-cucumber-preprocessor#312]
versions:
cypress@3.8.2
cypress-cucumber-preprocessor@1.19.2
cypress-cucumber-preprocessor@2.0.1

Issue:
getting the following error when running a feature which implements a step definition in common.js
`Error: Cannot find module 'cypress/integration/common/common.js' from '/Users/{user}/src/test/cypress/cypress/integration/API'`

I have tried on both 1.19.2 and 2.0.1 versions

the test is running fine if I implement the step definition inside the js file associated with the feature file

this is what I have defined in package.json:
`"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "commonPath": "cypress/integration/common",
    "stepDefinitions": "cypress/integration"
  }`

Any help would be much appreciated

**Comment by pravynandas** [comment]
Can you try with below package.json config?

`"cypress-cucumber-preprocessor": {
		"nonGlobalStepDefinitions": true,
}`

I had this issue earlier (on 2.0.1) with "commonPath" configuration.

**Comment by thiggins826** [comment]
That worked thank you I have another problem now with the common.js file and my tests restarting
after first test is run. 
I have 20+ const variables which are using require statements to reference fixtures, these are used in a before each block.
If I remove the require statement the tests runs normally. 
I am not sure if it is related to this plugin, but am trying to reproduce it now

**Comment by thiggins826** [comment]
closing as issue is resolved by above comment
