### ISSUE TITLE
Setting up the StepDefinitions path programatically

### ISSUE THREAD

**Issue by therussiankid92** [TheBrainFamily/cypress-cucumber-preprocessor#315]
Hi there,

I'm working on an library that wraps up together different test automation technologies, and use them with Cucumber. The library will be installed as a dependency into different projects, each one with their own structure of folders for tests (different than the cypress one). Via the information you provide, I have managed to get the feature files recognized, however I have stumbled upon issues while trying to locate the stepDefinitions. 

As I run cypress programmatically via the module API, I'm looking for a way to programmatically set up the stepDefinitions file path. How would you recommend me to approach that?

Cheers,
Andrei

**Comment by lgandecki** [comment]
unless I'm missing something, even though you run it programmatically it should still read the cosmiconfig configuration like described here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#configuration
