### ISSUE TITLE
[on Windows] since 1.9 version, I have this error Error: Cannot find module"

### ISSUE THREAD

**Issue by mnesti** [TheBrainFamily/cypress-cucumber-preprocessor#316]
Bad behavior

Only after the 1.9 upgrade on windows, cypress not found the feature despite a good path.

- Launcher: ./node_modules/.bin/cypress-tags run -e TAGS='@provider'
- At Starting, filter begin good.

 │ Cypress:    3.8.2                                                                              │
  │ Browser:    Electron 78 (headless)                                                             │
  │ Specs:      1 found (ImagePosting\IPAccountCreation.feature)                                   │
  │ Searched:   cypress\integration\ImagePosting\IPAccountCreation.feature    │

 ```
 Running:  ImagePosting\IPAccountCreation.feature                                          (1 of 1)

Oops...we found an error preparing this test file:

  cypress\integration\ImagePosting\IPAccountCreation.feature

The error was:

Error: Cannot find module 'C:DataBureauinextensoqa
esolveStepDefinition' from 'C:\Data\Bureau\qa\cypress\integration\ImagePosting'

This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

- A missing file or dependency
- A syntax error in the file or one of its dependencies
```
The path C:DataBureauinextensoqa seems losed this "\\" caracter 

For Information, this bug is referenced here by @antonio-zenoo  : https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/245#issuecomment-567451843

Could you help me please.

**Comment by antonio-zenoo** [comment]
I guess until this is resolved, you could try this workaround 
https://github.com/TheBrainFamily/cypress-cucumber-example/issues/14#issuecomment-572991957

**Comment by mnesti** [comment]
👍  Thanks

**Comment by lgandecki** [comment]
can you guys try the 2.0.1 version? Everything should work on Windows now

**Comment by robi4513** [comment]
Pulled in the latest and am no longer seeing that error. Tests execute on Windows as expected. Thank you!

**Comment by mnesti** [comment]
It's ok for me too, thanks for this fix.
