### ISSUE TITLE
Combine cypress-cucumber-preprocessor in combination with TypeScript

### ISSUE THREAD

**Issue by StefanNieuwenhuis** [TheBrainFamily/cypress-cucumber-preprocessor#32]
Hi there,

I'm trying to combine an `angular-cli` app with `cypress`, `cypress-cucumber-preprocessor` and `@bahmutov/add-typescript-to-cypress`, but I keep getting the following error:

> Error: Step implementation missing for: I open the home page

When I change the extension of my definition files to *.js it suddenly works! 
Is there a way to make it work for *.ts files as well? And how do I do that?

This is my feature file -- welcome.feature:
```Feature: Welcome Angular
  I want to be welcomed by Angular

  Scenario: Opening the home page and being welcomed
    Given I open the home page
    Then  I see "Welcome to app!" in the header
````
This is my step definition file -- shared.ts:
```/* global given */
given('I open the home page', () => {
  cy.visit('http://localhost:4200');
});
````

This is my plugin config -- index.js:
```const cypressTypeScriptPreprocessor = require('./cy-ts-preprocessor')
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = on => {
  on('file:preprocessor', cypressTypeScriptPreprocessor)
  on('file:preprocessor', cucumber())
}
```

This is my cypress folder structure:
```
- cypress
--   integration
--- cy-ts-preprocessor.js
--- index.js
--  support
--- step_definitions
---- shared.ts
```

ng -v 
```
   _                      _                 ____ _     ___
   / \   _ __   __ _ _   _| | __ _ _ __     / ___| |   |_ _|
  / △ \ | '_ \ / _` | | | | |/ _` | '__|   | |   | |    | |
 / ___ \| | | | (_| | |_| | | (_| | |      | |___| |___ | |
/_/   \_\_| |_|\__, |\__,_|_|\__,_|_|       \____|_____|___|
               |___/
    
Angular CLI: 1.7.3
Node: 9.3.0
OS: darwin x64
Angular: 5.2.9
... animations, common, compiler, compiler-cli, core, forms
... http, language-service, platform-browser
... platform-browser-dynamic, router

@angular/cli: 1.7.3
@angular-devkit/build-optimizer: 0.3.2
@angular-devkit/core: 0.3.2
@angular-devkit/schematics: 0.3.2
@ngtools/json-schema: 1.2.0
@ngtools/webpack: 1.10.2
@schematics/angular: 0.3.2
@schematics/package-update: 0.3.2
typescript: 2.5.3
webpack: 3.11.0
```

dev dependencies:
```
    "@bahmutov/add-typescript-to-cypress": "^2.0.0",   
    "cypress": "^2.1.0",
    "cypress-cucumber-preprocessor": "^0.3.0",
```

running cypress with the following command:
`yarn cypress open`

**Comment by lgandecki** [comment]
Hello. Thanks for making an issue!
Happy to help.
Could you:

a) make a small repro repository where this is broken 
OR
b) clone this repo, change the creation of a pattern in index.js from **/*.js to **/*.ts and see if that works (if yes, we just need to add two globs , one for .js, one for .ts, should be super easy and I'd love to receive a PR :-) ) 
For b - just clone it, do npm install, npm link, and then npm link cypress-cucumber-preprocessor
 from the app that breakes with typescript and this plugin)

Please let me know if you need more help.

**Comment by lgandecki** [comment]
Done in 0.6.0
