### ISSUE TITLE
problem with babel aliases

### ISSUE THREAD

**Issue by theluk** [TheBrainFamily/cypress-cucumber-preprocessor#324]
Hi guys, 

first huge thanks for this awesome library.

I have problems with some code I have, where we use a module resolver plugin with aliases. 

```
plugins = [
[
      'module-resolver',
      {
        alias: {
          frontend: './src/frontend',
        },
      },
    ]
]
```
My plugin file looks something like this

```
module.exports = (on, config) => {
  const options = browserify.defaultOptions;
  options.browserifyOptions.transform[1][1].plugins.push([
    'module-resolver',
    {
      alias: {
        frontend: './src/frontend',
        server: './src/server',
      },
    },
  ]);

  on('file:preprocessor', e => {
    if (/\.js$/.test(e.filePath)) {
      return browserify(options)(e);
    } else {
      return cucumber()(e);
    }
  });
};
```

Now the problem is, that the alias resolving simply is not working and I cannot not find out why. 
It seems like, no files cucumber loads from the configured paths, never goes through the browserify plugin. 

If so, is there any other way I can use aliases? Because I really need them, otherwise I almost cannot use any file from my source repo. There are a lot of utilities in there which are required for me to write proper tests

**Comment by lgandecki** [comment]
I think you will need to do something more like this:
```javascript
  const options = browserify.defaultOptions;

options.browserifyOptions.transform[1][1].plugins.push([
    'module-resolver',
    {
      alias: {
        frontend: './src/frontend',
        server: './src/server',
      },
    },
  ]);

  on("file:preprocessor", cucumber(options));
```

You shouldn't be doing the if/else. the files that show up as a callback to file:preprocessor are the ones you click (so, .feature files). That if/else would only make sense if you wanted to have tests both as .feature and .js files.

**Comment by theluk** [comment]
Thank you, did not know it comes with browserify by default
