### ISSUE TITLE
Run single fearute

### ISSUE THREAD

**Issue by dimaslz** [TheBrainFamily/cypress-cucumber-preprocessor#33]
Hi, first nice work!.

My doubt is I want to run a folder inside `integration` called ProjectName for example, do a command like `cypress run --folder ./cypress/integration/ProjectName` and will be executed all .feature files. Or something like setup a tag like `--tag @ProjectName`

The ida is use the same project to several applications to reuse the code.

Thanks!!

**Comment by lgandecki** [comment]
Hello @dimaslz 
Thanks!

Not sure if this is related to this particular plugin.

have you tried  ./node_modules/.bin/cypress run -s ./cypress/integration/ProjectName/*.feature ? 

I just did and it worked for me, so I'm closing this for now.
If you meant something else please kindly comment again here and I will reopen the issue. :)
