### ISSUE TITLE
Only can pass GLOB or TAGS in --env

### ISSUE THREAD

**Issue by dallevon** [TheBrainFamily/cypress-cucumber-preprocessor#335]
Currently we set our integration folder in `cypress.json` to
`"integrationFolder": "tests/integration"`

So we need to pass a GLOB as
`--env GLOB='tests/integration/**/*.feature'` in order to override `const defaultGlob = "cypress/integration/**/*.feature";`
 
We also have some tagged scenarios.
`--env TAGS='not @skip and not @lighthouse' `

The problem here is that we can't pass `--env GLOB='tests/integration/**/*.feature',TAGS='not @skip and not @lighthouse'`  or  `--env TAGS='not @skip and not @lighthouse',GLOB='tests/integration/**/*.feature'` because only the first one got picked up

`const specArg = process.argv.slice(2).find(arg => arg.indexOf("GLOB=") === 0);`
or 
`const found = process.argv.slice(2).find(arg => arg.indexOf("TAGS=") === 0);`

As temporary solution we end up passing multiple `--env` options like:
`--env GLOB='tests/integration/**/*.feature' --env TAGS='not @skip and not @lighthouse' --env TEST_SERVER=http://localhost:${INJECT_PORT}`
keeping the one consumed by the `cypress run` on the last place

Can this be fixed so we send only one `--env` with comma separated values?

**Comment by ojizero** [comment]
@dvelasquez BTW even your solution could still not run everything you want, if you have a tag that matches a specific scenario in a feature file passing any additional env vars would mean that the whole feature file would run even if it has scenarios not matching the tags given.

**Comment by dallevon** [comment]
Please see https://github.com/ojizero/cypress-cucumber-preprocessor/commit/5c6448dd298a18d391f05a9398cae8896ebbe037#r38125354
