### ISSUE TITLE
How to use tags in Test Runner?

### ISSUE THREAD

**Issue by DanielStoica85** [TheBrainFamily/cypress-cucumber-preprocessor#339]
So i want to be able to do the following:

1. Add different tags in a feature file. Let's assume I have @tag1 and @tag2.
2. Open the Test Runner by running `cypress open`.
3. Run that feature file by only targeting tests that have @tag1.

How would I do that? Is it possible?

Thanks in advance!

**Comment by lgandecki** [comment]
You can use @focus for that.

**Comment by DanielStoica85** [comment]
That's great, but that's not what I wanna do. I wanna be able to alternatively run tests with first or second tag, without constantly adding @focus to each one.

**Comment by lgandecki** [comment]
Are you saying you want to start cypress run and from there onwards only run tests tagged @tag1 , or do you want to be able to switch tags?

in that case adding this to the command should work:

`-e TAGS='@tag1'`

**Comment by DanielStoica85** [comment]
Yes, that's what I wanna do, but with `cypress open`.

**Comment by lgandecki** [comment]
can you try to use `npx cypress open -e TAGS='@tag1'` ?

**Comment by DanielStoica85** [comment]
That worked, @lgandecki . Thanks!

**Comment by ooge0** [comment]
@lgandecki
Hello!
I did not find a related topic and maybe missing something but the current discussion is very close to my problem.
I had a problem with running single tagged test.
In my case when I'm running all scenarios (tests) by Cypress test runner and by 
`npx cypress-tags run -e  --headed`
or
`./node_modules/.bin/cypress-tags run --headed `
All tests passed and I have no errors at all.
When I'm trying to use single tag 
`npx cypress-tags run -e TAGS="@Smoke" --headed`
I had an error that step implementation is missing.
`Error: Step implementation missing for: I fill the form details
    at Context.resolveAndRunStepDefinition (https://XYZ.com/__cypress/tests?p=cypress\integration\examples\BDD\ecommerce.feature:12466:11)
    at Context.eval (https://XYZ.com/__cypress/tests?p=cypress\integration\examples\BDD\ecommerce.feature:11804:35)`
Trace log is below
```
const state = window.testState;
return cy
  .then(() => state.onStartScenario(scenario, indexedSteps))
  .then(() =>
    resolveAndRunBeforeHooks.call(this, scenario.tags, state.feature.name)
  )
  .then(() =>
    indexedSteps.forEach((step) =>
      stepTest.call(this, state, step, rowData)
    )
  )
  .then(() =>
    resolveAndRunAfterHooks.call(this, scenario.tags, state.feature.name)
  )
  .then(() => state.onFinishScenario(scenario));
```
Main reason that this test is possible to run by the test runner or just `cypress run`
