### ISSUE TITLE
Ability to ignore scenarios based on tag

### ISSUE THREAD

**Issue by jprealini** [TheBrainFamily/cypress-cucumber-preprocessor#340]
Hi there

I come from the "protractor + cucumber" world, and I used to have some configurations done in the cucumber preprocessor there where I could tell it to not run any scenario tagged as @ignore or @skip or any tag I wished

I haven't been able to find anything like that so far in cypress-cucumber-preprocessor.. but searching for how it handles the @focus tag I found the code in 'lib\createTestsFromFeature.js'

I started playing around to see if I could modify it in some way in order to have the ability to run EVERYTHING but any scenario tagged as @ignore

I was able to accomplish it, but with the condition of every single scenario must be tagged.... scenarios without a tag are algo ignored.... Probably it's because of my not so great knowledge on JS... I am sharing the modification I made to that file so anyone can look at it and maybe make it work or tell me "forget about it, it's impossible"

(Commented code is where my modifications are)

```
const { CucumberDataCollector } = require("./cukejson/cucumberDataCollector");
const { createTestFromScenarios } = require("./createTestFromScenario");
const { shouldProceedCurrentStep, getEnvTags } = require("./tagsHelper");

const createTestsFromFeature = (filePath, spec) => {
  const testState = new CucumberDataCollector(filePath, spec);
  const featureTags = testState.feature.tags;
  const hasEnvTags = !!getEnvTags();
  const sectionsWithTags = testState.feature.children.filter(
    section => section.tags && section.tags.length
  );

  const sectionsWithTagsExist = sectionsWithTags.length > 0;

  let everythingShouldRun = false;
  let featureShouldRun = false;
  let taggedScenarioShouldRun = false;
  let anyFocused = false;
  // add anyIgnored 
  let anyIgnored = false;
  if (hasEnvTags) {
    featureShouldRun = shouldProceedCurrentStep(featureTags);
    taggedScenarioShouldRun = testState.feature.children.some(
      section =>
        section.tags &&
        section.tags.length &&
        shouldProceedCurrentStep(section.tags.concat(featureTags))
    );
  } else if (!sectionsWithTagsExist) {
    everythingShouldRun = true;
  } else {
    anyFocused = sectionsWithTags.some(section =>
      section.tags.find(t => t.name === "@focus")
    );
	//set value of anyIgnored based on the existence of @ignore tags
	anyIgnored = sectionsWithTags.some(section => 
	  section.tags.find(t => t.name === "@ignore")
	  );
	 
    if (anyFocused) {
      taggedScenarioShouldRun = true;
    } else {
      everythingShouldRun = true;
    }
  }

  // eslint-disable-next-line prefer-arrow-callback
  if (everythingShouldRun || featureShouldRun || taggedScenarioShouldRun) {
    const backgroundSection = testState.feature.children.find(
      section => section.type === "Background"
    );
    const otherSections = testState.feature.children.filter(
      section => section.type !== "Background"
    );
    const scenariosToRun = otherSections.filter(section => {
      let shouldRun;
      if (anyFocused) {
        shouldRun = section.tags.find(t => t.name === "@focus");
      } else if (anyIgnored) {
		  //if there are ignore tags, run everything but scenarios tagged as @ignore
		  //I suppose the problem is here.. this only picks up tagged scenarios... not
		  //sure how to pickup everything, tagged or not, but ignored scenarios
		shouldRun = section.tags.find(t => t.name !== "@ignore");
	  } else	  {
        shouldRun =
          everythingShouldRun ||
          shouldProceedCurrentStep(section.tags.concat(featureTags)); // Concat handles inheritance of tags from feature
      }
      return shouldRun;
    });
    createTestFromScenarios(scenariosToRun, backgroundSection, testState);
  }
};

module.exports = {
  createTestsFromFeature
};
```

**Comment by jprealini** [comment]
Oh my... I just found the way to do, it, and it was much simpler than I thought

I rolled back the changes I made to that file... and just added the "envs" property with the "TAGS" subproperty to the cypress.json config file... and that's it. It made the trick... I only wonder why there is no clear reference to this trick anywhere in the documentation (or maybe I just didn't find it yet)

```
{
    "env": {
        "TAGS": "not @ignore"
    },
    "baseUrl": "http://localhost:3000/",       
    "ignoreTestFiles": "*.js",
    "fixturesFolder": "cypress/fixtures",
    "integrationFolder": "cypress/integration",
    "pluginsFolder": "cypress/plugins",
    "screenshotsFolder": "cypress/screenshots",
    "testFiles": "**/*.feature",
    "video": true,
    "videosFolder": "cypress/videos",
    "supportFile": "cypress/support/index.js",
    "viewportWidth": 1920,
    "viewportHeight": 1080
}
```

**Comment by lgandecki** [comment]
Thanks for the trick. If you feel like we could accept a PR with this trick mentioned in the documentation. (The env: { TAGS} part is all we would need though, the rest is irrelevant.
For me it is kinda obvious that this is how it would work, but I don't see any harm in making this obvious and as an example of tag usage :)

**Comment by jprealini** [comment]
@lgandecki that would be awesome.. I just cloned the repo, created a branch, added that to the readme.md file, but seems like I don't have permission to push the changes... should I send you the addition so you can add it?

**Comment by lgandecki** [comment]
New on GitHub? ;) try to edit the file on GitHub and it will create a fork for you, make the changes there and create a Pull Request.

**Comment by jprealini** [comment]
maybe new on modifying projects that are not mine... :D

**Comment by jprealini** [comment]
@lgandecki just sent a new PR with minor fixes to the last update.. and seems like the link to the new section in the TOC is not working... can you verify? Thanks!
