### ISSUE TITLE
Feature Request : dataTable, could we have 'hashes' in addition to 'raw' ?

### ISSUE THREAD

**Issue by san-ouadghiri** [TheBrainFamily/cypress-cucumber-preprocessor#347]
Hi,

This is a feature request.

**Available at cypress-cucumber-preprocessor**
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/dataTable.js
The steps makes available a 'rawTable' that is an array of array. We can then manipulate it. This is nice to see dataTable handled :) (I thought I would have to code that, so honestly, I'm thankful).

**Feature Request**
Here is some [cucumber classical implementation of dataTable](https://github.com/cucumber/cucumber-js/blob/master/docs/support_files/data_table_interface.md).
Depending on the called methods you call you can end up with differents formats for your yielded table.

I would personnaly be interested in retrieving a 'hashes' (via .hashesTable' ?) instead of a 'raw' via rawTable. In fact, I'd like to use a dataTable to feed the cy.request() 'qs' option that requires a {foo: 'bar'} object. I'm testing an API microservice, and being able to convert a dataTable into cypress requests parameters would be a great plus. Thus the ability to retrieve an object instead of an array would be very nice.

In between, if someone else search for a solution, here is some non-optimized working code. Maybe there's a way to make it simpler ; if so please share :).

```
When(/^I retrieve items such as$/, function (parameters) {

    const parametersArray = parameters.rawTable.slice(1); // Slice remove the header line

    // == This function below should be store somewhere else JSYK ==
    function objectify(array) {
        return array.reduce(function(p, c) {
            p[c[0]] = c[1];
            return p;
        }, {});
    };
    // ==================================================

    const parametersObject = objectify(parametersArray);

    cy.request({
        method: 'GET',
        url: '/path',
        headers: {someHeaders},
        qs: parametersObject             // This works :)
    }).then( (response) => {
        cy.wrap(response).its('status').as('responseStatusCode');
        cy.wrap(response).its('headers').as('responseHeaders');
        cy.wrap(response).its('body').as('responseBody');
        cy.wrap(response).its('duration').as('responseDuration');
    })
});
```

**Comment by badeball** [comment]
The interface you're referring is available, as real DataTable objects (from Cucumber.js) are constructed.

**Comment by san-ouadghiri** [comment]
@badeball Thanks for the reply. Could you give me a short example? When I tried it, it did not seem to work.
If I can make use of that, it would make my day.

**Comment by badeball** [comment]
It's straight forward, as one would expect.

```js
When("something happens", dataTable => {
  console.log(dataTable.hashes());
});
```

**Comment by san-ouadghiri** [comment]
Hi,

Indeed this works. I could swear I had tried it. But it seems that I didn't properly.
Thanks for your help @badeball it is very much appreciated.

I'm closing this ticket. Hopefully this will help someone like me. Hopefully the world won't remind me based on that ticket XD.

Thanks again & have a good day!

**Comment by jasson99** [comment]
@badeball @san-ouadghiri I am not able to use it, could I get some help here? 
![Screenshot from 2021-08-22 18-40-45](https://user-images.githubusercontent.com/40829116/130356063-c8d190f3-50ba-47dc-9d36-b610b67b9bbf.png)

```
Then(/^the following (links|elements) should be visible in the webUI$/, (dataTable) => {
    console.log(dataTable.hashes())
})
```
