### ISSUE TITLE
cypress-tags doesnt work with tags across multiple files using OR operator

### ISSUE THREAD

**Issue by Phenomite** [TheBrainFamily/cypress-cucumber-preprocessor#350]
Apologies, posted here https://github.com/TheBrainFamily/cypress-cucumber-example/issues/18 but should have been here.

Bug Report:

I have 2 files in integration:

    1.feature - has tag: @1
    2.feature - has tag: @2

I run command:

    npx cypress-tags run -e TAGS='@1 or @2'

You would expect that to output: "Found 2 - path xyz" and execute the 2 feature files, however it stops at the first tag "@1" and doesnt do anything with @2.

I think there's an issue in how its handling this scenario, and you haven't made an example with it thus didn't discover the bug.

Please assess when you can!
Regards.

**Comment by lgandecki** [comment]
Would you be able to test with some older version to verify whether this is indeed a regression, or just something that never worked? Also, what version have you used for this test?

**Comment by Phenomite** [comment]
2.0.1, will try 2.1.0 shortly

**Comment by Phenomite** [comment]
At 2.2.0 and still occurring, not a regression as once thought.

**Comment by Phenomite** [comment]
Ah ok so it's an issue with Cypress.env reading from commandline, when there is a space regardless of quote type, it will stop reading at that space.

![image](https://user-images.githubusercontent.com/8285537/77876956-bcb79f00-7297-11ea-92b1-3d1f2d6dfbe2.png)
