### ISSUE TITLE
Sharing functions across features

### ISSUE THREAD

**Issue by luis-m-gonzalez** [TheBrainFamily/cypress-cucumber-preprocessor#354]
First of all, thanks for this awesome plugin.

When I need to share a step definition, I can easily do it by placing it on the 'common' folder. Is there a way to share a function similarly across all my features? 

I want to share this, but nothing I tried works:

```
var assertSelectOptionsByText = (optionsSelector, commaSeparatedExpectedOptions) => {
    var expectedOptionsTextArray = commaSeparatedExpectedOptions.split(',');
    
    cy.get(optionsSelector).should($actualOptions => {
        let actualOptionsTextArray = $actualOptions.toArray().map(actualOption => { return (actualOption.getAttribute("label") || actualOption.text) });
        expect(actualOptionsTextArray).to.deep.equal(expectedOptionsTextArray);
    });
```
If there is a solution, please let me know step by step, because I'm not familiar with JS. Thank you!

**Comment by facuvillarroel** [comment]
You can add custom commands that will start with `cy.` , in the `support/commands.js` folder. By doing that this command will be available across all you step definitions files. 
Alternatively, you can add a new js file under a utils folder for example, add your functions as exports, and then import them in the step definitions files that you need to use them.

**Comment by luis-m-gonzalez** [comment]
I don't know how to do imports, but the custom command was a great suggestion. Thank you!

**Comment by facuvillarroel** [comment]
Then I'd recommend that you go through this website: [https://javascript.info/](https://javascript.info/), it's pretty easy to follow and has a lot of practical examples that help you a lot with getting acquainted with JS.

**Comment by lgandecki** [comment]
I assume this is not an actual cypress issue, so closing. @facuvillarroel thanks for your help :)
