### ISSUE TITLE
Can't run tests due to missing module

### ISSUE THREAD

**Issue by redReno** [TheBrainFamily/cypress-cucumber-preprocessor#357]
I think a recent change in cypress-browserify-preprocessor  (2.2.0) has broken the Cucumber pre-processor for me. Now I can't import it into plugins.js with require, because I get this error when running:
```
Error: Cannot find module './lib/fs'
Require stack:
- /home/axis/git/cucumber_cypress/node_modules/@cypress/browserify-preprocessor/index.js
- /home/axis/git/cucumber_cypress/node_modules/cypress-cucumber-preprocessor/lib/index.js
- /home/axis/git/cucumber_cypress/cypress/plugins/index.js
- /home/axis/.cache/Cypress/4.3.0/Cypress/resources/app/packages/server/lib/plugins/child/run_plugins.js
```

This is perhaps related. When I use npm install or yarn I get this in the output:

`npm WARN notsup SKIPPING OPTIONAL DEPENDENCY: Unsupported platform for fsevents@1.2.12: wanted {"os":"darwin","arch":"any"} (current: {"os":"linux","arch":"x64"})
`

Is it possible for me to use a work-around, or could you use an earlier version of browserify (if the issue is indeed caused by it)?

**Comment by nelsieborja** [comment]
I'm getting the same issue
![Screen Shot 2020-04-04 at 9 55 50 pm](https://user-images.githubusercontent.com/6583614/78457974-3b10a880-76bf-11ea-92eb-12aa07f6e734.png)

**Comment by redReno** [comment]
I haven't tried it out yet, but the latest version of cypress-browserify-preprocessor, 2.2.1, should fix the issue. So try running install again.

**Comment by redReno** [comment]
It's working again thanks to the new  browserify update, so no need for any changes.
