### ISSUE TITLE
Fails due to Uncaught TypeError: Cannot read property 'native' of undefined

### ISSUE THREAD

**Issue by redReno** [TheBrainFamily/cypress-cucumber-preprocessor#362]
I haven't made any changes to my projects except running yarn install, but now I can't run any tests using Cucumber, while normal Cypress tests run fine.

I tested creating the Google example files and get the same error.

An uncaught error was detected outside of a test:
Uncaught TypeError: Cannot read property 'native' of undefined.

Here's the full error log;
` Running:  Google.feature                                                                  (1 of 1)

  1) An uncaught error was detected outside of a test

  0 passing (193ms)
  1 failing

  1)  An uncaught error was detected outside of a test:
     Uncaught TypeError: Cannot read property 'native' of undefined

This error originated from your test code, not from Cypress.

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at Object.<anonymous> (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:59549:35)
      at Object.361../caller.js (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:59835:4)
      at o (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:265)
      at http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:316
      at Object.360../lib/async (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:59533:13)
      at o (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:265)
      at http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:316
      at Object.<anonymous> (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:16149:16)
      at Object.178.bluebird (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:16155:4)
      at o (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:265)
      at http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:316
      at Object.177.../formatter/builder (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:15896:26)
      at o (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:265)
      at http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:316
      at Object.206../cli (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:18507:12)
      at o (http://localhost:35739/__cypress/tests?p=cypress/integration/Google.feature-026:1:265)
`

**Comment by lgandecki** [comment]
Would you be able to create a simple reproduction in a fresh repository? Also, what version of our plugin do you have installed?

**Comment by redReno** [comment]
I made this:
[](https://github.com/redReno/cucumber-cypress-issue)

It installed the latest version 2.3.0. If run as is, the tests fail. I included another lock file, working_yarn.lock from an earlier project. If it's used with yarn --pure-lock I got it to work. It's also 2.3.0 so perhaps the issue is one of the dependencies.

**Comment by lgandecki** [comment]
Thanks a lot! this will be very helpful. I should be able to disect this today:)

**Comment by 0gust1** [comment]
Thanks ! 
Same issue on our project. Everything was working fine several hours ago.

**Comment by lgandecki** [comment]
well, that just became even higher priority.. ;)

**Comment by 0gust1** [comment]
On our project :
cypress-cucumber-preprocessor :
package.json : "^1.19.0" 
package-lock.json : "1.19.2"

**Comment by cellog** [comment]
can confirm this is blocking everything. I am using Cypress 4.2.0, with this webpack config:

```js
module.exports = {
  resolve: {
    extensions: [".ts", ".js"],
  },
  node: { fs: "empty", child_process: "empty", readline: "empty" },
  module: {
    rules: [
      {
        test: /\.ts$/,
        exclude: [/node_modules/],
        use: [
          {
            loader: "ts-loader",
          },
        ],
      },
      {
        test: /\.feature$/,
        use: [
          {
            loader: "cypress-cucumber-preprocessor/loader",
          },
        ],
      },
      {
        test: /\.features$/,
        use: [
          {
            loader: "cypress-cucumber-preprocessor/lib/featuresLoader",
          },
        ],
      },
    ],
  },
};
```

NOTE: I tried removing all Typescript and it still fails instantly on parsing `.feature` files.

plugins.js:

```js
/* eslint-disable @typescript-eslint/no-var-requires */

// ***********************************************************
// This example plugins/index.js can be used to load plugins
//
// You can change the location of this file or turn off loading
// the plugins file with the 'pluginsFile' configuration option.
//
// You can read more here:
// https://on.cypress.io/plugins-guide
// ***********************************************************

// This function is called when a project is opened or re-opened (e.g. due to
// the project's config changing)

const fs = require("fs");
const wp = require("@cypress/webpack-preprocessor");
const coverageTask = require("@cypress/code-coverage/task");

const webpackConfig = require("../webpack.config");
const autoRecord = require("./auto-record/plugin");

module.exports = (on, config) => {
  const options = {
    webpackOptions: webpackConfig,
  };
  on("file:preprocessor", wp(options));
  on("task", coverageTask);
  autoRecord(on, config, fs);
};
```

cypress.json:

```json
{
  "baseUrl": "http://0.0.0.0:8085",
  "reporter": "junit",
  "ignoreTestFiles": [
    "*.hot-update.js",
    "**/integration/**/*"
  ],
  "testFiles": "**/*.{feature,features,ts}",
  "integrationFolder": "cypress/e2e",
  "videosFolder": "cypress/e2e/videos",
  "sceenshotsFolder": "cypress/e2e/screenshots",
  "viewportHeight": 1000,
  "viewportWidth": 1400,
  "reporterOptions": {
    "mochaFile": "results/junit-[hash].xml"
  }
}
```

**Comment by lgandecki** [comment]
Looks like the issue happens since this change in browserify resolve

https://github.com/browserify/resolve/commit/535ec22acf6d5cc4fa3665ab6dbb6755519e6deb#diff-688ede0ee2da1fa3d89f2fc485f39273R8

```javsacript
typeof fs.realpath.native === 'function' ? fs.realpath.native : fs.realpath;
```

fs.realpath is undefined 

I'm digging into how to pingpoint that version to an older versoin for us or if there is something else we can do

**Comment by cellog** [comment]
@lgandecki confirmed this fixes it! I added:

```
    "resolve": "1.15.1",
```

to our package.json `resolutions` field and now it works:

<img width="1395" alt="Screen Shot 2020-04-16 at 10 54 21 AM" src="https://user-images.githubusercontent.com/98250/79471438-a2d4c680-7fd0-11ea-9e37-89280c59feac.png">

**Comment by lgandecki** [comment]
great! We might need to add this to the README.md for now..

**Comment by lgandecki** [comment]
As @cellog mentions above, adding
```
"resolutions":  {
    "resolve": "1.15.1"
}
```

in your package.json should help for now. 

I've also opened a PR for more permanent solution:

https://github.com/browserify/resolve/pull/220

**Comment by cellog** [comment]
@mramsden that is for `npm` users. `yarn` uses `resolutions` natively. Definitely worth mentioning with a link to the docs for both solutions. Thanks so so much for the quick resolution!

**Comment by ljharb** [comment]
Are you mocking out `fs`? `fs.realpath` has been in node since v0.1.31 - if your `fs` implementation lacks it, then it's broken. The solution is to fix your `fs` implementation.

**Comment by lgandecki** [comment]
@ljharb thanks for stopping by. :-)
That portion of the code runs and fails in the browser not in node. We are not mocking it in any way. I thought that changing the sync/async modules of resolve package would be a quick and safe change. 

Anyway - Thanks to your comment I went back to the code to take another look. I noticed it was the import of cucumber that was causing the failure. Even if we import "pure" functionality of cucumber, requiring the main cucumber module that reexports its internals and APIs brings a lot of baggage, including it's cli, which brings bluebird, which brings the resolve package that now fails in the browser. When I changed all the cucumber imports to point to the files we actually need it clicked. And it will be probably be much faster as well. So definitely a win. I'd hope for some kind of a treeshaking as I'm not that comfortable with relying on a specific structure of a 3rd party package, but this will have to do for now. 

I will release a fix shortly.

**Comment by ljharb** [comment]
Either way, I’ll have a patch out to avoid this error for resolve in the next 10 hours.

**Comment by id-dan** [comment]
@lgandecki I get the same error with v2.3.1
Uncaught TypeError: Cannot read property 'native' of undefined

**Comment by lgandecki** [comment]
@id-dan works for me in the repro repo. Please verify your version with 
```
grep version node_modules/cypress-cucumber-preprocessor/package.json
```

remove your yarn/package lock , remove your node_modules, make sure your version is specified as 
`"cypress-cucumber-preprocessor": "2.3.1"`

reinstall everything and give it another try

**Comment by id-dan** [comment]
thank you, @lgandecki 
works after removing and reinstall - node_modules 😎

**Comment by redReno** [comment]
Thank you @lgandecki 
it works nicely after removing lockfile and running yarn.

**Comment by ljharb** [comment]
resolve v1.16.1 is released, which avoids this error.
