### ISSUE TITLE
How to put feature files and step files in separate folders

### ISSUE THREAD

**Issue by wangazz** [TheBrainFamily/cypress-cucumber-preprocessor#371]
Hi all, I am trying to set up my tests so that my files are organised as follows:
```
- testing
    - features
        - app.feature
    - steps
        - common
            - main.ts
        - app
            - main.ts
```
In package.json, I have put
```
"cypress-cucumber-preprocessor": {
        "commonPath": "testing/steps/common",
        "nonGlobalStepDefinitions": true,
        "stepDefinitions": "testing/steps"
    }
```
however my step files are not being picked up. I am still getting `Error: Step implementation missing...`.

If I move the `app` folder under `features` then it will work, so it feels like `stepDefinitions` is not having any effect. Has anyone had any success having feature files and step files in separate folders?

**Comment by lgandecki** [comment]
how about not use nonGlobalStepDefinitions ?

switch to to false or remove that completely

**Comment by lgandecki** [comment]
Please give it a try and reopen if that's not it.

**Comment by wangazz** [comment]
Thanks @lgandecki. Yes, that will work but I was hoping to make use of the other advantages of `nonGlobalStepDefinitions`, e.g. allowing identically-named steps in different feature files to be defined separately. 

Is there any way to make this work using `nonGlobalStepDefinitions` or is it currently not supported?
