### ISSUE TITLE
Cannot use .features file with "nonGlobalStepDefinitions": true 

### ISSUE THREAD

**Issue by Harpwn** [TheBrainFamily/cypress-cucumber-preprocessor#373]
```
 1) An uncaught error was detected outside of a test:
     Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
  could not clear instance from module cache

```
My project setup wasnt working when I decided to try and use feature bundling.
I downloaded the test project and found that it did not have this set, which is strange given that the documentation specifically states its the recommended approach.

In the test project as it was I could run the test just fine.
In my project I could not.
I changed the test project incrementally and found that it stopped working once I had done the following.

1.  Updated the packages (unsure if this has any effect)
2. Change "nonGlobalStepDefinitions": true
3. Created a folder in cypress/integrations for the webpack feature, and moved webpack.ts/myAssertion.ts into it.

From this point onwards all I get is the above error.
If I remove the ts files I can step not implemented as expected.

Seems weird that you are recommending one approach but the test project, nor the files in this repo follow that approach.

**Comment by lgandecki** [comment]
Hello, sorry to hear about your problems.

We have 3 examples, 2 of them use the nonGlobalStepDefinitions set to true:

https://github.com/TheBrainFamily/cypress-cucumber-example/blob/master/package.json
https://github.com/TheBrainFamily/cypress-cucumber-typescript-example/blob/master/package.json
and the third one doesn't:

https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/blob/master/package.json

On CI we run tests that ensure that both approaches work:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/.scripts/runOnExample.bash
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/.scripts/runOnWebpackTypescriptExample.bash

could you maybe experiment with https://github.com/TheBrainFamily/cypress-cucumber-typescript-example/
and see if that one works for you?

**Comment by Harpwn** [comment]
Ye it appears to work just fine when not using the webpack implementation, thanks alot.
