### ISSUE TITLE
Sharing data between step files

### ISSUE THREAD

**Issue by Martinspire** [TheBrainFamily/cypress-cucumber-preprocessor#374]
So say I have a project where I start with a background stating what User to use and the details of this user. Or a backend to specify what data I'm going to load. I'm going to use this in many places, so it becomes a common step.

But in my subsequent steps, I want to reference the user being used in order to fill in data or whatnot and do tests based on this data. How would I share this data between test files?

Is that supposed to stored with and come from cy.config or is there some other way to do it? I'd rather not pollute my step files with copies with slightly different text to make sure I can run this. And it would help separate lots of steps if they require certain information to be used.

What are some best practices in this regard?

**Comment by jprealini** [comment]
Hi... maybe I am misunderstanding what you describe, but just in case... one rule of thumb for automation testing is that each test should be independent... A given test can not depend on data created from another test.
What you can do is use fixtures and hooks to create the test data prior to each test, or prior to each feature that will be used by each test or set of tests...

**Comment by Martinspire** [comment]
I know you want tests to be separate, but with cucumber, we can spread out the lines in the tests to different files to share it between multiple files. So the test about finding a title (that every page has) is going to be shared.

Now I also want to have my users defined and used over different test files.

So in my case I have this user test feature file, that uses lines from both the user typescript file and the common typescript file. I want to use the logic for setting a user (and a data table that is in the feature file about what users to prepare) on multiple files. So when I prepare the test, it can use that data without worrying of duplicating a lot of code over different test files.

I thought one of the advantages of using the cucucmber setup, was that you could use multiple files for your tests in order to spread and share the logic. But it seems there's still a lot of duplication involved, unless I'm missing some way of sharing cucumber lines with data input/output.

So I thought I'd be able to set a datatable with users as a background, use the data from that datatable in my test lines that are in different files. But I don't see a way of storing and retrieving that. Not without making a separate service file to store/retrieve it from. I just thought Cypress had that functionality too

**Comment by badeball** [comment]
> So I thought I'd be able to set a datatable with users as a background, use the data from that datatable in my test lines that are in different files. But I don't see a way of storing and retrieving that.

You can memoize information during your steps with eg. [aliases](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html).

In some of our tests, we have something like this

```cucumber
Scenario:
  Given a have access to one of those things
  And my thing is configured
```

... where the 1st step will select one thing randomly, ensure access is configured and then following steps will know which thing we've been given access to. This allows us to remove redundant information in our descriptions, where we would otherwise do something like

```cucumber
Scenario:
  Given a have access to the "foobar"
  And the "foobar" is configured
```
