### ISSUE TITLE
After upgrade to 4.6.0 both typescript examples take a very long time to load

### ISSUE THREAD

**Issue by ggere** [TheBrainFamily/cypress-cucumber-preprocessor#380]
## Current behavior:
After cloning either typescript example repo ( cypress-cucumber-typescript-example or cypress-cucumber-webpack-typescript-example ) and then upgrading cypress to 4.6.0 and trying to run the tests they take a very long time (4-5 mins on my machine) to load and the browser appears to be hung.  They will eventually work, but there appears to be a serious issue with the loading.

If I pause the debugger while the browser is hung, it appears to be an issue in this function from `cypress_runner.js`:

```
var extractSourceMap = function extractSourceMap(file, fileContents) {
  var sourceMapMatch = fileContents.match(regexCommentStyle1) || fileContents.match(regexCommentStyle2);
  if (!sourceMapMatch) return Promise.resolve(null);
  var url = sourceMapMatch[1];
  var dataUrlMatch = url.match(regexDataUrl);
  if (!dataUrlMatch) return Promise.resolve(null);
  var sourceMapBase64 = dataUrlMatch[1];
  return initialize(file, sourceMapBase64);
};
```

The fileContents is a large file and the double regex match one the second line takes a very long time to return.  Perhaps this is a Cypress issue, and those regex's should be improved for performance?  Although I assume they don't see this issue with just Cypress.

## Desired behavior:
After upgrade to 4.6.0 the tests should still run quickly.

## Test code to reproduce
```
git clone cypress-cucumber-typescript-example or cypress-cucumber-webpack-typescript-example
node_modules\.bin\cypress open # tests run quickly and work fine

npm install --save-dev cypress@4.6.0
node_modules\.bin\cypress open # tests take a very long time to load, browser appears hung, but they eventually work
```

## Versions
Cypress 4.6.0

**Comment by lgandecki** [comment]
That is interesting. Good debugging! If you have some extra time can you try to downgrade the version a bit and see at which point it starts being slow?

**Comment by ggere** [comment]
Just wanted to mention that the file appears to be `C:/code/test/cypress-cucumber-webpack-typescript-example/cypress/integration/All.features`, and attached the file contents:

[All.features.txt](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/files/4669234/All.features.txt)

**Comment by ggere** [comment]
4.5.0 seems okay, and I don't see any releases between 4.5.0 and 4.6.0, so just 4.6.0 is affected. It appears the code is from this commit https://github.com/cypress-io/cypress/commit/a27bd34df306e0295ddc356d5adb00b2274f6414 that was merged 14 days ago.

**Comment by wescopeland** [comment]
I am also seeing this problem in multiple repos that I maintain. After the 4.6.0 bump, CI starts timing out. When forcing yarn to resolve to 4.5.0, everything is back in the green.

**Comment by lgandecki** [comment]
For now I think you'll have to stick with 4.5.0. Sorry! I will look a bit closer but it might require a cooperation with the cypress guys to solve this. 

@ggere thanks again for looking so closely, that will definitely be helpful!

**Comment by badeball** [comment]
I believe this is incorrectly reported to the preprocessor project. If that expression is indeed taking long, then I believe it will do so with or without this preprocessor. It has also been [reported](https://github.com/cypress-io/cypress/issues/7464) to Cypress without any mention of Cucumber.

**Comment by ggere** [comment]
@badeball I think you correct.  I think this can be linked and maybe closed (or whatever is proper).

**Comment by ggere** [comment]
Root cause:  https://github.com/cypress-io/cypress/issues/7464
