### ISSUE TITLE
transpile errors

### ISSUE THREAD

**Issue by Morriz** [TheBrainFamily/cypress-cucumber-preprocessor#390]
Hi, we use the out of the box typescript transpilation offered by latest cypress, and when we use your preprocessor it runs into problems:
```
SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

.../cypress/integration/common/i_see_string_in_the_title.ts:1
import { Then } from 'cypress-cucumber-preprocessor/steps'
^
ParseError: 'import' and 'export' may appear only with 'sourceType: module'
    (No stack trace)
```
I tried the following bootstrapping procedure for this error to appear:
```js
const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require('@cypress/browserify-preprocessor')

const options = {
  typescript: require.resolve('typescript'),
}
const b = browserify(options)
const c = cucumber()

module.exports = on => {
  on('file:preprocessor', file => {
    if (file.filePath.includes('.feature')) {
      return c(file)
    }
    return b(file)
  })
  ...
}
```
I located the culprit I think: [lib/index.js:L26](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/19d2083731a9c64439f4691d7ff0e3c110aed3e5/lib/index.js#L26)

If it encounters any accompanying file with an extension other than `feature|features`, it does NOT hand it over to browserify to have the default preprocessor pipeline handle it. I think it should.

**Comment by Morriz** [comment]
I have installed the following:
```
    "@cypress/browserify-preprocessor": "^3.0.0",
    "@percy/cypress": "^2.3.1",
    "cypress": "^4.8.0",
    "cypress-cucumber-preprocessor": "^2.4.0",
```

**Comment by lgandecki** [comment]
Did you try doing it with the steps described in the documentation https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#without-webpack ?

**Comment by Morriz** [comment]
I have given cypress folder it's own tsconfig, but don't need `tsify` (as following instructions of cypress, by giving it provided typescript).

**Comment by lgandecki** [comment]
I guess if you wanted to use this 
```
options = {
  typescript: require.resolve('typescript'),
}
```

you should experiment with adding it to the default browserify options, similarly to what we show in the docs.

**Comment by Morriz** [comment]
Strange thing is that the preprocessor just parses the file as is, but maybe that is intended. I don't know if the handler acts as a passthrough, but I would think it would not handle the `.ts` file at all.

**Comment by Morriz** [comment]
> I guess if you wanted to use this
> 
> ```
> options = {
>   typescript: require.resolve('typescript'),
> }
> ```
> 
> you should experiment with adding it to the default browserify options, similarly to what we show in the docs.

That is what is done, it gets merged with the default options.

**Comment by lgandecki** [comment]
but you need to follow this pattern:

```
const cucumber = require("cypress-cucumber-preprocessor").default;
const browserify = require("@cypress/browserify-preprocessor");

module.exports = (on) => {
  const options = browserify.defaultOptions;
// do something with the options, like
   options.typescript = require.resolve('typescript')
  on("file:preprocessor", cucumber(options));
};
```

```
on('file:preprocessor', file => {
    if (file.filePath.includes('.feature')) {
      return c(file)
    }
    return b(file)
  })
```

this will most probably never leave the if - the only file that the preprocessor gets when you run a .feature file is that .feature file. and everything else happens behind the scenes. 
You can verify that by adding console.log(file) before the second return.

**Comment by Morriz** [comment]
Exactly, so I really don't get why the cucumber preprocessor would be processing that `.ts` file.

**Comment by lgandecki** [comment]
because loading the .feature file behind the scenes loads the .ts files, and produces a .js file in the end. But cypress doesn't know about it anymore so it doesn't cause the on("file:preprocessor") callback to fire again. 
It's basically what this plugin does.
It reads a .feature file, loads a bunch of js/ts file and produces a js file :) 
That's why you need to pass any browserify options you want to cucumber directly, instead of doing an if/else

**Comment by Morriz** [comment]
I did what you suggested before, but the error remains the same. Plugin used:
```
const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require('@cypress/browserify-preprocessor')

const options = {
  typescript: require.resolve('typescript'),
}
const b = browserify(options)

module.exports = on => {
  const options = browserify.defaultOptions
  options.typescript
  const c = cucumber({
    ...browserify.defaultOptions,
    ...options,
  })
  on('file:preprocessor', file => {
    if (file.filePath.includes('.feature')) {
      return c(file)
    }
    return b(file)
  })
}
```

**Comment by lgandecki** [comment]
options.typescript = require.resolve('typescript')
instead of
options.typescript

**Comment by Morriz** [comment]
check typo changed

**Comment by Morriz** [comment]
I get many more errors when asking giving cucumber the typescript config.

**Comment by lgandecki** [comment]
Yeah I gave this a try locally and I get the same error. It would be nice to make it compatible with the way cypress parses typescript, it's not immediately obvious to me what's going on. We might be able to add that option in to simplify the setup.
but for now is there any reason why you can't just use the tsify? :-)

**Comment by lgandecki** [comment]
Something like this should do:

```javascript

const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require('@cypress/browserify-preprocessor')

module.exports = on => {
  on('file:preprocessor', file => {
    if (file.filePath.includes('.feature')) {
      const options = browserify.defaultOptions;

      options.browserifyOptions.plugin.unshift(['tsify']);

      return cucumber(options)(file)
    }
    return browserify({
      typescript: require.resolve('typescript'),
    })(file)
  })
}
```

**Comment by Morriz** [comment]
I indeed got it working, tnx. But now I get typing errors (cy not found etc), and I thought the type checks would be skipped (according to cypress docs).

**Comment by lgandecki** [comment]
I see some people adding
`/// <reference types="cypress" />` 

at the top of the files with definitions

**Comment by Morriz** [comment]
I did that, and I got that first error out of the way, but now I run into more issues. I am guessing my `cypress/tsconfig.json` is not used (but the root one probably) when I do a run. Any idea how to run pointing to that one?

**Comment by lgandecki** [comment]
oh yeah, that's documented actually in the readme:

  // Or, if you need a custom tsconfig.json for your test files:
  // options.browserifyOptions.plugin.unshift(['tsify', {project: 'path/to/other/tsconfig.json'}]);

**Comment by Morriz** [comment]
of course...doh!

**Comment by Morriz** [comment]
So for the readers, the final content of `cypress/plugin.js`:
```js
const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require('@cypress/browserify-preprocessor')

browserify.defaultOptions.browserifyOptions.plugin.unshift(['tsify', { project: './cypress/tsconfig.json' }])

const browserifyOptions = {
  typescript: require.resolve('typescript'),
}
const cucumberOptions = { ...browserify.defaultOptions }
const b = browserify(browserifyOptions)
const c = cucumber(cucumberOptions)

module.exports = on => {
  on('file:preprocessor', file => {
    if (file.filePath.includes('.feature')) {
      return c(file)
    }
    return b(file)
  })
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--remote-debugging-port=9222')
      return args
    }
  })
}
```

**Comment by inspiraller** [comment]
I had been struggling to get my solution to work with @cypress/webpack-preprocessor or latest cypress-webpack-preprocessor-v5@5.0.0-alpha.1

I tried your solution above to instead use @cypress/browserify-preprocessor. Only the example above just needed a little modification.

I think the reason is browserify.defaultOptions is undefined until exported
This is my working solution. Also returning the config for using instrumentation. Hope it helps anyone else following this chain.
```typescript
const cucumber = require('cypress-cucumber-preprocessor').default
const browserify = require('@cypress/browserify-preprocessor');

module.exports = (on, config) => {

  const browserifyOptions = {
    ...browserify.defaultOptions,
    typescript: require.resolve('typescript')
  };
  const brow = browserify(browserifyOptions)
  const cuc = cucumber(browserifyOptions);

  require('@cypress/code-coverage/task')(on, config);

  on('file:preprocessor', file => {
    if (file.filePath.includes('.feature')) {
      return cuc(file)
    }
    return brow(file)
  })
  on('before:browser:launch', (browser = {}, args) => {
    if (browser.name === 'chrome') {
      args.push('--remote-debugging-port=9222')
      return args;
    }
  })
  return config; // necessary for coverage
}
```
