### ISSUE TITLE
No Documentation for Step Definitions using Data Tables

### ISSUE THREAD

**Issue by jtaylor100** [TheBrainFamily/cypress-cucumber-preprocessor#394]
I am currently trying to work out how to write a step definition using a gherkin data table. However the current README doesn't explain or give any examples of how the data in the table is handled by the step definitions.

How do you define steps using data tables? Is there an example anywhere?

The documentation is missing this information.

**Comment by Kichiguy** [comment]
I am also having this issue. I use data tables often in my tests and this has become a blocker for me.

**Comment by lgandecki** [comment]
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/DataTable.feature
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/dataTable.js

Are those helpful?
I'd welcome a PR with changes to the README if so. :)

**Comment by jtaylor100** [comment]
Thanks @lgandecki, these are helpful, please assign me and I'll make a PR

**Comment by StephenGillCoop** [comment]
> https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/DataTable.feature https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/dataTable.js
> 
> Are those helpful? I'd welcome a PR with changes to the README if so. :)

Just a note that these are no longer available - showing a 404 @lgandecki so the README links are broken. I searched for DataTable.feature but can't find anything other than this PR. Happy to create a PR to update the README if you can point me to the feature and js file again?

**Comment by badeball** [comment]
Those tests are gone and have been replaced with cucumber tests. Here's what I'm guessing the equivalent is: https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/features/data_table.feature

Here are cucumber-js' data table docs, which implementation is identical: https://github.com/cucumber/cucumber-js/blob/main/docs/support_files/data_table_interface.md
