### ISSUE TITLE
There is no way to have feature files in an arbitrary location

### ISSUE THREAD

**Issue by SirMattCam** [TheBrainFamily/cypress-cucumber-preprocessor#395]
### Desired behavior

Allow for a configuration to specify the folder location of step definitions and a totally separate location for feature files. 

### Test code to reproduce

Try to put feature files and step definitions in non-sibling folders.

### Versions

* **Cypress version: ^1.0.0-beta.12**:
* **Preprocessor version: ^2.4.0**:
* **Node version: >= 10.18.1**:

**Comment by venseiiz** [comment]
I don't seem to find a way to store feature files anywhere else but the 'integration' folder, doesn't matter in sibling folders or not. If you, say, rename 'integration' folder into anything else, and then run/open cypress with '--config integrationFolder=newname', no feature files will be detected.

**Comment by brunano21** [comment]
@lgandecki any potential solution for the above?

**Comment by venseiiz** [comment]
I have found the following workaround:

cypress-cucumber-preprocessor.config.js file in the root of the project:
`module.exports = {
  nonGlobalStepDefinitions: true,
  stepDefinitions: process.env.STEP_DEFS_DIR
};`

Then launch cypress like this:
`STEP_DEFS_DIR=[relative/path/to/folder] npx cypress open --config integrationFolder=[relative/path/to/folder]`

**Comment by brunano21** [comment]
That's a viable solution! many thanks for sharing...I'll see how I can adapt that into a nrwl/nx workspace.
