### ISSUE TITLE
Steps definitions are not executed

### ISSUE THREAD

**Issue by BenoitAverty** [TheBrainFamily/cypress-cucumber-preprocessor#41]
I used this project successfully about a onth ago, and today I can't make it work anymore.

Whatever I do, I always get the error `Error: Step implementation missing for: I am on the "/" page`.

Here is my feature : 
tests/e2e/specs/vue-cli-demo.feature
```
Feature: Vue cli demo

I want to see the demo created by 'vue-cli create' to test cypress with cucumber preprocessor

  Scenario: Visualizing the home page
    Given I am on the "/" page
    Then I see the vue logo

  # Scenario: Navigating to the about page
  #   Given I am on the "/" page
  #   When I click on the "about" link in the menu
  #   Then The current page is "/about"
  #   And The page title is "This is an about page"
```

And the steps : 
tests/e2e/support/step_definitions/common.js
```
/* global given, when, then */
console.log('Hello')
given('I am on the "/" page', () => {
  cy.visit('/');
})

then('I see the vue logo', () => {
  cy.get('img[src="../assets/logo.png"]')
})
```

The non-default paths are all correctly configured (I think)

I added a console.log in the `compile` method of the index.js file of the project which prints the result of the function. I get this : 
```
const {resolveAndRunStepDefinition, given, when, then} = require('cypress-cucumber-preprocessor/resolveStepDefinition');
  const { createTestFromScenario } = require('cypress-cucumber-preprocessor/createTestFromScenario');
  const { createTestsFromFeature } = require('cypress-cucumber-preprocessor/createTestsFromFeature');
  { 
    /* global given, when, then */
console.log('Hello')
given('I am on the "/" page', () => {
  cy.visit('/');
})

then('I see the vue logo', () => {
  cy.get('img[src="../assets/logo.png"]')
}) 
    }
  const {Parser, Compiler} = require('gherkin');
  const spec = `Feature: Vue cli demo

I want to see the demo created by 'vue-cli create' to test cypress with cucumber preprocessor

  Scenario: Visualizing the home page
    Given I am on the "/" page
    Then I see the vue logo

  # Scenario: Navigating to the about page
  #   Given I am on the "/" page
  #   When I click on the "about" link in the menu
  #   Then The current page is "/about"
  #   And The page title is "This is an about page"
`
  const gherkinAst = new Parser().parse(spec);
  
  createTestsFromFeature(gherkinAst);

```

This makes me believe that the plugin correctly finds my step definitions, but they are never executed (I don't see the console.log("Hello") at the top)

Can you help me figure out what's wrong ?

**Comment by lgandecki** [comment]
Sorry for the problems!
It would be great to have a simple repro.. 
another thing to try would be to use older version and see if that helps - that would at least give us something to work from :)

**Comment by BenoitAverty** [comment]
Hey,

I will try to make a reproduction. I have tried with version 0.2.0 (which is the version I used last time), and the same problem is present, which tells me there's something wrong in my project but I can't figure out what.

**Comment by BenoitAverty** [comment]
Here's a reproduction : https://github.com/BenoitAverty/vue-cypress-cucumber

```
$ npm run test

  (Tests Starting)


  My First Test
    ✓ Visits the Kitchen Sink (487ms)

  Vue cli demo
    Visualizing the home page
      1) Given  I am on the "/" page
      - Then  I see the vue logo


  1 passing (959ms)
  1 pending
  1 failing

  1) Vue cli demo Visualizing the home page Given  I am on the "/" page:
     Error: Step implementation missing for: I am on the "/" page
      at resolveAndRunStepDefinition (http://localhost:8080/__cypress/tests?p=tests/e2e/specs/vue-cli-demo.feature-102:2365:11)
      at Context.step (http://localhost:8080/__cypress/tests?p=tests/e2e/specs/vue-cli-demo.feature-102:2236:5)
      at Context.sync (http://localhost:8080/__cypress/tests?p=tests/e2e/specs/vue-cli-demo.feature-102:26086:24)




  (Tests Finished)

  - Tests:           3
  - Passes:          1
  - Failures:        1
  - Pending:         1
  - Duration:        0 seconds
  - Screenshots:     1
  - Video Recorded:  true
  - Cypress Version: 2.1.0


  (Screenshots)

  - tests/e2e/screenshots/Vue cli demo -- Visualizing the home page -- Given  I am on the  page.png (1280x720)


  (Video)

  - Started processing:   Compressing to 32 CRF
  - Finished processing:  tests/e2e/videos/99rhy.mp4 (1 second)


  (All Done)


```

**Comment by lgandecki** [comment]
Thanks, it was much easier to debug it this way :)

There were two changes I had to make:

https://github.com/BenoitAverty/vue-cypress-cucumber/pull/1

one is that your step_definitions was in a non-default place, so unfortunately we need to use a custom config for that :-(
Another one was more trivial, looks like if you use "" in the feature file, then the step_definition has to use {string} instead to match.

We could think about better error messaging when we don't find step_definitions. Interesting that you saw them compiled together! I'm not sure what was happening there :)

**Comment by BenoitAverty** [comment]
Thank you ! The problem was the `{string}` tag. I had never seen that, is it specific to this implementation of gherkin ?

What threw me off was that the console.log("Hello") I had put in my step definitions was never shown. Something must have been swallowing the output of the script, so I thought it was never executed, but looks like it was !

The config for the steps definitions locations was present in my original project, I forgot to put it in the reproduction.

You saved my day ;) I'll look up the documentation for the `{string}` tag.

**Comment by lgandecki** [comment]
Happy to help

This is what we are using:

https://docs.cucumber.io/cucumber-expressions/

the thing that I'm not sure about though is whether we should match either :
given('I am on the "/" page')
or
Given('I am on the {string} page')
or only the latter.

**Comment by MrPierre1** [comment]
Once you have the feature file, How did you generate the step definitions file? Did you have to write the step_definitions file by hand with all the regex or was there a command you ran to generate it?

**Comment by lgandecki** [comment]
yes, you write them "by hand" :D There is no need for scray regex though! take a look here:

**Comment by sb5512** [comment]
> Once you have the feature file, How did you generate the step definitions file? Did you have to write the step_definitions file by hand with all the regex or was there a command you ran to generate it?

For my own use I created the following website which might be help. Basically copy your feature file content to the left and get the javascript code to the left.

https://gherkin-to-js.herokuapp.com/

**Comment by lgandecki** [comment]
nice! Thanks for sharing

**Comment by JimTheMan** [comment]
For me step definitions are ONLY found if they are within `cypress/support/step_definitions`... is this intentional?

**Comment by eyup-aydin** [comment]
> Thanks, it was much easier to debug it this way :)
> 
> There were two changes I had to make:
> 
**> https://github.com/BenoitAverty/vue-cypress-cucumber/pull/1**
> 
> one is that your step_definitions was in a non-default place, so unfortunately we need to use a custom config for that :-(
> Another one was more trivial, looks like if you use "" in the feature file, then the step_definition has to use {string} instead to match.
> 
> We could think about better error messaging when we don't find step_definitions. Interesting that you saw them compiled together! I'm not sure what was happening there :)

@lgandecki and @BenoitAverty, I have the same issue with vue-cypress and I cannot see your solution because the link is broken. Could you please help me how can I fix it?
like; What is the custom config you did?
Thanks in advance

**Comment by eyup-aydin** [comment]
Ok then, my solution:
1-
I updated all the path manually 
from `cypress/support` to `tests/e2e/support/` 
from `cypress/integration` to `tests/e2e/specs/`
on those files:

/node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.test.js
/node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.js
/node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.test.js
/node_modules/cypress-cucumber-preprocessor/lib/tagsInheritance.test.js

2- Adding 
`  
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "stepDefinitions": "tests/e2e/specs/Google"
  }
`
to the `package.json`.

<img width="136" alt="Screen Shot 2020-03-06 at 2 24 40 PM" src="https://user-images.githubusercontent.com/41606948/76115489-3a003480-5fb6-11ea-8276-d8b76004e2e7.png">

That is it. It is working now.

**Comment by raghuvarbisht** [comment]
@eyup-aydin

> Ok then, my solution:
> 1-
> I updated all the path manually
> from `cypress/support` to `tests/e2e/support/`
> from `cypress/integration` to `tests/e2e/specs/`
> on those files:
> 
> /node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.test.js
> /node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.js
> /node_modules/cypress-cucumber-preprocessor/lib/stepDefinitionPath.test.js
> /node_modules/cypress-cucumber-preprocessor/lib/tagsInheritance.test.js
> 
> 2- Adding
> 
> > "cypress-cucumber-preprocessor": {
> > "nonGlobalStepDefinitions": true,
> > "stepDefinitions": "tests/e2e/specs"
> > }
> 
> to the `package.json`.
> 
> <img alt="Screen Shot 2020-03-06 at 2 24 40 PM" width="136" src="https://user-images.githubusercontent.com/41606948/76115489-3a003480-5fb6-11ea-8276-d8b76004e2e7.png">
> 
> That is it. It is working now.

Hi Eyup Aydin ,
Is there any other option instead of modifying node_modules files?

Thanks ,
Raghuvar
Since in production we are going to modify node-modules file so is there any other work around.?

**Comment by lgandecki** [comment]
@raghuvarbisht 
did you try to set the stepDefinitions and commonPath options as described here:

https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#configuration-option

**Comment by raghuvarbisht** [comment]
@lgandecki  I am able to resolve the issue now with @vue/cli defined folder structure.
Below is my git repo link with the steps  I follow for integration and resolve the issue.

**https://github.com/raghuvarbisht/vue-cypress-cucumber**

Thanks for your quick response and much appreciated.

**Comment by nurkeevich1992** [comment]
I was able to connect features with steps after spending so much time. please take a look to following small repo, how I made it.
https://github.com/nurkeevich1992/cypress-cucumber
