### ISSUE TITLE
Handling loops with cypress-cucumber

### ISSUE THREAD

**Issue by moattarwork** [TheBrainFamily/cypress-cucumber-preprocessor#410]
The scenario I have is to load the list of companies and run a scenario one by one with the selected scenario. Is there any way to handle this?

**Comment by bkapadia01** [comment]
@moattarwork You could use a data table for this purpose and list out the companies you want to iterate through? 
[Feature File](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/DataTable.feature)
[Step Definition](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/dataTable.js)

**Comment by moattarwork** [comment]
> @moattarwork You could use a data table for this purpose and list out the companies you want to iterate through?
> [Feature File](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/DataTable.feature)
> [Step Definition](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/support/step_definitions/dataTable.js)

Correct but the sample passing the whole data table to Given/When/Then Methods. My requirement is to have a list of companies and Run the Given/When/Then for each one of them.

**Comment by amitguptagwl** [comment]
@moattarwork can you suggest some example?

**Comment by lgandecki** [comment]
@moattarwork isn't this what you need ? https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/cypress/integration/ScenarioOutline.feature
