### ISSUE TITLE
Error: Cannot find module 'cypress/types/jquery'

### ISSUE THREAD

**Issue by palm-audtachai** [TheBrainFamily/cypress-cucumber-preprocessor#411]
(Sorry, if my english is not good.)

I am cypress beginner. I have problem about my test. When I run my test, it show "Error: Cannot find module 'cypress/types/jquery'" from my .js folder. 
this is my error picture. I don't know how to fix it.
![Annotation 2020-07-09 094038](https://user-images.githubusercontent.com/57890260/86991162-92e01380-c1c8-11ea-902d-2d31792525a3.jpg)

my .js file is in EX09_cucumber folder
![image](https://user-images.githubusercontent.com/57890260/86991733-046c9180-c1ca-11ea-94df-edc11b96e1f9.png)

I config everything follow instruction.
- in my package.json
![image](https://user-images.githubusercontent.com/57890260/86991413-392c1900-c1c9-11ea-8130-fcffc4dfa7d4.png)

- cypress/plugins/index.js
![image](https://user-images.githubusercontent.com/57890260/86991460-5e208c00-c1c9-11ea-8007-fc41ec6ae040.png)

**Versions
Cypress version : 4.10.0
Preprocessor version : 2.5.3
Node version : 12.18.0**

**Comment by FredericLetellier** [comment]
I'm a beginner too, but for me the problem comes from your .feature files and the associated .js file. Can you give their content here?

**Comment by palm-audtachai** [comment]
> I'm a beginner too, but for me the problem comes from your .feature files and the associated .js file. Can you give their content here?

I know the reason of this error. Because I have these code in my .js file. When delete these code, my test can run normaly.
![image](https://user-images.githubusercontent.com/57890260/87228622-a65bcc00-c3cc-11ea-974d-7c074af45daf.png)

But I need to use these code. Do you know how to fix it?

**Comment by lgandecki** [comment]
You probably don't need to require the "when" from cypress/types/jquery, remove that line (3) and things should start working. cypress/types/ and in particular cypress/types/jquery contain typescript code, and since you use only javascript, that will not work.
