### ISSUE TITLE
Imports are not supported in the custom command file, as is the case with cypress alone

### ISSUE THREAD

**Issue by FredericLetellier** [TheBrainFamily/cypress-cucumber-preprocessor#414]
# Current behavior

The cypress project is embedded in the front of my project, everything is launched locally.

In **commands.js**, some imports are needed to create my custom commands
`import { AUTH_REQUEST, AuthParams } from '../../src/store/auth/authAction'`
`import { ONBOARDING_DONE, TUNNEL_ASKED } from '../../src/store/persistedInformation/persistAction'`
`...`

Without cypress-cucumber-preprocessor, cypress works well. Custom commands too.

But with cypress-cucumber-preprocessor, cypress reports an error from the start of the test : 

> Error: Cannot find module '../../src/store/auth/authAction' from '/Users/myuser/Projects/myproject/cypress/support'
Oops...we found an error preparing this test file:
cypress/integration/01_login/03_LoginSuccess.js
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:
-A missing file or dependency
-A syntax error in the file or one of its dependencies
Fix the error in your code and re-run your tests.

**package.json**

> "devDependencies": {
    ........
    "@cypress/skip-test": "^2.5.0",
    "cypress": "^4.9.0",
    "cypress-app-watcher-preprocessor": "^1.1.2",
    "cypress-cucumber-preprocessor": "^2.5.1",
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true,
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/cucumber-json",
      "filePrefix": "",
      "fileSuffix": ".cucumber"
    }

### Versions

* **Cypress version**: 4.9.0
* **Preprocessor version**: 2.5.1
* **Node version**:

**Comment by FredericLetellier** [comment]
Imported files are in TypeScript. You had to follow this doc with webpack:
[TypeScript Support](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#typeScript-support)

Well explain here: 
[Cypress ParseError: 'import' and 'export' may appear only with 'sourceType: module'](https://stackoverflow.com/a/56693706)

**Comment by lgandecki** [comment]
Great to see you figured it out so quickly. :-) I hope you will enjoy using our plugin.
