### ISSUE TITLE
help with regular expressions

### ISSUE THREAD

**Issue by stevepkuo** [TheBrainFamily/cypress-cucumber-preprocessor#42]
Using version 0.6.0. I can't figure out how to incorporate regular expressions into the step function.

I'm trying to not only make 'exact' an optional word, but have the step function track whether 'exact' is included or not in the gherkin sentence. This is so my step function's logic can act on whether 'exact' was in the sentence or not.
Goal:
"Then I do a exact search" => step function parameter exactParam will store 'exact'
"Then I do a search" => step function parameter exactParam will store either null, undefined, or ''

But the following cause cypress to say "Step implementation missing for: I do a exact search":
then('I do a (exact)? search'), (exactParam) => {.... //rest of code
then('/I do a (exact)? search/'), (exactParam) => {.... //rest of code
then('^/I do a (exact)? search$/'), (exactParam) => {.... //rest of code
then('^/I do a (exact\s+)?search$/'), (exactParam) => {.... //rest of code

I also tried another simple regex example to look for a single digit in the gherkin sentence:
"Then I do 2"

But Cypress still said "step implementation missing for: I do 2"
then('I do (\d)'), (num) => {.... //rest of code
then('I do (\d+)'), (num) => {.... //rest of code
then('/I do (\d+)/'), (num) => {.... //rest of code

**Comment by stevepkuo** [comment]
If using a direct regexp in the step definition is not currently available or won't be for a while, is it possible to define my own custom cucumber parameter types somewhere such as the following?
new ParameterType(
        'color',           // name
        /red|blue|yellow/, // regexp
        Color,             // type
        s => new Color(s), // transformer
        false,             // useForSnippets
        true               // preferForRegexpMatch
)

**Comment by lgandecki** [comment]
both should be possible :) but I don't think either are supported yet. I will put a few hours into this today and will  let you know what I find.

**Comment by lgandecki** [comment]
I'm so sorry - the previous issue about regular expressions seemed to be resolved, so I assumed they worked, but they never did. I fixed them, will release a new version in a momen!

Thanks so much for reporting this!

**Comment by stevepkuo** [comment]
Great, thanks a lot. This will help writing step definitions a lot more flexible.

**Comment by markbeaman44** [comment]
Hi I need some help with regular expressions.
I basically have these two feature lines

```
Given the user selects the "4th" item from the results lists
Given selects the "4th" item from the results lists
```
my given:
```
Given(/^selects the {string} item from the results lists$/, (itemPosition: string) => {
    home.selectItem(itemPosition.replace(/[^0-9]/g, ''))
  },
);
```
I need the ability for the Given to recognise both those feature lines above (the user - is basically optional)

Is there an issue or am I doing regular expressions incorrectly?

**Comment by lgandecki** [comment]
Remove the ^

**Comment by markbeaman44** [comment]
I removed the ^ - didnt work
I removed the $ as well - didnt work
<img width="348" alt="Screenshot 2021-08-24 at 08 05 29" src="https://user-images.githubusercontent.com/30801986/130572390-79a9ab28-de41-47c7-9508-0f9cc6c2ffe2.png">
my packages:
"cucumber": "^7.0.0-rc.0",
"cypress": "8.0.0",
"cypress-commands": "^1.1.0",
"cypress-cucumber-preprocessor": "^4.2.0",

it seems the / aint working at all no more, as it even failed against

```
And selects the "5th" item from the results lists
```

**Comment by badeball** [comment]
You can't use `{string}` in regular expressions. It only has meaning in strings, which are translated by [cucumber-expressions](https://cucumber.io/docs/cucumber/cucumber-expressions/).

```js
Given(/selects the "([^"]*)" item from the results lists/, (itemPosition: string) => {})
```

**Comment by lgandecki** [comment]
ah, right... :-) I somehow assumed the first Given worked and the second did not.

The ^ has to go as well nonetheless (and Jonas omitted it in his example). ^ in the regex world means that the matching line has to start with whatever follows.

**Comment by markbeaman44** [comment]
Thanks both for your help - it works nicely now :)
