### ISSUE TITLE
Not able to pass Cypress environment variable from feature file after upgrade from v2.3.1 to v2.5.4

### ISSUE THREAD

**Issue by amithkumarg** [TheBrainFamily/cypress-cucumber-preprocessor#421]
### Current behavior

I was passing some Cypress environment variable from feature file to test step definition for test execution. As these are secure data, I don't have liberty to define it inside fixture file or hardcode inside feature file.
I understand I can create exclusive step definition relevant to such data and don't have to pass from feature file, but then I will lose steps reusability.

This was working with v 2.3.1, but since I upgraded to v2.5.4, all the pass data is referred as plain text now instead of interpolated code/script.

### Desired behavior

Able to pass cypress environment variables from feature file to step definition.

### Test code to reproduce

```
#feature file - for example
Scenario: Refer environment variable
Given I log the data "${Cypress.env(`ADMIN_USERNAME`)}"

#step definition js file
defineStep("I log the data {string}", (data) => {
  cy.log(data);
});

#Another example feature file
And I fill the login form with data:
            | label                     | value                                                           | type     |
            | User Name          | ${Cypress.env(`ADMIN_USERNAME`)}   | text     |
            | Password            | ${Cypress.env(`ADMIN_PASSWORD`)}   | password |

#step definition js file
 switch (element.type) {
      case "text":
          FORM.INPUT_TEXT_BY_LABEL(element.label).type(element.value);
        break;
      case "password":
        FORM.INPUT_PASSWORD_BY_LABEL(element.label).type(element.value, {
          log: false,
        });
```

### Versions

* **Cypress version**: 4.7.0
* **Preprocessor version**: 2.5.4
* **Node version**: v12.16.1

**Comment by damsorian** [comment]
do you found any solution?

**Comment by amithkumarg** [comment]
> do you found any solution?

Nopes, the app was put on maintenance, so I just rolled back to the original working version.

**Comment by badeball** [comment]
This was incidental and not intended behavior stemming from a mistake, which led to other issues. As an alternative you can create a separate step which uses values as environment keys instead, as shown below.

```gherkin
When I fill the login form with data from environment variables
  | label     | environment key |
  | User Name | ADMIN_USERNAME  |
  | Password  | ADMIN_PASSWORD  |
```

Using ES6 string interpolation isn't a feature in Cucumber itself and this is a preprocessor which seeks to mimic its behavior.

**Comment by damsorian** [comment]
@badeball can you explain how I can fill `ADMIN_USERNAME` with `Cypress.env('ADMIN_USERNAME')`  for example? 

Thanks!

**Comment by badeball** [comment]
Maybe something like this?

```js
When("I fill the login form with data from environment variables", (dataTable) => {
  for (const { label, "environment key": environmentKey } of dataTable.hashes()) {
    cy.get(`input[label="${label}"]`).type(Cypress.env(environmentKey));
  }
});
```

**Comment by damsorian** [comment]
@badeball thanks! now I understand how to handle that
