### ISSUE TITLE
[Discussion] Should scenarios be a single test ?

### ISSUE THREAD

**Issue by BenoitAverty** [TheBrainFamily/cypress-cucumber-preprocessor#43]
Hello,

Currently, each step in a scenario becomes a single test in cypress. This is expected and this is the way other cucumber frameworks do it.

However, this goes against cypress recommendations and best bractices because they consider that each test should be independant and able to run alone. This is kind of incompatible with cucumber behavior.

It is not only a "best practice" issue because cypress clears a lot of things between tests : cookies, local storage, session storage, spies, stubs...
This means, for example, I can't set-up a mock in a `given` step and rely on it in a subsequent `when` or `then`.

Possible solutions : 
 - Make each scenario produce a single test (and Background would become beforeEach, but this would hurt reporting)
 - somehow preserve state for a scenario (currently, cypress only allows to do it for cookies)

See : 
 - https://github.com/cypress-io/cypress/issues/686 (second solution would become possible if they implement this but it doesn't look like it's going to be soon).
 - https://github.com/cypress-io/cypress/issues/461 (allows to keep local storage, but it's hacky and doesn't solve other things being cleared)

What do you think ?

**Comment by lgandecki** [comment]
Fixed in 1.0.0 :) Again - Thanks so much!

**Comment by manishbhatia7** [comment]
> Hello,
> 
> Currently, each step in a scenario becomes a single test in cypress. This is expected and this is the way other cucumber frameworks do it.
> 
> However, this goes against cypress recommendations and best bractices because they consider that each test should be independant and able to run alone. This is kind of incompatible with cucumber behavior.
> 
> It is not only a "best practice" issue because cypress clears a lot of things between tests : cookies, local storage, session storage, spies, stubs...
> This means, for example, I can't set-up a mock in a `given` step and rely on it in a subsequent `when` or `then`.
> 
> Possible solutions :
> 
> * Make each scenario produce a single test (and Background would become beforeEach, but this would hurt reporting)
> * somehow preserve state for a scenario (currently, cypress only allows to do it for cookies)
> 
> See :
> 
> * [cypress-io/cypress#686](https://github.com/cypress-io/cypress/issues/686) (second solution would become possible if they implement this but it doesn't look like it's going to be soon).
> * [cypress-io/cypress#461](https://github.com/cypress-io/cypress/issues/461) (allows to keep local storage, but it's hacky and doesn't solve other things being cleared)
> 
> What do you think ?

Is this issue solved,
Can we write multiple files with same session for cucumber with cypress

**Comment by dozzzzer** [comment]
How do you preserve cookies through steps? I need to stay logged in within the entire scope of the scenario. I tried `    Cypress.Cookies.preserveOnce('_session')` inside the step definition where log in is performed but it doesn't seem to work. Any help with that is much appreciated :)
