### ISSUE TITLE
calling another feature file in a feature file

### ISSUE THREAD

**Issue by bezba** [TheBrainFamily/cypress-cucumber-preprocessor#438]
I have a general question about using cypress cucumber. is it possible to call feature1 in feature 2.
so feature 2 is dependent of feature one and  feature one has to be finished before starting feature2. if I want to just run feature2 , is there anyway I can add on top to first run feature1 and once is done, run feature2 ?

**Comment by bezba** [comment]
@lgandecki have you had any experience doing this?

**Comment by Jsijbel** [comment]
I don't think this is possible.

You generally don't want dependencies between scenario's. Let alone features.

**Comment by badeball** [comment]
Not currently possible, nor can it be. By the time a test is execution, it has already been decided which tests are going to be executed. More importantly, what you're describing is a gigantic [anti-pattern](https://docs.cypress.io/guides/references/best-practices.html#Having-tests-rely-on-the-state-of-previous-tests) in testing
