### ISSUE TITLE
Getting SyntaxError: 'import' and 'export' may appear only with 'sourceType: module'

### ISSUE THREAD

**Issue by smrtyviks87** [TheBrainFamily/cypress-cucumber-preprocessor#445]
### Current behavior
Getting error while running spec files or feature files in Cypress open mode

'import' and 'export' may appear only with 'sourceType: module' (17:0) while parsing C:\Users\username\Documents\TestRepo\cypress\support\index.js while parsing file: C:\Users\username\Documents\TestRepo\cypress\support\index.js

### Test code to reproduce
**Index.js File**:

// Import commands.js using ES2015 syntax:
import './commands'

require('cypress-xpath')
require('cypress-plugin-retries')

### Versions

* **Cypress version**: 4.10.0
* **Preprocessor version**: 2.5.0
* **Node version**:12.18.3
![Cypress_issue](https://user-images.githubusercontent.com/61964856/93308634-cf507100-f802-11ea-95ce-593d051255b2.JPG)

**Comment by lgandecki** [comment]
This seems like a cypress error, maybe try at https://github.com/cypress-io/cypress
