### ISSUE TITLE
Question: Is it possible to use this along side exisitng specs not written in gherkin?

### ISSUE THREAD

**Issue by joegaudet** [TheBrainFamily/cypress-cucumber-preprocessor#447]
Hello,

Just doing some investigation into this addon, and am curious if it can be used alongside existing cypress tests that are done in BDD style.

We have a few existing tests that we aren't keen to migrate just yet, but would like to experiment with using cucumber style.

Thanks!

.joe

**Comment by badeball** [comment]
Hey, @joegaudet 

Yes, this is possibly. The preprocessor will only attempt to process files matching `*.feature` and `*.features`, while others are passed through as is.

**Comment by joegaudet** [comment]
Do I need to make the test files regex include .js files as well? When I added a single features file and configured the cypress.json it seems to have lost all my other specs.

**Comment by badeball** [comment]
Yup, here's an example of such file:

```js
{
  `"testFiles": "{**/*.feature,*.test.js}",`
}
```

**Comment by joegaudet** [comment]
Great Jonas!

Thanks so much for your help!
