### ISSUE TITLE
Running tests in Nx workspace results in displaying "Your tests are loading..." message before erroring out

### ISSUE THREAD

**Issue by kpmck** [TheBrainFamily/cypress-cucumber-preprocessor#453]
Hi there - 

**Current Behavior**
I am using Cypress and Cypress-Cucumber-Preprocessor for an Angular app in an Nx workspace. Everything runs perfectly well when I execute the following command to run the Cucumber tests in the Cypress runner:

`ng e2e nx-test-e2e --watch`

However, when I attempt to run all the tests using `ng e2e nx-test-e2e`, the Cypress runner will show the message "Your tests are loading..." for roughly one to two minutes before it errors out.

I have run the same commands prior to installing and using cypress-cucumber-preprocessor, and they worked without issue. It appears to be an issue with the change in `plugins\index.js` file, but it is not clear what is the problematic code in there specifically.

**Desired Behavior**
Running `ng e2e nx-test-e2e` or `ng e2e nx-test-e2e --headless` should execute all the tests without issue. There should be no behavior that differs when running from the Cypress runner with the `--watch` switch and without.

**Test Code to Reproduce**
https://github.com/kpmck/nx-workspace-cypress-cucumber

1. Open workspace in Visual Studio Code
2. Open terminal and run `ng e2e nx-test-e2e --watch`
3. When Cypress runner opens, click **Run all specs** => Spec runs successfully
4. Terminate terminal, open new terminal and run `ng e2e nx-test-e2e`
5. Cypress runner opens and "Your tests are loading..." will show for 1 to 2 minutes until it errors out.
 
**Versions**
* **Cypress version**: 4.1.0
* **Preprocessor version**: 3.0.0
* **Node version**: 12.17.0

**Error Report**

> 0 info it worked if it ends with ok
1 verbose cli [
1 verbose cli   'C:\\Program Files\\nodejs\\node.exe',
1 verbose cli   'C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js',
1 verbose cli   'run',
1 verbose cli   'e2e'
1 verbose cli ]
2 info using npm@6.14.4
3 info using node@v12.17.0
4 verbose run-script [ 'pree2e', 'e2e', 'poste2e' ]
5 info lifecycle nx-test@0.0.0~pree2e: nx-test@0.0.0
6 info lifecycle nx-test@0.0.0~e2e: nx-test@0.0.0
7 verbose lifecycle nx-test@0.0.0~e2e: unsafe-perm in lifecycle true
8 verbose lifecycle nx-test@0.0.0~e2e: PATH: C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin;C:\sandbox\nx-test\node_modules\.bin;C:\Ruby193\bin;C:\Python38\Scripts\;C:\Python38\;C:\Windows\system32;C:\Windows;C:\Windows\System32\Wbem;C:\Windows\System32\WindowsPowerShell\v1.0\;C:\Windows\System32\OpenSSH\;C:\Program Files\PuTTY\;C:\Program Files\Microsoft VS Code\bin;C:\Program Files\Git\cmd;C:\Program Files\Microsoft SQL Server\130\Tools\Binn\;C:\Program Files\dotnet\;C:\Users\ThisUser\AppData\Roaming\npm;C:\Program Files\nodejs\;C:\ProgramData\chocolatey\bin;C:\Program Files (x86)\Microsoft SQL Server\150\DTS\Binn\;C:\Program Files\TortoiseGit\bin;C:\Program Files (x86)\GitExtensions\;C:\Users\ThisUser\AppData\Roaming\npm\node_modules\@angular\cli\bin;C:\drivers;C:\Ruby193\bin;C:\Users\ThisUser\AppData\Local\Microsoft\WindowsApps;C:\Users\ThisUser\AppData\Local\Programs\Azure Data Studio\bin;C:\Users\ThisUser\.dotnet\tools;C:\Program Files (x86)\IDM Computer Solutions\UltraEdit\;C:\drivers;
9 verbose lifecycle nx-test@0.0.0~e2e: CWD: C:\sandbox\nx-test
10 silly lifecycle nx-test@0.0.0~e2e: Args: [ '/d /s /c', 'ng e2e' ]
11 silly lifecycle nx-test@0.0.0~e2e: Returned: code: 1  signal: null
12 info lifecycle nx-test@0.0.0~e2e: Failed to exec e2e script
13 verbose stack Error: nx-test@0.0.0 e2e: `ng e2e`
13 verbose stack Exit status 1
13 verbose stack     at EventEmitter.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\index.js:332:16)
13 verbose stack     at EventEmitter.emit (events.js:315:20)
13 verbose stack     at ChildProcess.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\lib\spawn.js:55:14)
13 verbose stack     at ChildProcess.emit (events.js:315:20)
13 verbose stack     at maybeClose (internal/child_process.js:1021:16)
13 verbose stack     at Process.ChildProcess._handle.onexit (internal/child_process.js:286:5)
14 verbose pkgid nx-test@0.0.0
15 verbose cwd C:\sandbox\nx-test
16 verbose Windows_NT 10.0.18363
17 verbose argv "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\bin\\npm-cli.js" "run" "e2e"
18 verbose node v12.17.0
19 verbose npm  v6.14.4
20 error code ELIFECYCLE
21 error errno 1
22 error nx-test@0.0.0 e2e: `ng e2e`
22 error Exit status 1
23 error Failed at the nx-test@0.0.0 e2e script.
23 error This is probably not a problem with npm. There is likely additional logging output above.
24 verbose exit [ 1, true ]

**Comment by kpmck** [comment]
My team and I were able to resolve our issue by explicitly including the ts-loader in the plugins/index.js file as shown below:

```
const { getWebpackConfig } = require('@nrwl/cypress/plugins/preprocessor');
const wp = require('@cypress/webpack-preprocessor');

module.exports = function (on, config) {
  const wpConfig = getWebpackConfig(config);
  wpConfig.node = { fs: 'empty', child_process: 'empty', readline: 'empty' };
  wpConfig.module.rules.push({
    test: /\.ts$/,
    exclude: [/node_modules/],
    use: [
      {
        loader: "ts-loader"
      }
    ]
  });
  wpConfig.module.rules.push({
    test: /\.feature$/,
    use: [
      {
        loader: 'cypress-cucumber-preprocessor/loader'
      }
    ]
  });

  on('file:preprocessor', wp({ webpackOptions: wpConfig }));
};
```

**Comment by lgandecki** [comment]
Great! Thanks for coming back and sharing the solution 🙂
