### ISSUE TITLE
TAGS keyword should be first one to appear after --env keyword

### ISSUE THREAD

**Issue by far11ven** [TheBrainFamily/cypress-cucumber-preprocessor#455]
Issue:
### TAGS keyword should be first one to appear after --env keyword, otherwise, it doesn't work

Expected:

### TAGS keyword should work irrespective of its placement

for ex:

**npx cypress run --env TAGS="@UI" configFile=dev** works as expected, only runs feature files with tag @UI,
whereas,

**npx cypress run --env configFile=dev TAGS="@UI"** discards the TAGS flag and all feature files are run.

### Versions

* **Cypress - 5.3.0**:
* **cypress-cucumber-preprocessor - 3.0.0**:
* **Node version - v12.18.3**:

**Comment by badeball** [comment]
Multiple variables should be separated with comma, as per [documentation](https://docs.cypress.io/guides/guides/environment-variables.html#Option-4-env).

```
$ cypress run --help

...

    -e, --env <env>                            sets environment variables. separate multiple values with a comma. overrides any value in cypress.json or cypress.env.json
```
