### ISSUE TITLE
Gets crash report when integrated cucumber in cypress

### ISSUE THREAD

**Issue by githubakarsh** [TheBrainFamily/cypress-cucumber-preprocessor#456]
**Error running plugin**

The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file 

CompositeParserException: Parser errors:

expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Background:'
(2:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'Given I am an existing customer'
(3:5): expected: #EOF, #Language, #TagLine, #FeatureLine, #Comment, #Empty, got 'And I visit rookie app'
    at Function.Errors.CompositeParserException.create
**Stack trace**
The following error was thrown by a plugin. We stopped running your tests because a plugin crashed. Please check your plugins file

### Current behavior

Not able to integrate this cucumber package with my app to integration tests
### Versions

* **Cypress version**: 5.3.0
* **Preprocessor version**: 3.0.0
* **Node version**:12.18.0

**Comment by badeball** [comment]
You probably have a syntax error, as the error suggests, but there's not enough information here to reproduce your issue or point to the error. Closing until you can provide that.

**Comment by githubakarsh** [comment]
Can you please have a look at 
https://github.com/githubakarsh/react-rookie-app/commit/422471e747275f481540e285c8caf042014121ef

Your help is appreciated !! 
Many Thanks

**Comment by badeball** [comment]
Alright, so `rookie-app-login-page.feature` isn't a valid feature-file. I recommend going through [the introduction to Cucumber](https://cucumber.io/docs/guides/overview/]) and particularly the [gherkin reference](https://cucumber.io/docs/gherkin/reference/).

Here's a valid version of it:

```gherkin
Feature:
  Scenario:
    Given I am an existing customer
    And I visit rookie app 
```
