### ISSUE TITLE
The ability to run my feature files in order

### ISSUE THREAD

**Issue by xuanvinhvu** [TheBrainFamily/cypress-cucumber-preprocessor#461]
I have two feature files A and B. I would like to only run B after A.

It would be nice to be able to do something like the following

`cypress run A.feature B.feature`

**Comment by badeball** [comment]
This has nothing to do with preprocessing. I recommend seeking help in the official documentation or Cypress' own official [Gittir channel](https://gitter.im/cypress-io/cypress).
