### ISSUE TITLE
DataTable type

### ISSUE THREAD

**Issue by xuanvinhvu** [TheBrainFamily/cypress-cucumber-preprocessor#464]
I would like to have type safety for dataTable.

```
Given("the user logged into to the tenant portal", (dataTable: DataTable) => {
   ...
});
```

The dataTable object seems to come from cucumber.js. I'm assuming there is no typescript definition for it?

**Comment by badeball** [comment]
Duplicate of https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/463.
