### ISSUE TITLE
assert that list grows after event fires

### ISSUE THREAD

**Issue by danieleades** [TheBrainFamily/cypress-cucumber-preprocessor#465]
I've got what feels like a fairly ordinary test- i need to assert that a table grows by one after an event. The catch is I don't know how big the table is when the test begins.

This is easy enough in pure cypress- I just check the current length, then chain the event, and finally assert that the new length has increased by 1.

Given that i'm now using cucumber, my cypress commands are decoupled, and I'm struggling to find an idiomatic way to represent this.

I've got it working by using a global variable that i'm setting in another step. Feels a bit awkward.

*feature*
```cucumber
Scenario: Add a new default asset
   When I add a new asset
   Then An asset is added to the table
```
then in javascript-
```javascript
import { Given, Then, When, Before } from "cypress-cucumber-preprocessor/steps";

let tableRows = 0;

When("I add a new asset", () => {
        // store initial value
	cy.get("#assets-table")
		.get("tr")
		.its("length")
		.then(length => {
			tableRows = length;
		});
	cy.get("#add-asset-btn").click();
});

Then("An asset is added to the table", () => {
	cy.get("#assets-table")
		.get("tr")
		.its("length")
		.should("equal", tableRows + 1);
});

```

What would be an idiomatic solution for this problem using this library?

**Comment by badeball** [comment]
Hi, @danieleades 

The preprocessor invokes your function bodies synchronously after each other, hence your approach won't work. You can achieve this using eg. [aliases](https://docs.cypress.io/guides/core-concepts/variables-and-aliases.html#Aliases).

**Comment by danieleades** [comment]
you're a gentleman and a scholar
