### ISSUE TITLE
I'm getting a strange error when running 'cypress open' 

### ISSUE THREAD

**Issue by jradom** [TheBrainFamily/cypress-cucumber-preprocessor#477]
### Current behavior
this is an error
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues

![image](https://user-images.githubusercontent.com/20550461/100534875-b1bb6280-31c8-11eb-83ef-ea8ed7b3b35e.png)

### Desired behavior
suppose to dhow Google site

### Test code to reproduce
my code
Feature: Login  and adding numbers feature
  As a valid customer I'm able to login into CAIR site

  @gierczynskiatom 
  Scenario: Login Validation
///    Given I am on CAIR login page
///    When I enter valid credentials
    And sum of two numbers is calculated

import { Given, When, Then, Before } from "cypress-cucumber-preprocessor/steps";
When(/^sum of two numbsers is calculated$/, function () {
///  cy.qe_cair();
///  cy.visit('http://qe.ist.bina.com');
  cy.visit('https://www.google.com');
});

always reproducible

### Versions

* **Cypress version**:
{
  "name": "e2e",
  "version": "0.0.1",
  "description": "SGP E2E tests",
  "main": "index.js",
  "author": "",
  "devDependencies": {
    "@cucumber/cucumber": "^7.0.0-rc.0",
    "@typescript-eslint/eslint-plugin": "^4.3.0",
    "@typescript-eslint/parser": "^4.3.0",
    "cypress": "^5.6.0",
    "cypress-file-upload": "^4.1.1",
    "cypress-promise": "^1.1.0",
    "eslint": "^7.10.0",
    "typescript": "^4.0.3"
  },
  "scripts": {
    "clean": "rm -rf ./node_modules",
    "lint": "npx eslint . --ext .ts"
  },
  "dependencies": {
    "@types/node": "^14.14.10",
    "cypress-cucumber-preprocessor": "^4.0.0"
  }
}

* **Preprocessor version**:
* **Node version**:
N7JG5L:CypressCucumber radomj$ node -v
v15.0.1
radomj-N7JG5L:CypressCucumber radomj$

**Comment by badeball** [comment]
Not able to reproduce. Provide a repository which illustrates the problem.
