### ISSUE TITLE
nonGlobalStepDefinitions: false does not work

### ISSUE THREAD

**Issue by cvolant** [TheBrainFamily/cypress-cucumber-preprocessor#478]
### Current behavior

With nonGlobalStepDefinitions set to false, none of the step definitions are found.
```
Error: Step implementation missing for: I open Google page
```

### Steps to reproduce

Really simple to reproduce:
- Clone [the official cypress-cucumber exemple repository](https://github.com/TheBrainFamily/cypress-cucumber-example)
- set nonGlobalStepDefinitions to false in the package.json, or remove the setting
- Launch the tests: `npx cypress run --spec **/*.features`
- :cry:  See the 'All features failed', and the missing step implementation errors.
- Try to udpate cypress-cucumber-preprocessor and cypress to their last versions
- Launch the tests again
- :sob:  See the same errors again

### Versions

* **Cypress version**: 4.9.0 or 6.0.1
* **Preprocessor version**: 2.5.0 or 4.0.0
* **Node version**: 14.3.0

**Comment by lgandecki** [comment]
Hello, thanks for the report.

If you change nonGlobalStepDefinitions, the step definitions have to be in a different place, why would you expect it to work the same if you change this configuration? :) 

Try moving the step definitions to cypress/support/step_definitions like in this repo:
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/tree/master/cypress/support/step_definitions

and see what happens :)

**Comment by cvolant** [comment]
Thank you for the quick answer !  I thought that since the step definitions were global, they could be declared anywhere...
So there is only 2 choices :
- either declaring all the step definitions in the support folder, completely appart'from the features,
- either creating one folder by feature (that makes a__lot__ of folders with only one file often nearly empty).

Am I correct ? There is no way to declare them in a way close to the following ? 
- 📂 integration
  - 📂 featureGroup1
    - feature1.feature
    - feature2.feature
    - feature3.feature
    - 📂 step-definitions
      - feature1.js
      - feature2.js
      - feature3.js

**Comment by lgandecki** [comment]
you can, just set stepDefinitions option to cypress/integration/step-definitions

**Comment by cvolant** [comment]
Yes, but I forgot to precise that the featureGroup1 folder wouldn't the only one: I would like to have several folders of features, each one containing a step-definitions folder. So I tried what you suggested with a glob pattern, "cypress/integration/**/step-definitions", but it doesn't work.

**Comment by cvolant** [comment]
Ok, sorry, I just needed to set stepDefinitions to "cypress/integration", and it works.
Thank you again for you work and your answers.
