### ISSUE TITLE
`Cannot read property 'native' of undefined` with multiple-cucumber-html-reporter

### ISSUE THREAD

**Issue by cvolant** [TheBrainFamily/cypress-cucumber-preprocessor#480]
### Current behavior

Importing multiple-cucumber-html-reporter (or cucumber-html-reporter) makes the tests crash with the following error:
```
  Running:  news/Google.feature                                                             (1 of 1)

  1) An uncaught error was detected outside of a test
  0 passing (233ms)
  1 failing

  1) An uncaught error was detected outside of a test:
     TypeError: The following error originated from your test code, not from Cypress.

  > Cannot read property 'native' of undefined

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.
Cypress could not associate this error to any specific test.
We dynamically generated a new test to display this failure.
      at Object.26.graceful-fs (http://localhost:35015/__cypress/tests?p=cypress/support/index.js:5338:24)
      at o (http://localhost:35015/__cypress/tests?p=cypress/support/index.js:1:265)
      at eval (http://localhost:35015/__cypress/tests?p=cypress/support/index.js:1:316)
      at ...
```

Really similar to https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/362 which is solved.
I tried the suggestion to add the following to my package.json, but it does not work better, event with "1.16.1".
```
  "resolutions":  {
    "resolve": "1.15.1"
  }
```

### Steps to reproduce

Really simple to reproduce:
- Clone [the official cypress-cucumber exemple repository](https://github.com/TheBrainFamily/cypress-cucumber-example)
- Install the reporter: `npm install multiple-cucumber-html-reporter`
- Add `const reporter = require('multiple-cucumber-html-reporter')` in _'/cypress/support/index.js'_
- Launch the tests: `npx cypress run --spec **/*.features`

I tried to update cypress-cucumber-preprocessor and cypress to their latest versions, but it does not solve the problem.

### Versions

* **Cypress version**: 4.9.0 or 6.0.1
* **Preprocessor version**: 2.5.0 or 4.0.0
* **Node version**: 14.3.0

**Comment by badeball** [comment]
`multiple-cucumber-html-reporter` uses `fs-extra`, which in turns uses `fs`, to read JSON reports and write HTML reports. This simply isn't available in the Cypress runtime and this is not how `multiple-cucumber-html-reporter` is supposed to be used. Closing as this isn't an error with the preprocessor.

**Comment by badeball** [comment]
You might have better luck using it from `plugins/index.js` and eg. invoking it through a [task](https://docs.cypress.io/api/commands/task.html).
