### ISSUE TITLE
Error: Step implementation missing for: {stepName}

### ISSUE THREAD

**Issue by ksezen59** [TheBrainFamily/cypress-cucumber-preprocessor#482]
Hello,

I am trying to implement Cucumber framework to my previously written cases while following a Cypress course. When I execute my feature file, I get an error below.

Running:  examples/BDD/ecommerce/ecommerce.feature                                        (1 of 1)

  End2End E-Commerce Validation
    1) E-Commerce Products Delivery

  0 passing (1s)
  1 failing

```
  1) End2End E-Commerce Validation
       E-Commerce Products Delivery:
     Error: Step implementation missing for: I open e-commerce page
      at Context.resolveAndRunStepDefinition (http://localhost:59873/__cypress/tests?p=cypress/integration/examples/BDD/ecommerce/ecommerce.feature:13435:11)
      at Context.eval (http://localhost:59873/__cypress/tests?p=cypress/integration/examples/BDD/ecommerce/ecommerce.feature:12773:35)
```

My ecommer.feature file : 

```
Feature: End2End E-Commerce Validation



    application Regression

    Scenario: E-Commerce Products Delivery
        Given I open e-commerce page
        When I add items to cart
        And Validate the total prices
        Then select the country submit and verify message
```

My eCommStepDef.js file:

```
import { Given, When, Then, And } from "cypress-cucumber-preprocessor/steps"
import HomePage from '../../../../support/pageObjects/HomePage'
import ProductPage from '../../../../support/pageObjects/ProductPage'

const homePage = new HomePage()
const productPage = new ProductPage()

Given('I open e-commerce page', function () {

    cy.visit(Cypress.env('url') + '/angularpractice')


})

When('I add items to cart', function () {


    homePage.getShopTab().click()


    this.data.productNames.forEach(function (element) {
        cy.addProductByName(element)
    });

    productPage.getCheckoutButton().click()


})

And('Validate the total prices', () => {

    cy.get('tr td:nth-child(4) strong').each(($el, index, $list) => {


        const amount = $el.text()
        var res = amount.split(" ")
        res = res[1].trim()
        sum = Number(sum) + Number(res)

    }).then(function () {
        cy.log(sum)
    })
    cy.get('h3 strong').then(function (element) {
        const amount = element.text()
        var res = amount.split(" ")
        var total = res[1].trim()
        expect(Number(total)).to.equal(sum)

    })

})


Then('select the country submit and verify message', () => {

    cy.contains('Checkout').click()
    cy.get('#country').type('Turkey')
    Cypress.config('defaultCommandTimeout', 15000)
    cy.get('.suggestions > ul > li > a').click()
    cy.get('#checkbox2').check({ force: true })
    cy.get('input[type="submit"]').click()
    cy.get('.alert.alert-success.alert-dismissible').then(function (element) {

        const actualText = element.text()

        expect(actualText.includes("Success")).to.be.true

    }


    )


})

```

My package.json file:

```
{
  "name": "cypress-training",
  "version": "1.0.0",
  "description": "Cypress Training",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cy:run": "cypress run"
  },
  "author": "Kerem Sezen",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^4.3.0",
    "cypress-cucumber-preprocessor": "^4.0.0",
    "cypress-iframe": "^1.0.1",
    "mocha": "^5.2.0",
    "mochawesome": "^6.2.1",
    "mochawesome-merge": "^4.2.0"
  },
  "dependencies": {
    "@types/core-js": "^2.5.4",
    "@types/jasmine": "^3.6.2"
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
}
```

My cypress.json file:

```
{
    "defaultCommandTimeout": 10000,
    "env": {
        "url": "https://www.rahulshettyacademy.com/"
    },
    "projectId": "ax1shi",
    "reporter": "mochawesome",
    "reporterOptions": {
        "overwrite": true,
        "html": true,
        "json": true
    },
    "testFiles": "**/*.feature"
}
```

My plugins/index.js file:

```
const cucumber = require('cypress-cucumber-preprocessor').default

module.exports = (on, config) => {
  on('file:preprocessor', cucumber())
}
```

The error:

node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js:195:1

Error: Step implementation missing for: I open e-commerce page
    at Context.resolveAndRunStepDefinition (http://localhost:60346/__cypress/tests?p=cypress/integration/examples/BDD/ecommerce/ecommerce.feature:13435:11)
    at Context.eval (http://localhost:60346/__cypress/tests?p=cypress/integration/examples/BDD/ecommerce/ecommerce.feature:12773:35)
From previous event:
    at Context.thenFn (http://localhost:60346/__cypress/runner/cypress_runner.js:155133:23)
    at Context.then (http://localhost:60346/__cypress/runner/cypress_runner.js:155572:21)
    at Context.<anonymous> (http://localhost:60346/__cypress/runner/cypress_runner.js:169999:21)
    at http://localhost:60346/__cypress/runner/cypress_runner.js:169423:15
From previous event:
    at runCommand (http://localhost:60346/__cypress/runner/cypress_runner.js:169402:8)

### Versions

* **Cypress version**: 4.3.0
* **Preprocessor version**: 4.0.0
* **Node version**: 12.14.1

**Comment by badeball** [comment]
Hi, @ksezen59

When using `nonGlobalStepDefinitions: true`, like you are doing, the step definitions must reside inside a directory with the same name as the feature-file, as described in the [readme](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#step-definitions-creation).

**Comment by badeball** [comment]
@lgandecki, it seems to me that missing step implementation is a common user-mistake and I was thinking a bit how to make it more apparent where the preprocessor will be looking.

This is somewhat of a radical suggestion, but what if we had a single configuration parameter a

```json
{
  "stepDefinitions": [
    "cypress/support/step_definitions/**/*.js",
    "cypress/integration/[filename]/**/*.js"
  ]
}
```

.. where `[filename]` is replaced with the name of the feature, excluding the file extension. Alternatively we could have `[filepath]` which I'm thinking would be the full path (again excluding extension) relative to `cypress/integration` (or whatever Cypress' `integrationFolder` might be configured to).'

My hope is that something like this would remove much doubt as to where the processsor will be looking.

**Comment by ksezen59** [comment]
Hello,

When I try to apply 1st suggestion, application throws me an error with a file name which I never have.

SyntaxError: Can't walk dependency graph:  : Unexpected end of JSON input
    required by /Users/sezenk/Desktop/CypressTraining/cypress/support/_fake.js

![image](https://user-images.githubusercontent.com/32410200/101471674-a4d10880-3958-11eb-9e59-39911513a122.png)

Project Structure:

![image](https://user-images.githubusercontent.com/32410200/101471740-b61a1500-3958-11eb-8351-898169c8343d.png)

After converting to 2nd suggestion(assuming that I replace the object element with nonGlobalStepDefinitions), I get the same error.

**Comment by ksezen59** [comment]
As 3rd method, I tried to change my package.json file as below. However, result is same.

```
{
  "name": "cypress-training",
  "version": "1.0.0",
  "description": "Cypress Training",
  "main": "index.js",
  "scripts": {
    "test": "echo \"Error: no test specified\" && exit 1",
    "cy:run": "cypress run"
  },
  "author": "Kerem Sezen",
  "license": "ISC",
  "devDependencies": {
    "cypress": "^4.3.0",
    "cypress-cucumber-preprocessor": "^4.0.0",
    "cypress-iframe": "^1.0.1",
    "mocha": "^5.2.0",
    "mochawesome": "^6.2.1",
    "mochawesome-merge": "^4.2.0"
  },
  "dependencies": {
    "@types/core-js": "^2.5.4",
    "@types/jasmine": "^3.6.2"
  },
  "stepDefinitions": [
    "../integration/examples/BDD/**/*.js"
  ]
}
```
  ]
}

**Comment by badeball** [comment]
I'm guessing that you actually have a syntax error in `cypress/support/_fake.js`, as the error suggests. Can you post its content?

**Comment by ksezen59** [comment]
There is no file in this path called "_fake.js", that's why it's so weird.

**Comment by badeball** [comment]
I can't help you any further without a reproducible example. You need to provide me with a repository somewhere that I can clone and run myself.

**Comment by ksezen59** [comment]
Kindly find in repository below.

https://github.com/ksezen59/CypressTraining/tree/master

**Comment by badeball** [comment]
You're not configuring it according to the documentation. Put the following in package.json:

```json
{
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
}

```

.. and move

```
cypress/integration/examples/BDD/ecommerce/ecommerce.js
```

.. to

```
 cypress/integration/examples/BDD/ecommerce/ecommerce/ecommerce.js
```

Then you'll see that the tests loads correctly. It doesn't pass, but that's due to other issues that you'll see.

**Comment by ksezen59** [comment]
Why would I create another ecommerce folder? Isn't there any other dynamic solutions? What about another feature files pathing?

**Comment by lgandecki** [comment]
You are a hero @badeball , as always. I agree, this is the most common problem. 

What you are proposing, if I understand correctly, is not to have two modes nonGlobal/global, but allow to configure it one way or another using/not using this '[filename]' keyword? I kinda like that :) it's clean. For transition period I think we should still keep it backward compatible though.. I would like the transition to the new version of this plugin to be mostly done by just updating the version (for all the most common and base usages)

Also, sorry for not getting back to you about using your version as the base, we've finished the project with a little delay, and now I got sick :) Life.. But! This is my task for the next week. I will look more closely at your code, see if there is anything I'd like to discuss or change, and prepare some release notes. I think at that point it would be also nice to build docusaurus page (something I've done for chimp - https://www.chimpjs.com , it's super simple to setup and it would be much nicer than just a README.md file, since docusarous also uses .md files for the docs, it shouldn't take more than few hours to set it all up )

**Comment by ksezen59** [comment]
Hi @lgandecki and @badeball  , I think your comments doesn't answer to any of my questions.

Any suggestions to place my js step definition files wherever like?

As per documentation, I kind of understand like the application should go all over the js files under "cypress/integration" regardless of the parent folders. 

stepDefinitions | cypress/integration when nonGlobalStepDefinitions is truecypress/support/step_definitions when nonGlobalStepDefinitions is false | Path to the folder containing our step definitions.

**Comment by badeball** [comment]
@ksezen59, you're right, our discussion doesn't pertain you.

However, I don't have the time (nor desire, honestly) to provide general support to everyone who wish to use Cypress + Gherkin. The primary reason for answering initially was to exclude the posibility that there was an actual issue with the preprocessor. Since there wasn't, I consider this issue to be closed.

You can try asking on Stackoverflow or Cypress' own official gitter. Don't expect help though, as this isn't an officially supported plugin in any way.

**Comment by ksezen59** [comment]
@badeball By the way, I also tried out your suggestion as adding a new "ecommerce" folder to path. It seems to have same error again.

![image](https://user-images.githubusercontent.com/32410200/101687816-19509800-3a7c-11eb-8c2e-6a509b954a6f.png)
![image](https://user-images.githubusercontent.com/32410200/101687833-2077a600-3a7c-11eb-8523-495d1ef3d993.png)
![image](https://user-images.githubusercontent.com/32410200/101687946-4bfa9080-3a7c-11eb-93ca-a26f143a8e52.png)
![image](https://user-images.githubusercontent.com/32410200/101687982-5b79d980-3a7c-11eb-80d0-0b0cd8a37d5a.png)

**Comment by badeball** [comment]
@ksezen59, don't *also* put your feature-file there, Do *only* what I told you to do.
