### ISSUE TITLE
Latest release breaks Cypress Custom Commands

### ISSUE THREAD

**Issue by vvanmol** [TheBrainFamily/cypress-cucumber-preprocessor#49]
Hello, 

When I use cypress-cucumber-preprocessor@1.0.0 every call to my Custom Commands defined in cypress/support/commands.js (imported in cypress/support/index.js as expected) are not recognised and I get error message "There is not Cypress Command issued for this test".

If I switch back to cypress-cucumber-preprocessor@0.6.0 everything works as expected.

FYI I'm using Cypress@2.1.0 in both cases.

**Comment by lgandecki** [comment]
This is very weird,as I don't see what could possibly cause this between the 0.6.0 -> 1.0.0 change.. would you be able to make a reproduction? That would help us a lot in fixing this problem

Thanks for reporting!

**Comment by volkanogretmen** [comment]
I'm running cypress-cucumber-preprocessor@1.0.0 and cypress 3.0.1 with custom commands and everything works fine. Perhaps updating cypress may help in this?

**Comment by lgandecki** [comment]
I'm going to close this for now to clear things up a bit, @vvanmol if you still have this problem after updating to the newest cypress please reopen, reproduction would be great (and shouldn't be hard).

**Comment by vvanmol** [comment]
Hello.
Sorry for the late reply...  I couldn't get back on this yet.
I'll try to reproduce it and if I can I'll re-open this ticket and provide more information.
Thanks !
