### ISSUE TITLE
cy.wrap() makes methods loose reference

### ISSUE THREAD

**Issue by Luiz-Ossinho** [TheBrainFamily/cypress-cucumber-preprocessor#494]
### Current behavior

As describe in this issue: https://github.com/cypress-io/cypress/issues/14508
cy.wrap will make objects loose track of their methods and will return undefined

### Desired behavior

I'm not extremely familiar with Cypress (or any Javascript),
but i believe that i should be able call methods inside objects as in both examples

### Test code to reproduce

```js
const bar = () => {
    // this represents a method
};

// This object will throw undefined when trying to use its methods
let ObjectListError = {
    entry = { propertyStr: "foo", propertyInt: 1, propertyFunc: bar}
}

// This object will work properly
let ObjectList = {
    entry = { propertyStr: "foo", propertyInt: 1, propertyFunc: () => {
            // this represents a method
        }}
}

When('Wraping objects', () => {
    cy.wrap(ObjectList.entry).as('ObjectList')
    cy.wrap(ObjectListError.entry).as('ObjectListError')
})

Then('Using properties from objects', () => {
    cy.get('@ObjectList').then($object=>{
        cy.log($object);
        // This will show that propertyFunc is a function
        // { propertyStr: "foo", propertyInt: 1, propertyFunc: function(){ }}
        // $object.propertyFunc() will work as intended
    })
    
    cy.get('@ObjectListError').then($object=>{
        cy.log($object);
        // This will show that propertyFunc as undefined
        // { propertyStr: "foo", propertyInt: 1, propertyFunc: undefined}
        // $object.propertyFunc() will throw an error
    })
})
```

scrennshot (true code ofuscated for privacy):
![image](https://user-images.githubusercontent.com/73566627/104495772-ee93bb00-55b6-11eb-89fd-4826c496dede.png)

### Versions

cypress: 6.1.0
-From what i've read in the changelog, this "bug" is still present in 6.2.0 and 6.2.1
cypress-cucumber-preprocessor: ^4.0.0
node-releases@^1.1.67

**Comment by badeball** [comment]
I'm not able to reproduce this. You need to provide me with a cloneable repository which successfully illustrates the issue.
