### ISSUE TITLE
Not able to use { retries} during Given, When and then

### ISSUE THREAD

**Issue by dthisner** [TheBrainFamily/cypress-cucumber-preprocessor#497]
When I tried using the new "Retries" that Cypress implemented, I wanted to have 1 test not retry for 3 times, just do it 

### Current behavior
When adding: `Then('I am at the login screen', { retries: 1 }, () => {`
I am getting:
```
Function.prototype.apply was called on undefined, which is a undefined and not a function
node_modules/cypress-cucumber-preprocessor/lib/resolveStepDefinition.js:208:1
  206 |         this,
  207 |         ...expression.match(stepText).map(match => match.getValue()),
> 208 |         argument
      | ^
  209 |       );
  210 |     }
  211 |     throw new Error(`Step implementation missing for: ${stepText}`);
```

### Desired behavior
Able to determine amount of retries at start of the test

### Test code to reproduce
```
Feature: Being a plugin handling DataTable scenario

  As a cucumber cypress plugin which handles DataTables
  I want to allow people to write DataTable scenarios and run it in cypress

  Scenario: DataTable
    When I add all following numbers:
      | number | another number |
      | 1      | 2              |
      | 3      | 4              |
    Then I verify the datatable result is equal to 10
```

```
When('I add all following numbers:', { retries: 1 }, dataTable => {
  sum = dataTable.rawTable
    .slice(1)
    .reduce(
      (rowA, rowB) =>
        rowA.reduce((a, b) => parseInt(a, 10) + parseInt(b, 10)) +
        rowB.reduce((a, b) => parseInt(a, 10) + parseInt(b, 10))
    )
})

Then(
  'I verify the datatable result is equal to {int}',

  result => {
    expect(sum).to.equal(result)
  }
)
```

### Versions

* **Cypress version**: 6.2.1
* **Preprocessor version**: 2.3.1
* **Node version**: v14.15.1

**Comment by badeball** [comment]
I'm unable to reproduce your error. Furthermore, Cypress retries aren't configured per step definition, but per scenario, thus this won't work.

**Comment by lgandecki** [comment]
I guess we could try to implement that functionality somehow. Maybe with a tag? A scenario tagged with @retry could have the {retries: 1} added dynamically

**Comment by dthisner** [comment]
Thanks @lgandecki ! 
This is a functionality I would have great use off :) 
Should I create a new ticket for this or should we re-open this one?

**Comment by lgandecki** [comment]
I think we can reopen this one but need to think about how this would look like. Not sure how else we could have it done if not with tags to be honest. But then do we only do the retry one? Or create the whole array of special cases @retry @retry1 @retry2 etc?

**Comment by dthisner** [comment]
Personally, I would only go between default value and just having it running once.

**Comment by wmedali** [comment]
This is a great feature, thanks for opening the issue @dthisner

**Comment by dthisner** [comment]
@iksinski @badeball  Can we open up this issue? since it seems to be worth implementing?

**Comment by badeball** [comment]
What exactly are you looking for here, retrying scenarios or retrying step definitions?

Retrying step definition isn't something you should ever feel compelled to do, as Cypress already has built in retry-ability in their commands. If this isn't enough, you're doing something wrong. Furthermore, I don't see how it could be implemented unless it's something similar is already possible in Cypress (without a preprocessor).

**Comment by dthisner** [comment]
@badeball Can you please provide an example how you implement Cypress retry? 
I am trying to retry a scenario. I have some scenarios that I don't want to have retries on.

**Comment by alastair-todd** [comment]
@badeball cypress added the ability to retry a test, in our case this would be a scenario. retrying cypress commands wont help a network failure for example as that is an app exception. [See here](https://docs.cypress.io/guides/guides/test-retries.html#Custom-Configurations).

A `@Retry` attribute on the feature, scenario or background would be really useful as we can still configure retires on cypress at the global level. this is just to cover specific flakey tests
