### ISSUE TITLE
Not able to Use text "A/B" within Step Definition

### ISSUE THREAD

**Issue by far11ven** [TheBrainFamily/cypress-cucumber-preprocessor#498]
I want to use a text "A/B", which doesn't need to be retrieved as a String in my code.
"A/B" is just for highlighting purpose in my Cucumber step.

### Current behavior

A step with text "A/B" in the cucumber step is not matched step-definition.

My Step Definition:
![image](https://user-images.githubusercontent.com/26922130/105575898-075d5700-5d95-11eb-9e68-9e6343d41f5a.png)

My Cuumber Step:
![image](https://user-images.githubusercontent.com/26922130/105575906-1fcd7180-5d95-11eb-995c-b71f8f2dc852.png)

### Desired behavior

A step with text "A/B" in the cucumber step is not matched step-definition. As both the texts are same, I don't want to pick it using  {string} in my step definition

### Test code to reproduce

```
    @smoke
    Scenario: GET all atamodels
        #Given As a user I want to execute signIn api request with "TEAM_LEAD" user role
        #Then verify "@signin" response status code is 200
        #And verify access token is received in cookies
        When I make a GET request on "A/B" endpoint
        #Then verify response status code is 200
        #And verify datamodels list is received
```
When('I make a GET request on "A/B" endpoint', () => {

```
  cy.request({
      method: 'GET',
      url: `/trainer/api/analytics/datamodels`,
      headers: {
        'Content-Type': 'application/json'  
      }
  }).as('getDataModelsForTrainer');
  
})
```

### Versions

* **Cypress version**:  NA
* **cypress-cucumber-preprocessor**: "^4.0.0",
* **Node version**:  v12.18.3

**Comment by badeball** [comment]
You're likely encountering [alternative text](https://cucumber.io/docs/cucumber/cucumber-expressions/#alternative-text). Try escaping it.

**Comment by steevessaillant** [comment]
When('I make a GET request on {string} endpoint', (value) => {

//use the value passed: "A/B"
  cy.request({
      method: 'GET',
      url: `/trainer/api/analytics/datamodels`,
      headers: {
        'Content-Type': 'application/json'  
      }
  }).as('getDataModelsForTrainer');
  
})

**Comment by far11ven** [comment]
@steevessaillant I don't want to extract and use "A/B" as value, just for naming

**Comment by badeball** [comment]
I'm going to assume to tried escaping as per Cucumber's docs and solved this. Feel free to say otherwise, but only if you actually tried.
