### ISSUE TITLE
Cypress detected that you returned a promise in a test, but also invoked one or more cy commands inside of that promise

### ISSUE THREAD

**Issue by kpturner** [TheBrainFamily/cypress-cucumber-preprocessor#499]
When running Cypress tests via the cypress-cucumber-preprocessor I saw a number of these warnings. It is not causing my tests to break but I wanted to eradicate the warnings nevertheless.  However, when I went through my scenarios and steps I could not find anything that would cause it.  So I created a bare bones scenario that did absolutely nothing other than `cy.log('HELLO')` and I still got the warnings.

If I put a breakpoint on the warning and look at the call stack it seems to be caused by code in the preprocessor (createTestFromScratch.js), firstly in:

```
const runTest = (scenario, stepsToRun, rowData) => {
  const indexedSteps = stepsToRun.map((step, index) =>
    Object.assign({}, step, { index })
  );

  // should we actually run this scenario
  // or just mark it as skipped
  if (scenario.shouldRun) {
    // eslint-disable-next-line func-names
    it(scenario.name, function() {
      const state = window.testState;
      return cy
        .then(() => state.onStartScenario(scenario, indexedSteps)). <<<<< HERE
```
and then here
```
// eslint-disable-next-line func-names, prefer-arrow-callback
  after(function() {
    cy.then(() => testState.onFinishTest()).then(() => {            <<<<<< HERE
      if (window.cucumberJson && window.cucumberJson.generate) {
        const json = generateCucumberJson(testState);
        writeCucumberJsonFile(json);
      }
    });
  });
```

### Current behavior

Cypress noisy warnings in console 

### Desired behavior

No Cypress warnings in console

### Test code to reproduce

Any test scenario will produce this result

### Versions

* **Cypress version**:  4.9.0
* **Preprocessor version**: 2.5.2
* **Node version**: 10.9.0

**Comment by badeball** [comment]
Not able to reproduce. Where do you encounter there warnings? Provide us with an example repostory.

**Comment by kpturner** [comment]
You have asked for an example and then closed the issue?

**Comment by badeball** [comment]
> You have asked for an example and then closed the issue?
 
I don't personally care so mcuh about the issue-status, tt wasn't very deliberate. Do you want to argue about it or do you rather want to just provide what I asked you for?

**Comment by lgandecki** [comment]
It's just a cleanup... if we can't reproduce and there is no reproduction provided we need to consider an issue closed, as we are doing this for free and have super limited resources (basically me and badeball, and recently it's more like 90% badeball), for ~150k weekly installs (which is almost 10% of all cypress users, which itself is a tool from a for-profit company providing paid services.)

It might be a bit nicer to wait a few days for a reproduction, I agree.. 😅 But most people never come back and I assume badeball closing the issue basically marked it for himself as "checked". It's easy to reopen things.  Please do provide a small repro where you are positive that the issue shows up. 
A hunch - are you testing on windows?

**Comment by kpturner** [comment]
> 
> Do you want to argue about it or do you rather want to just provide what I asked you for?

Why the aggressive attitude?   I wasn't being unreasonable in assuming "closed" = "Not going to look at it anymore".
How was I supposed to automatically know that the issue status is irrelevant on this project.

People are taking the time to log questions and issues because they want to help the developers improve the package. We aren't doing it to try to irritate you. Passive/aggressive responses will simply discourage that level of interaction.

**Comment by kpturner** [comment]
> ....But most people never come back .....
Understood. I will of course endeavour to boil it down into a manageable reproducible repo.  It will take some time as these Cypress tests are embedded in a monolithic proprietary application/repo that I am not at liberty to share.  Doing so may actually give me more insight into the cause. Either way I will report back.

> A hunch - are you testing on windows?

Actually no, it is on Ubuntu.

**Comment by badeball** [comment]
> People are taking the time to log questions and issues because they want to help the developers improve the package. We aren't doing it to try to irritate you. Passive/aggressive responses will simply discourage that level of interaction.

That's hilarious, but honestly it would be nice if that was the reality. The reality however is much, much sader. Most issues filed are unfortunately characterized by one or more of the following

* Author having done no debugging on their own
* Not providing enough information to reproduce a problem
* Containing large bodies of code instead of a clonable repository, making the job suck just a little bit more
* Having basic issues with npm / node
* Having issues with Cypress
* Having not read the readme
* Being a duplicate, IE. author hasn't even searched beforehand
* Just looking for testing advice / support

Maintaining the package at this point mostly entail debugging on behalf of other people (who either aren't capable of it themselves or haven't bothered) and explaining them how they're wrong. It's an exhaustive and unappreciative job.

People might have the best intentions, but most do *nothing* to help improvide the package and are really just wasting my time. Hence, I believe _some_ level of aggressiveness is warranted. Your desire to be treated differently is understandable, but it's not my priority.

> It will take some time as these Cypress tests are embedded in a monolithic proprietary application/repo that I am not at liberty to share. Doing so may actually give me more insight into the cause.

You're right that doing so would provide more insight. It's exactly what either of the maintainers would have had to do on your behalf. Why would you not just do this for us beforehand?

**Comment by kpturner** [comment]
> Why would you not just do this for us beforehand?

Because I believe(d) I had provided enough information already by debugging the tests down to providing the exact line(s) of code that threw the error. I didn't just post a throwaway remark on an issue without any investigation. It seemed very easily reproducible. Your feedback (inability to replicate based on the information provided) indicates that I was wrong in my assertion and need to dig deeper.  That is the way these things usually work - right?  

But honestly, your reaction and comments genuinely have discouraged me from doing so.  I have no wish to make the maintainers life a misery, and I have no wish to be reprimanded if my next effort still fails to meet with your approval.

Feel free to leave it closed.
