### ISSUE TITLE
Change steps and scenarios to default features path

### ISSUE THREAD

**Issue by fccoelho7** [TheBrainFamily/cypress-cucumber-preprocessor#50]
Hello guys, I would like to change `step_defintions` path and `scenarios` to default `features` path proposed by Cucumber.

Following the structure:
```
features/
  step_definitions/
  scenarios/
```
Does it possible?

**Comment by KeithGillette** [comment]
Did you find a way to change the paths, @fccoelho7? We like to colocate our `.feature` and `steps.ts` files, so would like to create a structure like:
```
features/
  user-register/
    user-register.feature
    user-register.steps.ts
  user-sign-in/
    user-sign-in.feature
    user-sign-in.steps.ts
```
