### ISSUE TITLE
[Feature-Request] add option to exclude non-matching tags from test run entirely

### ISSUE THREAD

**Issue by emturner** [TheBrainFamily/cypress-cucumber-preprocessor#500]
related: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/436

### Current behavior
Currently when running a feature that contain scenarios with non-matching tags are marked as `pending` in the test output.

### Desired behavior
Have a `cypress.json` option which results in scenarios being excluded from the run all together. 

e.g.
```
{ "excludeSkippedTests": true }
```

### Test code to reproduce
It is possible to work around this by having two feature files: `first.feature` and `first.e2efeature` as a way of splitting up scenarios tagged with `@e2e` vs ones which don't, while still enabling access to all steps defined under `first/`.

You can then leverage `excludeFiles` option to do the filtering

This feels like a bit of a hack - and results in small things like syntax highlighting breaking on the `first.e2efeature` file.

### Versions

* **Cypress version**: 6.3.0
* **Preprocessor version**: ^4.0.0
* **Node version**: 12.8.3 (bundled)

**Comment by emturner** [comment]
If you'd be open to having something like this, I'd be more than happy to have a look and submit a PR!

**Comment by badeball** [comment]
See my [answer](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/436#issuecomment-768200356) in the related issue.

**Comment by emturner** [comment]
Hi @badeball, thanks for replying!

so we can split tests up like you suggested - but then we run into the issue of not being able to use private steps from two different feature files.  

The scenario is that we have some @ci tests, and @e2e tests.  We're using cypress.io to upload our test results when running against our environment - only running @e2e.  We don't want the @ci tests to show up as pending, as that counts as a test result in cypress.io.

So currently we have: 
```
x/steps.js        -> contains steps for x
x.feature         -> contains @ci tests
x.e2efeature   -> contains @e2e tests
```

This allows to just run either e2e or ci or both, using the *testfiles* option.  Then when we run using `*e2efeature` filter only our e2e tests show up in cypress.io

However, it feels like this is relying on the internals of the processor, in that it doesn't care what the extension is for the feature file.  If that changed in future our workaround would break.

It would be nicer if we could use tags instead to decide which tests we are running, and not have to split up our files in this way.  If we had an option to exclude cypress-cucumber-preprocessor from outputting tests which get skipped, then we'd could do this.

Would this be possible at all?  Thanks

**Comment by badeball** [comment]
It seems to me like you can name your files

- x.e2e.feature
- y.ci.feature

.. and specify `testFiles` either as `**/*.e2e.feature` or `**/*.ci.feature` and thus not rely on the fact the preprocessor incidentally don't care right now.

**Comment by emturner** [comment]
we can do that - but run into issues with the private steps.

we don't want to duplicate the private steps into both `x/steps.js` and `y/steps.js` when they are the same.
We have other feature files that we don't want to be able to access the steps for `x`, hence why we can't use common.

**Comment by badeball** [comment]
> we don't want to duplicate the private steps into both x/steps.js and y/steps.js when they are the same.

You can import files willy-nilly, so just put the x-y-shared steps into some other file which both `x/steps.js` and `y/steps.js` can import.

Another alternative is to just use symlinks.

> It would be much nicer to just mix the ci and e2e tests for a feature within the same file, but if this really isn't something that you'd want to have as an option, then I'll close this off.

Let me be blunt here for a second. Every piece of added functionality comes with a maintenance cost. Your use case seems incredibly narrow to me and at the same time solvable in other ways. This (mixing different test suites) simply isn't something I expect a preprocessor to cater to and at the moment I'm unfortunately not even remotely convinced to implement this.

**Comment by emturner** [comment]
fair enough - I'll close this off then.  I completely understand that added functionality incurs future maintenance cost - and if this use case is too narrow then that's completely your call.

Thanks for taking the time to respond! :smile:
