### ISSUE TITLE
How to skip all scenarios from a specific feature file

### ISSUE THREAD

**Issue by devsrihari4** [TheBrainFamily/cypress-cucumber-preprocessor#501]
Is there any way to skip all scenarios from a specific feature (here featreA) file and run specific scenarios with tag (tagA) from remaining all features.

@featreA
Feature: The featreA

  @tagA
  Scenario: scenario 1

@featreB
Feature: The featreB

  @tagA
  Scenario: scenario 1

  @tagB
  Scenario: scenario 2

featreC
Feature: The featreC

  @tagA
  Scenario: scenario 1

  @tagB
  Scenario: scenarion 2

**Comment by badeball** [comment]
Tag behavior in the preprocessor should conform to Cucumber's own behavior. Tthis is essentially a re-implementation and therefore it might not, and if you find that it doesn't you may open an actual bug-ticket. I suggest you read up on [cucumber tags](https://cucumber.io/docs/cucumber/api/#tags).
