### ISSUE TITLE
"@ignore" tag gives me -> Sync Skip: aborting execution

### ISSUE THREAD

**Issue by dthisner** [TheBrainFamily/cypress-cucumber-preprocessor#503]
I have been setting up another project to have same setup as one where I have a good setup for Cypress and Cucumber setup. 

The weird thing is that I can't get the `@ignore` tag to work, I add it to a test and when I run cypress, I get:

```
CypressError
sync skip; aborting execution
node_modules/cypress-cucumber-preprocessor/lib/createTestFromScenario.js:71:1
  69 |         .then(() => state.onFinishScenario(scenario))
  70 |         // eslint-disable-next-line func-names
> 71 |         .then(function () {
     | ^
  72 |           return this.skip();
  73 |         });
  74 |     });
```

Been comparing my other projects setup and what I can find, nothing is different  

Cypress.json:
```
{
  "baseUrl": "http://localhost:3001/",
  "testFiles": "**/*.{feature,features}",
  "viewportWidth": 1920,
  "viewportHeight": 1080,
  "retries": {
    "runMode": 2,
    "openMode": 0
  },
  "env": {
    "TAGS": "not @ignore",
    "mobile_viewportWidth": 414,
    "mobile_viewportHeight": 896,
    "mobile": false
  }
}
```

package.json:

```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  }
```

plugins -> index.js

```
import cucumber from 'cypress-cucumber-preprocessor';
const cucumberdefault = cucumber.default;

module.exports = (on) => {
  on('file:preprocessor', cucumberdefault());
};
```

File in question:
```
@smokeTest
Feature: 404 page Test

  @ignore
  Scenario: User is able to see 404 page
    When user visit a 404 page
    Then text "Not Found" is displayed
```

    Cypress version: 6.4.0
    Preprocessor version: 4.0.0
    Node version: v14.15.1

**Comment by badeball** [comment]
I'm not able to reproduce your isuse. Please provide an example repository which illustrates the problem.

**Comment by dthisner** [comment]
Works when I downgraded to preprocessor version 3.0.0
I will setup a working setup today or tomorrow that repos the issue at hand

**Comment by dthisner** [comment]
Wasn't able to repo. Thanks badeball for you taking the time

**Comment by dthisner** [comment]
nvm, was able to reproduce it

**Comment by dthisner** [comment]
Here is the repo: https://github.com/dthisner/cypressIssue

**Comment by badeball** [comment]
This appears to be a problem with Cypress and can be seen with the following, simplified example. You should create another ticket with them.

```js
it("should work", function () {
  cy.then(() => this.skip()); // throws "sync skip; aborting execution"
});
```

@lgandecki, I'm actually a bit perplexed here. Has eg. the focus tag ever worked since #329?

**Comment by dthisner** [comment]
Found it being logged here: https://github.com/cypress-io/cypress/issues/14867

Will close this issue. Thanks for your guys help :)

**Comment by dthisner** [comment]
Interesting note, I need to run: `Cypress@6.2.1` and `cypress-cucumber-preprocessor@2.3.1` to make tags work as it should.

**Comment by ganeshbalasti** [comment]
in my case it was an issue with other plugin called cypress-terminal-report. So remove unnecessary plugins if any.
