### ISSUE TITLE
"Cannot find step" when using Optional (|) syntax in step definition with more than one variable {}

### ISSUE THREAD

**Issue by DaveClissold** [TheBrainFamily/cypress-cucumber-preprocessor#507]
I am experiencing an issue where I cannot add more than one variable in a step if I have an optional part in the step definition.  example below

feature
```
 Scenario Outline: AC01 User should be able to select one or more <item> content types from the drop down, with each item being added to the filter labels list
        When I search for "sandwich"
        Then I can filter "<type>" by "<item>"
        Examples:
            | type    | item      |
            | Content | Article   |
            | Content | Event     |
            | Content | Video     |
            ...
```
step file
```
defineStep("I (can |)filter {string} by {string}", function(s, t) {
 ...
} 
```
The cucumber(Gherkin) full support extension in VSCode it shows that it can find the step definition in the feature file and a step elsewhere in the feature and step files using a single variable works perfectly

```defineStep("I (can |)sort by {string}", function () {```

**Comment by badeball** [comment]
This project has literally nothing to do with vscode or syntax hightlightling. You're in the wrong place.

**Comment by lgandecki** [comment]
I think he gets "cannot find step" error from our preprocessor. But I'm not sure I understand this sentence:

```
The cucumber(Gherkin) full support extension in VSCode it shows that it can find the step definition in the feature file and a step elsewhere in the feature and step files using a single variable works perfectly
```

@DaveClissold Could you please rephrase it, maybe split it into 2/3 sentences, and then read it out loud to make sure it makes sense? For example I'm 100% sure the "Cucumber full support extension in VSCode it shows" is not correct. It brakes the flow of the sentence and makes it hard to understand what's going on. For example I'm not sure what all the "it"s and "in"s mean. 

Does one of those defineSteps get highlighted by the VScode, but not the other? Or do both seem to work according to VScode but only one of them works with our preprocessor?

**Comment by DaveClissold** [comment]
@lgandecki Sorry for the confusion with that sentence, even I had a problem reading it back and the mention of the extension is confusing the matter, just ignore that, I was trying to indicate that the steps were not missing. The only bit to note from that is

_A step in the same step file and feature file, works 
```defineStep("I (can |)sort by {string}", function () {```_

So to answer your last question, it is the preprocessor that is not working.

**Comment by badeball** [comment]
I'm not able to reproduce the issue, IE. two variables with optional text seems to work fine. Granted, I removed the vertical bar from the step defintion.

**Comment by DaveClissold** [comment]
@badeball I tried removing the vertical 'OR' bar and it does work, but when I try the following, which is something I need in another test that I'm writing

```defineStep("I (can change|have changed) {string} with {string}", function (s, t)```

the error persists

**Comment by badeball** [comment]
First of all, alternative text happens with slash, not vertical bar. Furthermore, I don't believe it's allowed within an optional group. This can be seen [here](https://github.com/cucumber/cucumber/blob/messages/v14.0.1/cucumber-expressions/javascript/testdata/expression/does-not-allow-alternation-in-optional.yaml).

**Comment by DaveClissold** [comment]
@badeball I've just realised the mistake I'm making and I do apologise, I'm using regular expressions and didn't realise.  That said when I try to define the step using regex, either 

`defineStep(/I (can change|have changed) {string} with {string}/, function() ...`

or 

`defineStep("^I (can change|have changed) {string} with {string}$", function() ...`

I get the cannot find step implementation error, do you support using regular expressions in step definitions, I noticed at the bottom of the docs you say to not use legacy methods.

**Comment by badeball** [comment]
Regular expressions are supported, but the `{string}` syntax is part of `cucumber-expressions`, which is a language that translates into regular expressions. When you use regular expressions yourself, you do not get the benefit of EG. `{string}`. Hence, you would have to do something like

```js
defineStep(∕^I (?:can change|have changed) "([^"]+)" with "([^"]+)"$/, function(arg1, arg2) {})
```

**Comment by DaveClissold** [comment]
Of course, me being stupid again and crossing syntax. Thanks for the support and apologies again for my stupidity on this.
