### ISSUE TITLE
Improve the cucumber-js report.

### ISSUE THREAD

**Issue by vio-codes** [TheBrainFamily/cypress-cucumber-preprocessor#508]
### Current behaviour
Individual report generated by the plugin cannot be imported successfully into [Cucumber for Jira](https://marketplace.atlassian.com/apps/1221264/cucumber-for-jira-bdd-natively-in-jira?hosting=cloud&tab=overview)

After I merge all the individual json files into a big one the import works.

But even then only the status is updated, no duration or marking which step exactly failed.

### Desired behavior

I want to be able to generate a cucumber-js report that is imported correctly into [Cucumber for Jira](https://marketplace.atlassian.com/apps/1221264/cucumber-for-jira-bdd-natively-in-jira?hosting=cloud&tab=overview)

### Test code to reproduce

Report generated by your example repo.

### Versions

* **Cypress version**: 6.4.0
* **Preprocessor version**:4.0.1
* **Node version**: LTS

**Comment by badeball** [comment]
Nobody here has time to research into the requirements of other parties' software, such as a Jira-plugin. Unless you can provide us with exact information as to what they require, this will unfortunately not be fixed.

**Comment by badeball** [comment]
Allow me to elaborate a little bit on this. The reason for which research is likely required, is because the JSON-format is inherently unspecified by Cucumber themselves, which means we have nothing to work with. Furthermore, the JSON-format is going away from Cucumber and likely here as well.

**Comment by vio-codes** [comment]
Hi this issue can be closed. I understand your point @badebal, so I ended up talking with the guys that manage the jira plugin.
