### ISSUE TITLE
Fetching resource at '/__cypress/tests?p=src/support/index.ts' failed

### ISSUE THREAD

**Issue by olliiiver** [TheBrainFamily/cypress-cucumber-preprocessor#509]
### Current behavior

I've configured an nx monorepo with cypress-cucumber-preprocessor by following these tutorials:

https://tapaibalazs.dev/how-to-set-up-gherkin-with-nx-cypress-ts/

https://stackoverflow.com/questions/58374064/use-feature-files-in-cypress-with-nrwl-nx

However, when I run the tests (``nx e2e frontend-e2``), the Cypress windows pops up and following message appears after some minutes:

````
 1) An uncaught error was detected outside of a test:
     Error: The following error originated from your test code, not from Cypress.

  > Fetching resource at '/__cypress/tests?p=src/support/index.ts' failed

When Cypress detects uncaught errors originating from your test code it will automatically fail the current test.

Cypress could not associate this error to any specific test.

We dynamically generated a new test to display this failure.
      at XMLHttpRequest.xhr.onerror (http://localhost:4200/__cypress/runner/cypress_runner.js:175071:14)
 ````

### Desired behavior

Tests should be executed without the error from above. 

### Test code to reproduce

The behaviour can be reproduced in the following repository:

https://github.com/olliiiver/nx-cypress-cucumber-angular-test

### Versions

* **Cypress version**: 6.0.1
* **Preprocessor version**: 4.0.1
* **Node version**: 15.2.1

I really want to get this to run. Any help would be very much appreciated.

**Comment by olliiiver** [comment]
Don't know if there is a similarity to https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/491, but please find the reproducible repo from above (https://github.com/olliiiver/nx-cypress-cucumber-angular-test).

**Comment by badeball** [comment]
I'm not able to reproduce the problem using the above-mentioned repository. The test seems to hang when requesting the support-file and I don't see any error. I'm unfortunately not able to dig any deeper into anything ng-related. You can try running it with `DEBUG=cypress:*` and see if that reveals anything.

**Comment by olliiiver** [comment]
Thanks @badeball 

There had been two issues:

1) The plugins/index.js was just wrong.
2) Importing ``import { Before, Given, Then } from 'cucumber';`` in step file caused another issue returning a very weird error message (Arguments to path.resolve must be strings). It must be ``import { Before, Given, Then } from "cypress-cucumber-preprocessor/steps"``
