### ISSUE TITLE
Skip scenarios

### ISSUE THREAD

**Issue by fccoelho7** [TheBrainFamily/cypress-cucumber-preprocessor#51]
Does have any way to skip some scenarios by adding a tag `@skip` for example or another approach?

**Comment by lgandecki** [comment]
Not currently, there is #46 that implements this, would you like to take a look and review? It would be great to have another pair of eyes on it

**Comment by lgandecki** [comment]
Duplicate of #24, should come soon when #46 / #58 gets merged in. I'm closing this one out to clean things up a bit - please observe #24 issue or the #58 PR

Thanks!
