### ISSUE TITLE
How do I run a Before step before multiple tests (by using multiple tags)?

### ISSUE THREAD

**Issue by DlDanielStoica** [TheBrainFamily/cypress-cucumber-preprocessor#511]
How do I run a Before step before multiple tests (by using multiple tags)?

In the example given in the docs, I can run this step before tests tagged with `@foo`:

```
// this will only get called before scenarios tagged with `@foo`
Before({ tags: "@foo" }, () => {
  beforeWithTagCounter += 1;
});
```

What if I want to run this step before tests tagged with `@foo` and `@bar`?

**Comment by badeball** [comment]
Can you use the or-operator, as described in Cucumber's [documentation](https://cucumber.io/docs/cucumber/api/#tag-expressions)?

**Comment by DanielStoica85** [comment]
If you mean something like this, I tried and it did not work:

```
Before({ tags: "@foo and @bar" }, () => {
  doSomething();
});
```

**Comment by badeball** [comment]
No, like this.

```js
Before({ tags: "@foo or @bar" }, () => {
  doSomething();
});
```

**Comment by DanielStoica85** [comment]
> 
> 
> No, like this.
> 
> ```js
> Before({ tags: "@foo or @bar" }, () => {
>   doSomething();
> });
> ```

Yeah, that worked. Thank you, @badeball .

**Comment by badeball** [comment]
I'm glad! I'm then considering this closed for now.
