### ISSUE TITLE
Tags currently not compiling at all

### ISSUE THREAD

**Issue by softwareqi** [TheBrainFamily/cypress-cucumber-preprocessor#513]
When clicking on a feature-file in cypress test runner an Error occurs.

### Current behavior

Error: Webpack Compilation Error
./cypress/integration/AnotherExample.feature 6:2
Module parse failed: Unexpected character '@' (6:2)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
|     "**I can** send and fetch REST calls"
| 
>   @anotherApi
|   Scenario: cy.request() - make an XHR request
|     Given Visitting "https://example.cypress.io/commands/network-requests"

![CypressCucumber_WebpackCompilationError_UnexpectedCharacter](https://user-images.githubusercontent.com/68852803/108207023-77a69080-7127-11eb-8581-4d0eb3f29a45.png)

### Desired behavior

Feature File is compiling and executing

### Versions

* **Cypress version**: 6.5.0
* **Preprocessor version**: 4.0.1
* **Node version**: 14.15.5

**Comment by badeball** [comment]
You're going to have to show us the whole feature-file.

**Comment by softwareqi** [comment]
Feature: AnotherExample
    "**In order to** use my Backend Services"
    "**As a** Frontend"
    "**I can** send and fetch REST calls"

  @anotherApi
  Scenario: cy.request() - make an XHR request
    Given Visitting "https://example.cypress.io/commands/network-requests"
    When Send a GET request to /comments
    Then Check for proper response and header

**Comment by softwareqi** [comment]
I tried reverting cucumber-preprocessor to 4.0.0 but without effect

**Comment by badeball** [comment]
I'm not able to reproduce the issue. Have you configured webpack similar to that shown [here](https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example/blob/master/cypress/webpack.config.js)?

**Comment by softwareqi** [comment]
All I did was setting up with base settings and configuration...
- create a working directory
- npm init -y
- npm i --save-dev cypress
- npm i --save-dev cypress-cucumber-preprocessor
- npx cypress open
- adding "cucumber configuration" to "plugins/index.js"
- adding "testFiles": "**/*.feature" to cypress.json
- adding "cypress-cucumber-preprocessor": { "nonGlobalStepDefinitions": true } to package.json
- copy "feature" and "step_definitions" to integration
- run the feature in test runner

BUT... repeated these exact actions today >> no problem! why? don't know!
