### ISSUE TITLE
How to link feature files 

### ISSUE THREAD

**Issue by Rishikantpd** [TheBrainFamily/cypress-cucumber-preprocessor#515]
I have created a login.feature with only one login scenario 
I have created another account.feature file that will create the account 
Now I want to call login scenario to account.feature
Can you please help me in that?

**Comment by badeball** [comment]
This isn't possible, as explained [here](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/438). Simply put, this is an anti-pattern and not something you should feel compelled to do.

**Comment by Rishikantpd** [comment]
Thank for your response and i have one more doubt do I need to cerate the folder with same name as .feature has?
if i am creating 5 feature files means i need to create 5 folder with the same name?
