### ISSUE TITLE
Step implementation with custom parameters not recognized in Webstorm

### ISSUE THREAD

**Issue by oosterholt** [TheBrainFamily/cypress-cucumber-preprocessor#529]
When a step implementation contains a custom parameter, this is not recognized in Webstorm.

### Current behavior

![image](https://user-images.githubusercontent.com/730953/111470885-98fb9c00-8728-11eb-84e9-b37cc415b993.png)

### Desired behavior

I expect the step to be recognized:
![image](https://user-images.githubusercontent.com/730953/111470991-b4ff3d80-8728-11eb-8750-6817a7b52561.png)

### Test code to reproduce

**Feature**:

     Scenario: Opening the dashboard tab as a manager
     Given As a Manager I open the tab "Overview"
     Then I see "Testing Portfolio" in the title`

**Custom step definition**:

    Given('As a {role} I open the tab {string}', (roleName, tabName) => {
	// implementation
    });

**Custom parameter definition**:

    defineParameterType({
	    name: 'role',
	    regexp: new RegExp("Manager|Reader"),
	    transformer: (n) => n,
    });

Feature is correctly tested; so it is a matter of Webstorm detecting a step with a custom parameter

**Comment by lgandecki** [comment]
Webstorm does not know about cypress cucumber at all, could you try make it work with pure cucumber? if not, it would mean it's a webstorm issue and not related to our project. The only thing that could be wrong on our side would be if we used some function names or API differently

**Comment by badeball** [comment]
This just isn't this package's responsibility and as explained [here](https://github.com/badeball/cypress-cucumber-preprocessor/pull/1#issuecomment-762092157), it will likely never happen. You _could_ do some static analyzes of the AST to safely resolve custom parameters, but again - it's up the your IDE and their plugin.
