### ISSUE TITLE
it is not possible to add env after defining the tags

### ISSUE THREAD

**Issue by yaanr3is** [TheBrainFamily/cypress-cucumber-preprocessor#532]
Hello!

### Current behavior

I try to run the following command to define tags and envs.

`npx cypress-tags run -e TAGS='@fidelity and @regress and not @Ignore' --env configFile=hlg`

The code executes normally, except that it executes the not @Ignore tag that it shouldn't.

So when I execute the command:

`npx cypress-tags run -e TAGS='@fidelity and @regress and not @Ignore'`

Without --env configFile = hlg it runs perfectly and following the rule of not executing the scenarios that @Ignore has.

### Desired behavior

How could I execute the tags and set the environment variables that I pass through the command line?

### Versions

* **Cypress version**: ^4.12.1
* **Preprocessor version**: ^2.5.5
* **Node version**: v12.18.3

**Comment by badeball** [comment]
Multiple variables has to be separated by commas, not by specifying `-e / --env` multiple times. This is simply how the Cypress CLI works. Try this instead.

```
$ npx cypress-tags run --env TAGS='@fidelity and @regress and not @Ignore',configFile=hlg
```

**Comment by yaanr3is** [comment]
Perfect, it worked as expected <3
