### ISSUE TITLE
I have to close my browser down to restart the test on any change of .feature file

### ISSUE THREAD

**Issue by inspiraller** [TheBrainFamily/cypress-cucumber-preprocessor#539]
There is a button - 'Run All Tests' in browser mode of cypress.
When ever I fix something and resave my .feature file I currently have to close this mode down, and rerun it which is painfully time consuming.

**Comment by badeball** [comment]
I'm not able to reproduce the issue you're describing. It seems to reload upon changes just fine, both to feature-files and step-definitions.

**Comment by inspiraller** [comment]
This is running from command line with:

```
nyc --reporter=text-summary cypress run --browser chrome --no-exit
```

Note I am also using 
- typescript 
- instrumentation with nyc and istanbul 
- coverage,
but I can't see how that would be preventing  this but I will have to test it without to prove the case.

**.nycrc.json**
```
{
  "extends": "@istanbuljs/nyc-config-typescript",
  "all": true,
  "report-dir": "cypress-coverage",
  "include": [
    "src/**/*.ts",
    "src/**/*.tsx"
  ]
}
```

**cypress/support/index.js**
```
import '@cypress/code-coverage/support';
```

**babel.config.js** 
```
  env: {
    test: {
      plugins: ['istanbul']
    }
  },
```
**package.json - plugins**
```
    "@istanbuljs/nyc-config-typescript": "^1.0.1",
      "babel-plugin-istanbul": "^6.0.0",
      "istanbul-lib-coverage": "^3.0.0",
      "nyc": "^15.1.0",
      "@cypress/code-coverage": "^3.9.4",
```
and setting 
```
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": true
  },
```

**Comment by badeball** [comment]
`cypress run` doesn't watch for file changes as far as I know, and it has nothing to do with this preprocessor. If you want the interactive experience, you should run `cypress open`.
