### ISSUE TITLE
Cypress run in Jenkins

### ISSUE THREAD

**Issue by kayvanbree** [TheBrainFamily/cypress-cucumber-preprocessor#54]
When I run cypress run in Jenkins like this:

```
stage('Build e2e test container') {
        docker.build('wecapangular/cypress', "-f Dockerfile.cypress .")
    }

    stage('Run e2e tests') {
      withDockerContainer(args: "-u root", image: 'wecapangular/cypress') {
        sh 'cd /usr/src/app && npm run cypress:run'
      }
    }
```

With this Dockerfile:

```
FROM cypress/base

COPY package.json /usr/src/app/package.json
COPY package-lock.json /usr/src/app/package-lock.json
COPY src /usr/src/app/src/
COPY karma.conf.js /usr/src/app
COPY angular.json /usr/src/app
COPY tsconfig.json /usr/src/app
COPY cypress.json /usr/src/app
COPY cypress /usr/src/app
COPY .npmrc /usr/src/app

WORKDIR /usr/src/app

RUN npm install
```

Cypress will raise an error. It can't find spec files within cypress/integration/.

Does cypress-cucumber-preprocessor work with the cypress run command?

**Comment by breeny** [comment]
cypress-cucumber-preprocessor works within Jenkins (we have it in our build pipeline).

Perhaps your plugin index.js isn't being copied correctly - have you checked that the full `cypress` folder is being copied correctly within the container?

**Comment by kayvanbree** [comment]
Okay, that's good to know. I'll check if the cypress folder is actually filled and if index.js is copied correctly!

**Comment by lgandecki** [comment]
@kayvanbree it should work. Please let us know so we can either try to help out or close this issue :-) 
@breeny thanks for your input!

**Comment by kayvanbree** [comment]
I think I can get it to work. The only problem I have now is that I run my application in Jenkins with `ng serve`, which never exits, so I can't run cypress and Jenkins hangs. 

```
FROM cypress/base

WORKDIR /usr/src/app

# Copy the application
RUN ls -al /usr/src/app
COPY package.json /usr/src/app
COPY package-lock.json /usr/src/app
COPY src /usr/src/app/src
COPY angular.json /usr/src/app
COPY .npmrc /usr/src/app
COPY tsconfig.json /usr/src/app

# Copy test files
COPY cypress.json /usr/src/app
COPY cypress/ /usr/src/app/cypress

# Some stuff to make the build faster
RUN npm set progress=false && npm config set depth 0 && npm cache clean --force

# Install new version of npm because cypress has 5.7
RUN npm install -g npm
RUN npm install

CMD npm start

# CMD npm run cypress:run
```

I got this running locally like this:

1. Run `docker build -t nameof/image -f Dockerfile.cypress`
2. Run `docker run -p 4200:4200 nameof/image`
3. In a separate powershell, run `docker exec <container_name> npm run cypress:open`

However, when I run it in Jenkins npm run start will never exit, so cypress:run will never be executed. 

```
stage('Build e2e test container') {
         docker.build('wecapangular/cypress', "-f Dockerfile.cypress .")
      }

      stage('Run e2e tests') {
       withDockerContainer(args: "-u root", image: 'wecapangular/cypress') {
         sh 'cd /usr/src/app && npm run start'
         sh 'cd /usr/src/app && npm run cypress:run'
       }
      }
```

Is there a way to do this or should I create a Docker compose, 2 containers and run Cypress tests from one container to the other?

**Comment by kayvanbree** [comment]
This might be more a Cypress problem though.
