### ISSUE TITLE
Is it a way to run Scenarios in parallel on Jenkins?

### ISSUE THREAD

**Issue by jradom** [TheBrainFamily/cypress-cucumber-preprocessor#542]
### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

**Comment by badeball** [comment]
One way is to consider this a knapsack problem. You assign each feature-file a weight based on its expected execution time. Then you divide all feature files into similar chunks. Based off of a node-index and a node-count, you can now invoke Cypress with `--spec`.

In other words, there's nothing in Cypress nor the preprocessor to help you with this. It's certainly possible, but you have to do it yourself.
