### ISSUE TITLE
Cannot reuse steps across features files

### ISSUE THREAD

**Issue by Dawogi** [TheBrainFamily/cypress-cucumber-preprocessor#543]
### Current behavior

Cannot reuse steps across features files.

I.e. I have a project with login page, and topbar that I want to test after login:

[![enter image description here][1]][1] 

Got LoginPage.feature and LoginPage.js step file, everything works fine, all tests run correctly.

[![enter image description here][2]][2]
 
I would like reuse steps “Given user open TestPage login page” and “When user login using valid credentials” from LoginPage.js in TopBarCmp.feature:

[![enter image description here][3]][3]
 
But it always ends with error:

[![enter image description here][4]][4]
 

Long time ago I used Specflow(Cucumber for .Net) and it was normal to ruse steps with same singatures across all features - Basically reuse functionality that was automated in other features.

  [1]: https://i.stack.imgur.com/Y3Egz.png
  [2]: https://i.stack.imgur.com/QbwyG.png
  [3]: https://i.stack.imgur.com/WciSG.png
  [4]: https://i.stack.imgur.com/gGup7.png

### Desired behavior

Reuse steps with same signature across all features

### Versions

* **Cypress version**: 7.0.1
* **Preprocessor version**: 4.0.3
* **Node version**: 14.15.4

**Comment by badeball** [comment]
This is already possible. Please read the whole readme one more time before asking again how to do it.

Furthermore, posting screenshots depicting a problem is insanely unhelpful to us. It makes it incredibly difficult to attempt to reproduce a scenario.

**Comment by lgandecki** [comment]
To add to that - you probably need to remove the nonGlobalStepDefinitions or set it to false
