### ISSUE TITLE
2nd cy.wait fails when there are two cy.intercept with same alias

### ISSUE THREAD

**Issue by varunpradhan** [TheBrainFamily/cypress-cucumber-preprocessor#551]
### Current behavior

There is a cy.intercept which has a dynamic URL with an alias. When we call cy.wait for this alias for the second time, then it fails to look for the new URL/alias.

As cy.intercept URL is dynamic, 2 different routes are generated with same alias:

![image](https://user-images.githubusercontent.com/26091432/115143677-5f3eed80-a066-11eb-86b7-41468321c1f9.png)

Now the 1st cy.wait is passed:

![image](https://user-images.githubusercontent.com/26091432/115143723-a0cf9880-a066-11eb-9fe4-de2e7890e663.png)

When system tries to wait on 2nd cy.wait it fails:

![image](https://user-images.githubusercontent.com/26091432/115143785-01f76c00-a067-11eb-992c-7ae8e65d20ff.png)

Below is stack printed on Cypress Test Runner:

![image](https://user-images.githubusercontent.com/26091432/115143824-2a7f6600-a067-11eb-9690-0bebdb8d571a.png)

### Desired behavior

System should catch the latest URL/alias and wait for it.

### Test code to reproduce

I have the git repo which we can clone - **https://github.com/varunpradhan/bddeapp**

Run the feature file - **cypress\integration\bddCy\multipleCalls.feature**

Below is the cy.intercept code which has dynamic URL, which is also found under **cypress\step_definitions\common\editEmployee.js** in the git repo

```
class editEmployee {
    benefitEmp(index) {
        cy.intercept({
            method: "GET",
            url: `**/Benefit/Details/${index}`,
        }).as('empBenefit');

        cy.get(`[href="/Benefit/Details/${index}"]`).click()

        cy.wait('@empBenefit').then(({ response }) => {
            expect(response.statusCode).to.equal(200);
        })
    }

}
```

### Versions

* **Cypress version**: 6.8.0
* **Preprocessor version**: ^2.3.1
* **Node version**: 12.18.4

**Comment by badeball** [comment]
This is just how Cypress behaves / misbehaves when you're overwriting / reusing aliases and it is not an issue with the preprocessor.
