### ISSUE TITLE
Step implementation missing for:  feature name

### ISSUE THREAD

**Issue by uzeyirqa** [TheBrainFamily/cypress-cucumber-preprocessor#556]
Hi, 

I am using the cypress cucumber preprocessor and each time I get "error: Step implementation missing for:..." 

My configurations:

Cypress.json file:

![Screenshot 2021-04-27 at 00 28 20](https://user-images.githubusercontent.com/83247101/116146798-f56eb580-a6ef-11eb-9fab-38a4ec591f12.png)

Package.json file:

![Screenshot 2021-04-27 at 00 28 36](https://user-images.githubusercontent.com/83247101/116146796-f4d61f00-a6ef-11eb-81d5-ced3b3db74de.png)

index.js file:

![Screenshot 2021-04-27 at 00 28 54](https://user-images.githubusercontent.com/83247101/116146791-f30c5b80-a6ef-11eb-84a7-481a089deb9d.png)

Steps file:

![Screenshot 2021-04-27 at 00 27 53](https://user-images.githubusercontent.com/83247101/116146803-f6074c00-a6ef-11eb-8d04-0541182b1574.png)

Feature file:

![Screenshot 2021-04-27 at 00 26 51](https://user-images.githubusercontent.com/83247101/116146807-f869a600-a6ef-11eb-9cae-09afe296cf43.png)

project structure:

![Screenshot 2021-04-27 at 00 27 25](https://user-images.githubusercontent.com/83247101/116146806-f7d10f80-a6ef-11eb-9929-665731fee5c6.png)

I searched for similar issues and It looks that it should work but I get this error:

![Screenshot 2021-04-24 at 04 43 39](https://user-images.githubusercontent.com/83247101/116147429-c1e05b00-a6f0-11eb-9319-ff27c313a21d.png)

Please advise how to solve this issue

### Versions

* **Cypress version**:  "^7.1.0"
* **Preprocessor version**: "^4.1.0"
* **Node version**: v15.14.0

**Comment by PatoDeVille** [comment]
i am having the exact same problem, were you able to solve it?

**Comment by badeball** [comment]
Parenthesis have special meaning in cucumber expressions, as explained [here](https://cucumber.io/docs/cucumber/cucumber-expressions/#optional-text).

**Comment by Sabareesh-UB** [comment]
Were you able to solve @uzeyirqa ? I am facing the same issue

**Comment by umytjandurdyyev** [comment]
I am also facing same problem.

**Comment by lgandecki** [comment]
Did you guys see the link from Badeball?
It says:
```
Escaping
If you ever need to match () or {} literally, you can escape the opening ( or { with a backslash:

I have {int} \{what} cucumber(s) in my belly \(amazing!)
```

**Comment by Fiontan** [comment]
where is the problem in the original files? Van anyone see it? Hving the same issue with a VERY simple file with no ( nor {

**Comment by faisalakmal** [comment]
already solved guys?

**Comment by milindr4123** [comment]
Cypress es un maldito asco

**Comment by Leonfag** [comment]
This did not happen when i used java + selenium

**Comment by TejasSingh-CS** [comment]
I have explained the steps here; please follow them, as I hope they will help. I faced the same issue and tried several other documentation sources without success. Eventually, I checked the npm packages and found that installing the related dependencies resolved the problem. Then i created medium post to help my cypress community.

npm i -D cypress cypress-cucumber-preprocessor
npm install --save-dev cypress-cucumber-preprocessor

https://medium.com/@imtejassingh/cypress-with-cucumber-in-just-5-simple-steps-8e0206f6da4f
