### ISSUE TITLE
How to run multiple tags to before and after hooks

### ISSUE THREAD

**Issue by hussainsam** [TheBrainFamily/cypress-cucumber-preprocessor#558]
Hey, 

Sorry for the lame question. I am trying to add @firstTest and @secondTest tag to the before hook. How can I add both of these ? It's not working for tags with comma separated 

``
Before({ tags: "**@firstTest", @secondTest**}, () => {

});
``

**Comment by badeball** [comment]
```js
Before({ tags: "@firsttest and @SecondTest" }, () => {});
```

or

```js
Before({ tags: "@firsttest or @SecondTest" }, () => {});
```

.. depending on what you want to achieve.

https://cucumber.io/docs/cucumber/api/#tag-expressions

**Comment by hussainsam** [comment]
Thanks a ton :)
