### ISSUE TITLE
2 Backgrounds throw a plugin crash error in Cypress

### ISSUE THREAD

**Issue by jameseg** [TheBrainFamily/cypress-cucumber-preprocessor#559]
### Current behavior
throwing non-descriptive error when 2 Backgrounds are present

![image](https://user-images.githubusercontent.com/38703245/117075723-4b041d00-ad03-11eb-8d4b-bba7cd276e51.png)

### Desired behavior

tell me why it crashed, or alert me before i click through and try to start the feature file

### Versions

* **Cypress version**:
* **Preprocessor version**:
* **Node version**:

**Comment by badeball** [comment]
This is the error propagated by the gherkin parser, which we don't maintain. If you were to expand the error, you would likely see something like

```
expected: #EOF, #TableRow, #DocStringSeparator, #StepLine, #TagLine, #ScenarioLine, #ScenarioOutlineLine, #Comment, #Empty, got 'Background:'
```

... which should tell you pretty clearly that you're doing something wrong.
