### ISSUE TITLE
Check for support - Fixture file in Feature file

### ISSUE THREAD

**Issue by ashishpCACTUS** [TheBrainFamily/cypress-cucumber-preprocessor#563]
I just want to check if there is an option to set a JSON based fixture file inside the Feature file. 

I am trying to see if under the Examples section of my Scenario Outline if I can provide the location of a JSON file stored under the fixture folder which has properties names which I can provide in the Gherkin test in <> same as we provide for a datatable one. 

I have very huge test data. About 40-50 params to be added for some tests. Also some of the columns needs to have 4000 characters tested. It will be a very long inline data table and hard to maintain.  

Please let me know if  there is an option  to specify  a JSON  file  in Examples section  not just a datatable

**Comment by badeball** [comment]
There is no such option.
