### ISSUE TITLE
Typescript Property env does not exist on type CypressNpmApi

### ISSUE THREAD

**Issue by inspiraller** [TheBrainFamily/cypress-cucumber-preprocessor#565]
### Current behavior

currently I cannot access cypress.env variables declared either in cypress.json, cypress.env.json or .env using cypress-dotenv

### Desired behavior
.env should be available via typescript and be able to run

steps.ts
```
import Cypress from 'cypress';
import { Given } from 'cypress-cucumber-preprocessor/steps';

Given(/I have environment variable ('[^\']*')/, (key) => {
  const email = Cypress.env('email'); // <!- this should not display error
  expect(email).to.be.a('string');
});
```

### Test code to reproduce
See repo. Reduced just for this error.

https://github.com/inspiraller/next-cypress-cucumber-boilerplate

**Comment by badeball** [comment]
You shouldn't import from `cypress` like that. It's a global variable available in the runtime and you just have to configure [`tsconfig.json`](https://docs.cypress.io/guides/tooling/typescript-support#Configure-tsconfig-json) appropriately. Furthermore, this isn't an actual issue with the preprocessor.
