### ISSUE TITLE
Run After hook even when the Cucumber scenario failed

### ISSUE THREAD

**Issue by hussainsam** [TheBrainFamily/cypress-cucumber-preprocessor#573]
Hi,

Is there a way I can run After hook even when the scenario fail?  I am using Cypress 6.9.1

**Comment by MateuszNowosad** [comment]
What version of cypress-cucumber-preprocessor are you running? We fixed this issue in v4.1.1.

**Comment by hussainsam** [comment]
@MateuszNowosad  Hi, I am using cypress-cucumber-preprocessor version 1.6. So I just need to update the preprocessor. Any additional thing should I need to do ? or calling just Asfter simply works

**Comment by lgandecki** [comment]
Probably nothing additional except you should "pray to Thor himself" that everything else will still work :) You will be jumping through a few versions with breaking changes. 
If things break you can take a look at the https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/releases , find the "breaking changes" and see if their descriptions help you get things to work again

**Comment by hussainsam** [comment]
Thank you for the quick response. I now know how to proceed
