### ISSUE TITLE
Step definitions inside subfolders don't work when providing commonPath to the config

### ISSUE THREAD

**Issue by okky-rymera** [TheBrainFamily/cypress-cucumber-preprocessor#594]
### Current behavior

When setting a custom commonPath via the config, the files in subfolders won't work. To reproduce:
1. Set the config in package.json:
   ```
   "cypress-cucumber-preprocessor": {
     "nonGlobalStepDefinitions": true,
     "commonPath": "cypress/step_definitions/"    
   }
   ```
2. Add a step definition under `cypress/step_definitions/subfolder/step_def.js`
3. Try to use the step definition in a feature file

Issue: I won't be able to find the step definition

Note: If you put it under `cypress/step_definitions/step_def.js`, it will work.

### Desired behavior

It should find the step definition even if it's inside a subfolder.

### Test code to reproduce

package.json
```
"cypress-cucumber-preprocessor": {
  "nonGlobalStepDefinitions": true,
  "commonPath": "cypress/step_definitions/"    
}
```

cypress/step_definitions/subfolder/step_def.js
```
Given("I test something", () => {
  cy.log("Step definition is found")
})
```

cypress/integration/test.feature
```
Feature: test

  Scenario: test
    Given I test something
```

### Possible issue

It seems under `cypress-cucumber-preprocessor/lib/getStepDefinitionsPaths.js` for the getStepDefinitionsPaths function, it has:

```
if (config.commonPath) {
  commonPath = path.resolve(appRoot, commonPath);
}
```

The `path.resolve()` will always remove the trailing slash, so even when my commonPath includes trailing slash ("cypress/step_definitions/"), the `commonDefinitionsPattern` will always be "cypress/step_definitions**/*.+(js|ts|tsx)"

### Versions

* **Cypress version**: 7.6.0
* **Preprocessor version**: 4.1.3
* **Node version**: 16.3.0

**Comment by fypnlp** [comment]
Hi, you're not alone.  [I'm experiencing the same thing as well](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/593).  Took me 3 days to figure  out it was the dependency and not user error.

**Comment by lgandecki** [comment]
Sorry for this, you are absolutely right, and what's even worse, we have a test for this specific combinations of options and we mocked the path.resolve in a wrong way:
```typescript
jest.mock("path", () => ({
      resolve(appRoot, commonPath) {
        return `./${appRoot}/${commonPath}`;
      },
      extname() {
        return ".js";
      },
    }));
```

which would keep the trailing slash passed from commonPath, when in reality resolve removes it. We don't even need that mock, so I removed it and fixed the issue, the release should be out there soon.
