### ISSUE TITLE
Can't run step definition.js file after new update

### ISSUE THREAD

**Issue by fypnlp** [TheBrainFamily/cypress-cucumber-preprocessor#596]
I honestly feel really about doing this,  but the problem in the new release does not appear to be resolved 

I updated the dependency with the new release.  I opened cypress runner and and ran the test file 

Expected Result 

E2E test with BDD 

However this is what I got, [watch this video](https://www.dropbox.com/s/cnz6poh6mmuolw0/Feature%20file%20still%20not%20linking%20to%20step%20definition%20file.mp4?dl=0) 

Screen shot  of  testing 

![Screenshot 2021-07-09 at 17 26 21](https://user-images.githubusercontent.com/39129689/125109086-cb1b7a00-e0da-11eb-8fd1-824ed1375cb6.png)

### Versions

* **Cypress version**: 7.4.0
* **Preprocessor version**:  Mac Big Sur
* **Node version**: 14.17.1

**Comment by lgandecki** [comment]
Try putting the shoppingCart.js file into integration/BDD/shoppingCart/shoppingCart.js (there is supposed to be a folder matching the feature file next to the feature file)

**Comment by fypnlp** [comment]
Hi thanks for getting back to me so quickly.  I really appreciate it.  All my files are in the same folder.  
![Screenshot 2021-07-09 at 17 33 08](https://user-images.githubusercontent.com/39129689/125109820-bd1a2900-e0db-11eb-9056-46e79991f55e.png)

**Comment by lgandecki** [comment]
yeah that's not correct, try to do what I said please. ./integration/BDD/shoppingCart.feature ./integration/BDD/shoppingCart/shoppingCart.js . if you want to have the files in the same folder make nonGlobalStepDefinitions: false  , that will have the side-effect of having all steps available to all feature files

**Comment by fypnlp** [comment]
let me try it and let me get back to you

**Comment by fypnlp** [comment]
[watch the video](https://www.dropbox.com/s/3ae0hxoa77lffw6/plugin%20update.mp4?dl=0).  I have  misunderstood something let me know and break down step by step how I should rectify it.

**Comment by stevenlafl** [comment]
@fypnlp I had to use regex instead. Did you try `/^I am on the Ecommerce page$/` ? Sad that I can't use it with `{string}` as it shows in the documentation either.

**Comment by fypnlp** [comment]
@stevenlafl     I was able to FINALLY fix it

1. adding ANOTHER folder in the under BDD called shoppingCart
2. In the package.json I added the following

```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/integration/BDD/"
```

Notice, I was forced to change the **nonGlobalStepDefinitions to false**

It was able to read the Feature file and start running the test . 

I now have a data issues.  But this problem appears to be resolved!

**Comment by Thetestport** [comment]
Hello, can someone please help me? I am experiencing the same issue as reported above "Step Implementation Missing " I have   
1. included the following in my package.json

"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/e2e/BDD/"
    
 2.  I have added the .feature file directly into "BDD folder"
 3. I have added a folder "repLogin" to the "BDD folder" and added step file to it
 
but I still get the error

**Comment by badeball** [comment]
@Thetestport, assuming your using `@badeball/cypress-cucumber-preprocessor`, you need to configure `stepDefinitions` with a pattern matching files, EG. `cypress/e2e/BDD/*.js`.

**Comment by Thetestport** [comment]
@badeball thanks for the response. i have done that and still get "step implementation missing

![1](https://github.com/badeball/cypress-cucumber-preprocessor/assets/140278561/51e9ad5e-41cc-4d87-9b46-14c2f7b8471b)

**Comment by badeball** [comment]
Then you need to provide a [minimal, reproducible example](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/CONTRIBUTING.md#reduced-test-case) that illustrates the issue.

**Comment by Thetestport** [comment]
**1. Fixture file**
{
  "email": "kydstest1@gmail.com",
  "password": "tentancles3."
 
}

**2. PageObject**
import testData from '../../../../fixtures/loginCredentials.json';

export class FaceBookLoginPage {
    elements ={
        emailField: ()=> cy.get('#email'),
        passwordField: ()=> cy.get('#pass'),
        loginButton: ()=>cy.get('#u_0_0_fV'),
    }
    
  Login(){
    this.elements.emailField().type(testData.email);
    this.elements.passwordField().type(testData.password);
    this.elements.loginButton().click();
  }

}

export const faceBookLogin = new FaceBookLoginPage();

**3. Feature file**
Feature: Login Functionality
    User logs in to facebook

    Scenario: Face Book Login
    Given The User opens the url
    And He Verifies the fields
    When He specifies his valid credentials
    Then He should be able to login successfully
    
**4. StepDefinition**

import { Given, When, Then, And } from 'cypress-cucumber-preprocessor/steps';
import { faceBookLogin } from '../../pageObjects/facebookLoginPage';

Given('The User opens the url', () => {
    cy.visit(Cypress.env('externalConsoleUrl'));
});


And('He Verifies the fields', ()=>{
    // Check if the register link is present
    faceBookLogin.elements.emailField().should('be.visible');
    faceBookLogin.elements.passwordField().should('be.visible');
    faceBookLogin.elements.loginButton().should('be.visible');
})

When('He specifies his valid credentials', ()=>{
    faceBookLogin.repLogin();

})

Then('He should be able to login successfully', ()=>{
        // Assert URL 
    cy.url().should('include', 'web.facebook.com/');
})

**5. cypress.config**

const { defineConfig } = require("cypress");

const {addCucumberPreprocessorPlugin,} = require("@badeball/cypress-cucumber-preprocessor");
const {preprocessor,} = require("@badeball/cypress-cucumber-preprocessor/browserify");

async function setupNodeEvents(on, config) {
  // This is required for the preprocessor to be able to generate JSON reports after each run, and more,
  await addCucumberPreprocessorPlugin(on, config);

  on("file:preprocessor", preprocessor(config));

  // Make sure to return the config object as it might have been modified by the plugin.
  return config;
}

module.exports = defineConfig({
  viewportHeight: 800,
  viewportWidth: 1280,
  video: true,
  LANG: 'en_US.UTF-8', // Set the desired encoding
  env:{
    url: "https://web.facebook.com/",
    
  },
  projectId: "",

  retries:{
    runMode: 1 //this will rerun failed test 1 more time
  },

  e2e: {
    
    specPattern: 'cypress/e2e/**/*.feature',
    setupNodeEvents,
    
  },
});

**6. package.json**
{
  "name": "errorreproduction",
  "version": "1.0.0",
  "description": "Error reproduction",
  "main": "index.js",
  "scripts": {
    "test": "node_modules\\.bin\\cypress run"
    
  },
  "cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "stepDefinitions": "cypress/e2e/BDD/*.js"
  },
  "keywords": [],
  "author": "",
  "license": "ISC",
  "dependencies": {
    "@badeball/cypress-cucumber-preprocessor": "^20.0.4",
    "@cypress/browserify-preprocessor": "^3.0.2",
    "chai": "^5.1.0",
    "cypress": "^13.6.6"
  },
  "devDependencies": {
    "@types/cypress": "^1.1.3",
    "cypress-xpath": "^2.0.1"
  }
}

**Comment by Thetestport** [comment]
@badeball  Thanks for the response. I have reproduced my codes and step missing error using a facebook login flow.

**Comment by badeball** [comment]
> I have reproduced my codes and step missing error using a facebook login flow.

You haven't quite though. You omitted to provide file names and locations, which are crucial parts.

Given that you're importing `And` and doing so from `cypress-cucumber-preprocessor/steps` - I'm guessing you've been reading some outdated blog post. Stop doing that and instead look through any of the [many examples](https://github.com/badeball/cypress-cucumber-preprocessor/tree/master/examples), which all work. The package lives under a [new name](https://github.com/badeball/cypress-cucumber-preprocessor/issues/689) and no support is provided for `cypress-cucumber-preprocessor`. Everything you need to know about resolving "Step implementation missing" can be found in the [documentation](https://github.com/badeball/cypress-cucumber-preprocessor/blob/master/docs/step-definitions.md).

**Comment by Thetestport** [comment]
@badeball thanks a lot for the help. I am pretty much new to this and confused much, Nevertheless, I will go read up on the documentations you have provided

**Comment by Thetestport** [comment]
@badeball Thank you. I have read the documents in the links you provided and the error has been resolved
![1](https://github.com/badeball/cypress-cucumber-preprocessor/assets/140278561/42376e92-5eb5-4de3-9d26-4a5da6eb8dcb)

I have also implemented in my real codes and they work perfectly

**Comment by TejasSingh-CS** [comment]
I have explained the steps here; please follow them, as I hope they will help. I faced the same issue and tried several other documentation sources without success. Eventually, I checked the npm packages and found that installing the related dependencies resolved the problem. Then i created medium post to help my cypress community.

npm i -D cypress cypress-cucumber-preprocessor
npm install --save-dev cypress-cucumber-preprocessor

https://medium.com/@imtejassingh/cypress-with-cucumber-in-just-5-simple-steps-8e0206f6da4f
