### ISSUE TITLE
Allow any step definition with any follow up string

### ISSUE THREAD

**Issue by tobi-adekanye-itm** [TheBrainFamily/cypress-cucumber-preprocessor#597]
Currently the options for starting a step are Given, When, Then, And .... which are followed by a string or regex.

For example `Given("I go to the homepage, () => .....` .

But what if I wanted to us the statement "I go to the homepage" with an `And` step definition starter, then I would have to essentially copy and paste the exact same code body but with the function `And(.....`. 

Is there a way to allow us to use a step definition with ANY starter we want. This will make things so much more flexible. Thank you 🙏🏾

**Comment by lgandecki** [comment]
That's exactly how things work, try it.
