### ISSUE TITLE
Error: ENOENT: no such file or directory, open '..\cypress-cucumber-example\node_modules\cypress-cucumber-preprocessor\temporary-..\cypress-cucumber-example\cypress\integration\Google.feature.js'

### ISSUE THREAD

**Issue by serviax** [TheBrainFamily/cypress-cucumber-preprocessor#6]
Hi,

Thanks for this nice project!

I tried to run this example but unfortunately encountered some problems when trying to run it.
These are the steps I took: 
`git clone https://github.com/TheBrainFamily/cypress-cucumber-preprocessor.git`
`npm install`
`node_modules\.bin\cypress open`
Then tried to run test "Facebook.feature"

I ended up with this error:
Error: ENOENT: no such file or directory, open 'C:\Projects\Github\cypress-cucumber-example\node_modules\cypress-cucumber-preprocessor\temporary-C:\Projects\Github\cypress-cucumber-example\cypress\integration\Facebook.feature.js'

I tried to install some additional depndencies
like 
`npm install --save gherkin`
`npm install --save @cypress/browserify-preprocessor`
but that didn't help either.

**Comment by lgandecki** [comment]
I think this was fixed in 0.0.3 and the example was still using 0.0.2 - hence failing on Windows. I updated the example, please check again @serviax . Thanks for reporting! If this still doesn't work please let me know, if it's a different error message create a new issue, I'm closing this for now as I don't think this could possibly error out like that anymore.

**Comment by Anilkumarotte** [comment]
Error: ENOENT: no such file or directory, stat 'C:\Users\pc\AppData\Roaming\Cypress\cy\production\projects\Cypress cucumber-d722a61a77b061ffa1b8e055df15bea2\bundles\cypress\e2e\Hometest.feature'
 I am getting above issue

**Comment by PRAVEENKUMAR782** [comment]
I have same issue , I have created the feature file in my cypress/e2e with .feature extension   , but when I am running , system is reading file from some other folder , no idea why . Any way to correct this ?
No idea why cypress is searching in appdata folder where my framework is installed in documents folder .

Attaching first screenshot from my cypress run where we can openurl.feature file is visible , and second image is from the error while trying to run 

here is the screen shot of error
![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/90023844/f0ff8674-cfe6-42a9-aaf4-7ef1dd3b6773)

![image](https://github.com/badeball/cypress-cucumber-preprocessor/assets/90023844/d43d6ac7-1558-4681-b6de-96fcb482a4da)

**Comment by badeball** [comment]
@PRAVEENKUMAR782, you will have better luck if you can provide a reproducible example.
