### ISSUE TITLE
Step definitions with the same name in multiple step_definition files

### ISSUE THREAD

**Issue by dankelleher** [TheBrainFamily/cypress-cucumber-preprocessor#60]
It looks like you cannot have two steps with the same name in different features with different implementations. e.g.

login.feature
`Given I enter my details`

...should point to step_definitions/login.js `given('I enter my details', function() ... )`

signup.feature
`Given I enter my details`

...should point to step_definitions/signup.js `given('I enter my details', function() ... )`

At the moment it seems like the first one to be loaded wins. Is there any way to solve this?

**Comment by lgandecki** [comment]
hmmm.. I'm not aware if there should be a way to resolve this, the step definitions should be global, as far as I understand. There is no matching between the feature file name and where to get the step definition from. 

Maybe we can figure out a different way of doing what you are trying to do - could you please tell us why/when would you have two steps of the same name implemented in two different ways?

**Comment by dankelleher** [comment]
The example above is a pretty common case for me. To improve readability, I often have step definitions that are not completely explicit such as "I enter my details". Another example would be "I click the OK button" where the OK button may be different on different pages. I can definitely work around it... I'm not sure what the official cucumber spec says about step definitions. If they are meant to be global, I can get behind that.

**Comment by volkanogretmen** [comment]
@dankelleher I have worked with nightwatchjs + cucumberjs combination in the past and the cucumber spec didn't allow me to you the same name for multiple steps. When doing so, I would get a corresponding error in the console (`Multiple step definitions match:`). I saw that cypress-cucumber-preprocessor doesn't have this kind of error handling yet.

You can try it out yourself here: http://cucumber.github.io/cucumber-js/

**Comment by lgandecki** [comment]
Yeah.. I don’t think this is how cucumberjs is supposed to work. Good point though that we should throw an error when there is multiple definitins of the same step

**Comment by dankelleher** [comment]
Fair enough, I'm happy to close this then.

**Comment by azhukovskygit** [comment]
With latest Cypress v.12+ for some reason creating common folder with common.js file didn't work, however, what I did, is under step_definitions folder you can create SHARED_STEPS.js file where you import defineStep and then add your shared steps that looks like that. That way you can store all of the commonly used steps under same file and then used it in your feature files.
```
import { defineStep } from '@badeball/cypress-cucumber-preprocessor'

defineStep('I should be able to wait for {int} milliseconds', time => {
	cy.wait(time)
})

defineStep('I should see {string} in the title of the page', string => {
	cy.title().should('include', string)
})
```

Feature: Add/Delete store

    As a user I should be able to add and delete the store

```
Background: navigate to Login page
    Given I navigated to the Login page
    Then I should be able to wait for 2000 milliseconds
    And I should see "Account Login" in the title of the page

Scenario: E2E Test: Add/Delete Store
    When I enter valid login credentials and pin
```
