### ISSUE TITLE
Unable to switch env variables runtime in case of Scenario Outline

### ISSUE THREAD

**Issue by jime2003** [TheBrainFamily/cypress-cucumber-preprocessor#610]
@smoke
Scenario Outline: Test example
  Given Step with <param1>
  When Step with <param2>
  Then Result is <result>

@qa
Examples:
| param1 | param2 | result |
| foo    | bar    | foobar |
| 1      | 2      | 3      |

@uat
Examples:
| param1 | param2 | result |
| foo    | bar    | foobar |
| 1      | 2      | 3      |

When I run below command through “scripts”, it takes correct environment but it runs all the scenarios and completely ignore given tag.
"npx cypress-tags run -e TAGS=\"@smoke\" --browser chrome --env env=qa"

after removing  --env env=qa - it works fine.
our requirement is to run scenarios in different environments by switching it by command.

Can someone please look into it?

**Comment by badeball** [comment]
This has been answered [here](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/532#issuecomment-805065245).
