### ISSUE TITLE
Failure after install

### ISSUE THREAD

**Issue by UrbanNomadIT** [TheBrainFamily/cypress-cucumber-preprocessor#615]
Hi,

The following behavior happens always when I run the project through a corporation machine and I am still not able to identify what is wrong. They all run normally on my personal laptop.

1. After clone and install steps the cypress runner will only open if I rename the cypress-> plugins -> index.js to a "plungsFile.js"
2. After this step despite that Cypress open work successfully, I am not able to run any test case, receiving the following message. 

_Error: Webpack Compilation Error
./cypress/integration/AndAndButSteps.feature 1:15
Module parse failed: Unexpected token (1:15)
You may need an appropriate loader to handle this file type, currently no loaders are configured to process this file. See https://webpack.js.org/concepts#loaders
> Feature: Using And and But
|   Scenario: With an And everything is fine
|     Given I do something
    at Watching.handle [as handler] 

![image](https://user-images.githubusercontent.com/35435477/130433025-afb1ffbf-05a9-470a-8b4f-0c9b844934a2.png)

**Desired behavior**
Feature File is compiling and executing

**Versions**
Cypress version: 8.3.0
Preprocessor version: as in the stack
Node version: 14.16.1

**Comment by badeball** [comment]
Renaming the plugins file to `plungsFile.js` likely means that Cypress isn't picking it up and you have indeed not successfully configured a loader for feature-files (like the error says). In other words - don't do that. Aside from that, it's difficult to say what's wrong with the information you're currently providing.

**Comment by UrbanNomadIT** [comment]
Yeah, you are right on that. 

To the point - After I cloned your repository based on the system that I used and the firewall level, I discovered that npm wasn't installing the proper version of Cypre. The result was that I was receiving some errors. Right now it runs correctly again after I forced the update and changed manually the versions.
