### ISSUE TITLE
Security vulnerabilities (Regular expression denial of service)

### ISSUE THREAD

**Issue by poponuts** [TheBrainFamily/cypress-cucumber-preprocessor#618]
Two npm dependencies have security vulnerabilities after doing `npm audit`.

Issue: Regular expression denial of service 
Package: glob-parent 
Path: @cypress/browserify-preprocessor >   babel-plugin-add-module-exports > chokidar

Patched in: >=5.1.2                  

### Versions

* **Cypress version**: 8.3.1
* **Preprocessor version**:
* **Node version**:

**Comment by dropbeardan** [comment]
Any issues with upgrading the deps/sub-deps?

I could raise a PR if you like

**Comment by ianjamieson** [comment]
Have added a PR to fix this.

**Comment by inthegarage** [comment]
@ianjamieson  Can you also look at the following which appears when using this plugin:

npm WARN deprecated cucumber@4.2.1: The npm package has moved to @cucumber/cucumber

It's probably a good idea to go around all these.

**Comment by ianjamieson** [comment]
Further investigation into fixing the `npm audit` leads me to [this article](https://overreacted.io/npm-audit-broken-by-design/).

I will see if the PR gets merged, but in the mean time I am using `npm audit --production` for my audits.

**Comment by inthegarage** [comment]
@ianjamieson  Just to check the npm warn isn't an audit, it comes from the package maintainer to advise you to move move to the revised package name etc. I think cypress-cucumber should align itself with the package that is being maintained.

**Comment by lgandecki** [comment]
in general I agree most of the audit infos are useless especially in the context of a dev-time only testing tool, but in this case it doesn't seem like it could hurt to bump it so I merged

**Comment by inthegarage** [comment]
@lgandecki Many thanks for uplifting that package. What do you want to do regarding the deprecated warning regarding cucumber itself? New ticket or also fix it here?

**Comment by lgandecki** [comment]
What do you mean by "fix here"? If you want to give the cucumber update a try go ahead, that would be highly appreciated!
Fair warning - It will be more tricky than this one though!
