### ISSUE TITLE
Install cucumber error

### ISSUE THREAD

**Issue by kovacsdongo** [TheBrainFamily/cypress-cucumber-preprocessor#620]
Hello
I installed cucumber with this command:
npm install --save-dev cypress-cucumber-preprocessor
but I get an error:
1939 verbose node v14.17.6
1940 verbose npm  v6.14.15
1941 error code ENOENT
1942 error syscall rename
1943 error path C:\git\intlandCyTest\node_modules\.staging\cypress-cucumber-preprocessor-4490c3b2\node_modules\debug
1944 error dest C:\git\intlandCyTest\node_modules\.staging\debug-e4269b55
1945 error errno -4058
1946 error enoent ENOENT: no such file or directory, rename 'C:\git\intlandCyTest\node_modules\.staging\cypress-cucumber-preprocessor-4490c3b2\node_modules\debug' -> 'C:\git\intlandCyTest\node_modules\.staging\debug-e4269b55'
1947 error enoent This is related to npm not being able to find a file.
1948 verbose exit [ -4058, true ]

so do not finish the complete installation, therefore I can not use cucumber preprocessor
"cypress@^8.3.1"
node: v14.17.6

thanks is advance

**Comment by badeball** [comment]
This isn't an issue specifically with this package and if you google eg. "npm install error syscall rename" you will find lots of proposed solutions.
