### ISSUE TITLE
Infinite test loading

### ISSUE THREAD

**Issue by ikrasnikov** [TheBrainFamily/cypress-cucumber-preprocessor#621]
Hello!
I have an Angular application and test it with the help of cypress-cucumber-preprocessor.
If I run a big amount of test (feature) files with `npm run cypress run`. More than 28 files. I got an infinite test loading each time when Cypress tries to run the 29th file. I tried a different test files amount, but the result is the same. There is no error or message.

![Screenshot from 2021-09-14 10-38-36](https://user-images.githubusercontent.com/22263937/133215806-9e9acc8c-1a4b-4744-bbbd-80a85bd1ccc6.png)

![Screenshot from 2021-09-14 11-21-44](https://user-images.githubusercontent.com/22263937/133222960-07099ff6-9f12-4667-a32f-e7837973b593.png)

* **Cypress version**: 8.3.1
* **Preprocessor version**: 4.2.0
* **Node version**: 12.16.3

**Comment by lgandecki** [comment]
Did you figure this out? :) Worth leaving a note for future googlers :)

**Comment by ikrasnikov** [comment]
I could not reproduce this case with a help of the pet-project. So I guess the problem is on our side. :(
