### ISSUE TITLE
Is browserify required to use TypeScript with Cypress-cucumber-preprocessor?

### ISSUE THREAD

**Issue by merrua** [TheBrainFamily/cypress-cucumber-preprocessor#625]
The current Readme suggests it is? 

"As of Cypress v4.4.0, TypeScript is supported out-of-the-box. To use it, add this to your plugins/index.js:
const browserify = require('@cypress/browserify-preprocessor');
const cucumber = require('cypress-cucumber-preprocessor').default;"
https://github.com/TheBrainFamily/cypress-cucumber-preprocessor

I'd like to clarify, as I don't need it unless cypress-cucumber-preprocessor requires it.

**Comment by badeball** [comment]
> Is browserify required to use TypeScript with Cypress-cucumber-preprocessor?

No, and [here's](https://github.com/TheBrainFamily/cypress-cucumber-webpack-typescript-example) an example of using without browserify (but rather webpack).

**Comment by kubijo** [comment]
To others that stumble upon this for similar reason to mine: You can rid yourselves of many dependencies by excluding the dependency on `@cypress/browserify` from this package by using https://yarnpkg.com/package/noop-package

…that is, add this to your `package.json`
```json
{
    "resolutions": {
        "cypress-cucumber-preprocessor/@cypress/browserify-preprocessor": "npm:noop-package@1.0.0"
    },
}
```
