### ISSUE TITLE
Error: Step implementation missing occurs when the intuitive expression is used

### ISSUE THREAD

**Issue by dhamo-pk** [TheBrainFamily/cypress-cucumber-preprocessor#626]
For this step

```
Scenario Outline:  Verify if route editor works
 When saving after adding the <fixtureFile> waypoints
 Then route should be calculated
        Examples:
            | fixtureFile  |
            | createRoute1 |
```

### Current behavior
This set of code works 
```
When(/^saving after adding the ([^"]*) waypoints$/, (fixtureFileName) => {

});
```
This set of code NOT working
```
When('saving after adding the {string} waypoints', fixtureFileName => {

 });
```

And my package,json

```
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "step_definitions": "cypress/integration/step_definitions/",
    "cucumberJson": {
      "generate": true,
      "outputFolder": "cypress/reports/cucumber-json"
    }
  },
```

And my project structure:
![image](https://user-images.githubusercontent.com/44419390/135249745-211e80fe-bc88-49f1-a8d4-a985c15a86ac.png)

### Versions

Cypress package version: 8.3.0
Cypress binary version: 8.3.0
Electron version: 13.1.7
Bundled Node version: 14.16.0
cypress-cucumber-preprocessor: 4.2.0,

**Comment by badeball** [comment]
> This set of code NOT working
> 
> ```
> When('saving after adding the {string} waypoints', fixtureFileName => {});
> ```

This wouldn't work because `{string}` doesn't match `foo`, but `"foo"`, so change your scenario to something like

```
Scenario Outline:  Verify if route editor works
 When saving after adding the "<fixtureFile>" waypoints
 Then route should be calculated
        Examples:
            | fixtureFile  |
            | createRoute1 |
```
