### ISSUE TITLE
Infinite test runtime when retries enabled

### ISSUE THREAD

**Issue by ghost** [TheBrainFamily/cypress-cucumber-preprocessor#628]
I have retries enabled in my cypress.json `"retries": 2` and these retries work on normal cypress js tests for any error. For cucumber tests though, if the test fails due to pageload timeout then the test will retry once. During the first retry, it will run through the test like normal, but it never resolves and runs the timer infinitely although the test completes.

To reiterate: With retries enabled, if a test fails on the first attempt from pageload timeout, then any retry attempt after that will never resolve whether that retry attempt passes the test or fails for any reason.

The impact is that I can't put these into CI with chance of infinite runtimes.

Any suggestions?

Relevant threads/comments: 
[Not able to use { retries} during Given, When and then](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/497#issuecomment-772492207)
[Possible infinite loop while running in Jenkins with retries](https://github.com/cypress-io/cypress/issues/14972#issuecomment-808249411)

<img width="445" alt="infnite runtime" src="https://user-images.githubusercontent.com/81179661/136230035-bbe8c13b-4130-47d0-b4c9-c288fcd67445.png">

### Versions
* **Cypress version**: 8.5.0
* **Preprocessor version**: 4.3.0
* **Node version**: 14.16.0

**Comment by badeball** [comment]
Can you provide a way for us to consistently reproduce the issue?

**Comment by badeball** [comment]
I'm unfortunately not able to reproduce the issue at all using the above-mentioned code.

**Comment by badeball** [comment]
Thanks for the update, @qlimlass. With starwars.com I was indeed able to reproduce the issue. I was also able to reduce everything down to a minimal example that doesn't involve `cypress-cucumber-preprocessor` at all, as shown below.

```js
// cypress/integration/test.js
afterEach(() => {
  cy.then(() => {});
})

it("should work", () => {
  cy.visit('https://www.starwars.com/');
});
```

The preprocessor does an afterEach-handler and the mere presence of this with at least one Cypress commands seems to be what's causing the issue. As we can't really do anything to remedy this, I consider this to not be an issue with the preprocessor, but rather with Cypress itself and I recommend that you take the above-mentioned example and make an issue on their issue tracker.
