### ISSUE TITLE
Can not import function in spec files

### ISSUE THREAD

**Issue by haan123** [TheBrainFamily/cypress-cucumber-preprocessor#636]
Let’s say i want to call login function on every scenarios:
 
 i defined a login file
```js
// src/auth/login.js

export function login() {
  //…
}
```

then import it in spec

```js
// cypress/integrations/test.spec.js

import { login } from ‘src/auth/login’

// …
```

i’m also using @cypress/webpack-preprocessor   

### Current behavior

The login variable is `undefined`

### Desired behavior

The login variable is login function

### Versions

* **Cypress version**: 8.7.0
* **Preprocessor version**: 4.3.0
* **Node version**: 12.x

**Comment by haan123** [comment]
I updated the node to **v16.13.0** but the issue is still remaining, you can see the image below, the `login` variable is `undefined`

![image](https://user-images.githubusercontent.com/5218341/139514250-4510bb99-65bd-4ad0-a5ba-8f283ff2d2bb.png)

**Comment by badeball** [comment]
You can't pass function arguments to a task, as explained [here](https://docs.cypress.io/api/commands/task#Arguments). If you log the method to dev console you will see that it is indeed define. Closing as this isn't an issue with the preprocessor.

**Comment by haan123** [comment]
Hi @badeball ,

Thanks for the explanation, but in my `cypress/integration/Product/product.spec.js`, line `6`, I only pass one parameter to the `log` task, and I believe it will be printed out if the `login` variable is not `undefinded`

![image](https://user-images.githubusercontent.com/5218341/139529870-3d4e4cf8-a352-4480-aa39-cc9955c0d4b3.png)

**Comment by badeball** [comment]
You can print it out fine in the dev console and you can use `cy.log` to print it to the command log, but you cannot pass it to a task and log it in non-interactive mode.

**Comment by haan123** [comment]
Ah, I understand now, I thought that I can view the log in the terminal, but it's only shown in the browser's console

Thank you for your support!
