### ISSUE TITLE
Add support for different languages

### ISSUE THREAD

**Issue by AbdelHajou** [TheBrainFamily/cypress-cucumber-preprocessor#644]
### Current behavior

Preprocessor doesn't process feature definitions in different languages.

### Desired behavior

Preprocessor should support multiple languages, just like native cucumber does. <https://cucumber.io/docs/gherkin/languages/>

### Test code to reproduce

Create a feature file with the following content (Dutch):
```gherkin
Feature: Home Page
  Scenario: Open the home page
    Gegeven the app is open
    Wanneer I go to the home page
    Dan I should see "Home Page"
```

### Versions

* **Cypress version**:  9.0.0
* **Preprocessor version**: 4.3.0
* **Node version**: 16.9.0

**Comment by badeball** [comment]
It does and it works exactly like with Cucumber.

```feature
# language: nl
Functionaliteit: Home Page
  Scenario: Open the home page
    Gegeven the app is open
    Wanneer I go to the home page
    Dan I should see "Home Page"
```

**Comment by AbdelHajou** [comment]
Thanks @badeball , I didn't know the comment on the first line was necessary.
