### ISSUE TITLE
How can I use JSON path as a feature file parameter>

### ISSUE THREAD

**Issue by dawidappnovation** [TheBrainFamily/cypress-cucumber-preprocessor#646]
Im not sure this is right place to rise this question, but I feel like this is imported or useful feature and ther should be something about this in readme.
How can I use JSON path as a feature file parameter?

This is my example:

Feature  file:
```When I scroll to element "HomePage.section_3_H2"```  

import HomePage from './../../fixtures/HomePage.json'
When('I scroll to element {string}', (element) => {
  cy.get(HomePage[element]).scrollIntoView()
})

Test is failing because we are scrolling to string not value.
Thanks a lot.

**Comment by mike-mccormick** [comment]
Hey @dawidappnovation I think you need to use variable expansion:

Assuming your HomePage.json is something like 

```json
{
   "element": ".title-bar"
}
```
Then this:

```javascript
cy.get(HomePage[`${element}`]).scrollIntoView() 
```

Should run:

```javascript
cy.get(".title-bar").scrollIntoView()
````

**Comment by mike-mccormick** [comment]
@dawidappnovation 

You can get the URL of the current page using `cy.url()`, so something like

```javascript
cy.url().then((returnedUrl) => {
  cy.log(returnedUrl)
// returns something like http://localhost:3000/admin/users

})
```
> Note, you might need to tinker a little with `split` I'm not sure if I've escaped the forward slash correctly. 

But aliases are super handy for setting context. They stay active during each scenario, letting you pass values between steps:

```cucumber
Given I click "Homepage"
And I fill "Forename" with the text "John"
```

```javascript
Given(`I click "{}"`, (linkName) => {
//wrap the name of the link we're clicking for later
cy.wrap(linkName).as('contextPageName')

//click the link
cy.get('.nav-links').contains(linkName).click()

})
```

```javascript
And(`I fill "{}" with the text "{}"`, (field, text) => {

      //fetch the alias we created
      cy.get('@contextPageName').then((linkName) => {
        cy.get(linkName[field])
            .type(text,{force: true})
      })
        
})

```

If you use that approach, you can build your json out to match the strings you're using:

```json

"Homepage" : { 
  "Forename": "#onboarding-forename",
  "Surname": "#onboarding-surname"
}

```

I really recommend getting a good Udemy course and binge-watching it, there are so many awesome little tricks you'll find.  I personally used [this](https://www.udemy.com/course/cypress-io-master-class/) one but there's no shortage of fantastic out there!

**Comment by dawidappnovation** [comment]
This answer is great, I will just set context base on first step
`        Given I open the url "/"
`
This solution will avoid hundreds unnecessary if statements

**Comment by dawidappnovation** [comment]
### Getting value from multiple demential JSON => JavaScript Object.
I was trying to figure it out in different ways and this is my solution,
JSON file:
```
{
    "home": {
        "demo_F": "#demo_form",

```
Getting value using alias as a parameter.
```
import prod from './../../fixtures/prod.json'

When('I scroll to element {string}', (element) => {
  //fetch the alias we created in given step
  cy.get('@pageName').then((page) => {
    cy.get(prod[page][element])
      .scrollIntoView()
  })
})
```
Thank you for helping me with this issue and yes I have right now more then one Udemy course about Cypress.

**Comment by mike-mccormick** [comment]
Happy to help! Enjoy your learning!!
