### ISSUE TITLE
Can't run individual tests using tag - all scenarios from the feature file are executed instead of the one that has the tag

### ISSUE THREAD

**Issue by andrei-s-buta** [TheBrainFamily/cypress-cucumber-preprocessor#672]
Our automated regression has more than 200 scenarios divided in multiple feature files. Each scenario has a scenarioID tag, regression tag and/or smoke tag

feature1.feature
@scenario1 @regression @smoke
Scenario: scenario 1
Given
When
Then

@scenario2 @regression 
Scenario: scenario 2
Given
When
Then

@scenario3 
Scenario: scenario 1
Given
When
Then

feature2.feature
@scenario4 @regression @smoke
Scenario: scenario 1
Given
When
Then

@scenario5 @regression 
Scenario: scenario 2
Given
When
Then

@scenario6 
Scenario: scenario 1
Given
When
Then

....

### Current behavior

When I try to run all the scenarios containing @smoke tag or just a specific scenario using its tag @scenario1, cypress runs all the scenario inside the feature file

For e.g:

-  in case of @smoke
npx cypress-tags run -e TAGS='@smoke' --env allure=true --browser chrome --headed --> all scenarios are executed
- in case of @scenario1
 npx cypress-tags run -e TAGS='@smoke' --env allure=true --browser chrome --headed --> all scenarios from feature1.feature file are executed

### Desired behavior

For e.g:

- in case of @smoke - only @scenario1 and @scenario4 to be executed
- in case of @scenario1 - only @scenario1 to be executed

### Versions

* **Cypress version**: 9.4.1 
* **Preprocessor version**: 4.3.0
* **Node version**: v16.5.0

**Comment by jamiejackson** [comment]
I had the same experience and although I'd like to use this instead of CucumberJS, the inability to use tags prevents my adoption.

**Comment by badeball** [comment]
From https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/532#issuecomment-805065245

> Multiple variables has to be separated by commas, not by specifying `-e / --env` multiple times. This is simply how the Cypress CLI works. Try this instead.
> 
> ```
> $ npx cypress-tags run --env TAGS='@fidelity and @regress and not @Ignore',configFile=hlg
> ```

**Comment by badeball** [comment]
By using -e or --env multiple times, only last takes effect.
