### ISSUE TITLE
Reusable Step Definitions in common folder doesnt seem to work

### ISSUE THREAD

**Issue by pprasanth91** [TheBrainFamily/cypress-cucumber-preprocessor#673]
I have two feature files Featurefile1 and FeatureFile2 and in both the files i have a Step "User Logs into the Application" used. When i define this step in .js file under cypress/integration/common/ folder and run my test it throws an Error stating "Step implementation is missing".

I tried configuring the following in my package.json file
  "cypress-cucumber-preprocessor": {   
    "nonGlobalStepDefinitions": false,
    "commonPath": "cypress/integration/common"
  }

For nonGlobalStepDefinitions i tried with **true** replacing false but still this doesn't seem to work.

@lgandecki

**Comment by andrei-s-buta** [comment]
Have you tried to use commonPath like this "step_definitions": "cypress/integration"? I have a folder inside integration folder that contains all steps and it's working fine.

**Comment by pprasanth91** [comment]
@andrei-s-buta  - can you share me the configuration that i need to do in package.json file please ?

**Comment by andrei-s-buta** [comment]
Replace this part
"cypress-cucumber-preprocessor": {
"nonGlobalStepDefinitions": false,
"commonPath": "cypress/integration/common"
}
 with 
"cypress-cucumber-preprocessor": {
    "nonGlobalStepDefinitions": false,
    "step_definitions": "cypress/integration"
}

**Comment by pprasanth91** [comment]
Thanks @andrei-s-buta its working for me now... :)
