### ISSUE TITLE
My Cypress is skipping my Cucumber's 3 "And's"

### ISSUE THREAD

**Issue by lucasxavierlucas** [TheBrainFamily/cypress-cucumber-preprocessor#681]
![Captura de tela 2022-03-23 122255](https://user-images.githubusercontent.com/86451070/159736513-66938883-8c81-4a37-bedc-548ce2122bf5.png)
### Current behavior

my Cypress is skipping my Cucumber's 3 "And's" commands

### Desired behavior
my Cypress should execute my Cucumber's 3 "And's" commands

### Test code to reproduce

https://github.com/lucasxavierlucas/Cypress-Cucumber_Swag_Labs_Automation

### Versions
  "cypress": "^9.5.2",
    "cypress-cucumber-preprocessor": "^4.3.1"
[node-v16.14.2-x64.msi]

**Comment by badeball** [comment]
From https://github.com/lucasxavierlucas/Cypress-Cucumber_Swag_Labs_Automation/blob/master/cypress/support/steps/OrderSteps.js#L10-L12:

```js
When(/^clico no CART$/, () => {
	loginPage.clicarCART;
});
```

You're not actually invoking the method, only referencing it.
