### ISSUE TITLE
Typescript/browserify  bundle directory output folder broken on Windows 10

### ISSUE THREAD

**Issue by agentHoover** [TheBrainFamily/cypress-cucumber-preprocessor#77]
Using the typescript configuration settings for the plugin on Windows 10 with Visual Studio Code, the bundle output folder was being put into the root of the application folder instead of the user profile.

I was able to fix it by changing line 100 in the index.js  file  to use the path.sep instead of a hardcoded forward slash. 

.\node_modules\cypress-cucumber-preprocessor\index.js

const bundleDir = file.outputPath.split(path.sep).slice(0, -2);

Since windows uses the backslash this line was producing an invalid array of folder names.

**Comment by lgandecki** [comment]
Cool. Would you be willing to send a PR? :-)

**Comment by agentHoover** [comment]
I'll see if I can get one done this weekend.  No promises though. :)

**Comment by agentHoover** [comment]
@lgandecki  
I have the code fix for this.  I tried to push my branch so I can issue a pull request but I was denied.

**Comment by agentHoover** [comment]
PR submitted.
