### ISSUE TITLE
Error: Cannot find module 'test/cypress/support/step_definitions/shared.js'

### ISSUE THREAD

**Issue by ChrisBAshton** [TheBrainFamily/cypress-cucumber-preprocessor#78]
I'm getting this error:

```
Error: Cannot find module 'test/cypress/support/step_definitions/shared.js' from '/Users/ashtoc03/Sites/bbc/news-vj-search-lookup/features'
```

...on v1.2.2 of cypress-cucumber-preprocessor, when v1.0.0 was working ok (removed `package-lock.json` and it stopped working).

This is our cypress config:

```json
{
    "fileServerFolder": "test/cypress",
    "fixturesFolder": "test/cypress/fixtures",
    "integrationFolder": "features",
    "supportFile":  "test/cypress/support/index.js",
    "pluginsFile": "test/cypress/plugins/index.js",
    "videosFolder": "test/cypress/videos",
    "screenshotsFolder": "test/cypress/screenshots",
    "video": false
}
```

And here is our dir structure:

![screen shot 2018-07-31 at 16 13 43](https://user-images.githubusercontent.com/5111927/43468787-baaf5d64-94dc-11e8-84fa-ff1e4265d8a1.png)

Could be that there's been an API change and we're doing something wrong, or it could be that this is a regression... (looks similar to #30)?

**Comment by lgandecki** [comment]
Any chance of a simple reproduction? Also - could you go back a version or two and see if that helps?

**Comment by ChrisBAshton** [comment]
Just re-tried it in a few versions:

* 1.2.2 broken, see error in this issue description
* 1.2.0 broken, see error in this issue description
* 1.1.0 works (but 1 of our tests fails for some reason!)
* 1.0.0 works fully

So breaking change was introduced in 1.2.0.

**Comment by ChrisBAshton** [comment]
I'd take a wild guess and assume it's because [`path.resolve` got removed](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/commit/ad76f6f3fa8cae5536fb5f5e2df5c5ffd2370a03#diff-168726dbe96b3ce427e7fedce31bb0bcL58) :)

**Comment by lgandecki** [comment]
I mean, we don't resolve the paths manually anymore, so the whole operation from that line was removed.

It would be great to have a reproduction (just try to have the same structure and config and strip everything specific to your project). Unless it will be hard to me to verify the problem.
For now I'd recommend: don't use fileServerFolder , as it was mistakenly used for our plugin purpose. Go with the cosmicconfig and step_definitions property as explained here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#configuration

**Comment by ChrisBAshton** [comment]
Ok!

Here's a test repo: https://github.com/ChrisBAshton/cypress-cucumber-debug

The master version passes tests, but the `broken` branch fails them: https://github.com/ChrisBAshton/cypress-cucumber-debug/pull/1

**Comment by lgandecki** [comment]
Cool! I will take a stab at this tonight.

**Comment by lgandecki** [comment]
As I thought:

putting this:
```javascript
  "cypress-cucumber-preprocessor": {
    "step_definitions": "test/cypress/support/step_definitions"
  }
```

in your package.json fixes the problem. 

I'm thinking whether I should try to make it work for the mistakenly used     "fileServerFolder": "test/cypress", as well, or just make a note in the documentation that this is no longer supported (it was deprecated a few versions back)

**Comment by lgandecki** [comment]
@ChrisBAshton It would be great if you could verify this fix and I'd love to hear your thoughts about removing the ability to use fileServerFolder for good, instead of fixing it :)

**Comment by ChrisBAshton** [comment]
Hi @lgandecki I can confirm that fixes it 🎉 but it does feel wrong to pollute the `package.json` with Cypress-specific properties 🤔 can't this be handled in the `cypress.json`?

**Comment by lgandecki** [comment]
cypress.json is for cypress configuration, and you are not configuring cypress here, really. If you don't want to pollute package.json you have all the options that  https://github.com/davidtheclark/cosmiconfig gives you
