### ISSUE TITLE
`and` not supported in step_definitions

### ISSUE THREAD

**Issue by ChrisBAshton** [TheBrainFamily/cypress-cucumber-preprocessor#82]
Whilst [we have `given`, `when` and `then` globally](https://github.com/TheBrainFamily/cypress-cucumber-preprocessor#step-definitions)...

...we do not have a global `and`. (Looks like step definition support was missed off in #31 / #35).

I would expect to be able to write `and('foo happens')` as I am allowed to write `And foo happens` in the feature file.

Thanks!

**Comment by steftanguy** [comment]
Hi Chris,
the And step is like the When step.

So in your case, you can do it :
`Then('foo happens')` in your step_definition file

**Comment by ChrisBAshton** [comment]
Yes, I'm doing that as a workaround - but still think there should be a global `and` method, it reads better!

**Comment by sessa** [comment]
Mind pointing out the complication in allowing `and` as a step definition?  This is not the right implementation but this works: 
`  const And = window.And = window.and = then;`

here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/blob/master/index.js#L20

I have not look into the code a ton, but given that works when running tests, would updating the project correctly be a heavy lift?  If not, I can take a crack at it.

**Comment by lgandecki** [comment]
@sessa that's exactly how we could add that.. If you could also add a simple .feature test where you use And step while creating a step definitions that define that's as And(``, () => {}) that would be great!

**Comment by lgandecki** [comment]
I believe this was done in the #153 , not sure why it didn't close automatically
