### ISSUE TITLE
TypeScript configuration transpiling all `.ts` files in project?

### ISSUE THREAD

**Issue by KeithGillette** [TheBrainFamily/cypress-cucumber-preprocessor#84]
I'm attempting to add `cypress@3.0.3` and `cypress-cucumber-preprocessor@1.2.2` with `tsify@4.0.0` to an existing Angular 6 project. However, I am getting a TypeScript transpilation error in some code located outside of the `cypress` directory when running any test, even the stock JavaScript examples provided with Cypress. 

If I do not have any `.feature` files or corresponding TypeScript step definitions, I get an error of the form:
```
 Oops...we found an error preparing this test file:
...
This occurred while Cypress was compiling and bundling your test code. This is usually caused by:

A missing file or dependency
A syntax error in the file or one of its dependencies
Fix the error in your code and re-run your tests.
```
If I have added `.feature` file & corresponding step definition, the same TypeScript error gets referenced by way of a plugin error:
```
Error running plugin
The following error was thrown by a plugin. We've stopped running your tests because a plugin crashed.
...
```

I am using the `cypress/plugins/index.js` configuration provided in the `README.md`. The same occurs with or without a [`cypress/tsconfig.json`](https://docs.cypress.io/guides/tooling/typescript-support.html#Configure-tsconfig-json). From testing, I suspect that the `tsify` `babel` plugin is either ignoring entirely or perhaps always using the root `tsconfig.json` rather than the one closest to the `cypress` code.

How can I configure `cypress` with `cypress-cucumber-preprocessor` to only transpile TypeScript code inside of the `cypress` directory?

**Comment by mhodgson** [comment]
Here is the `plugin/index.js` file we're using. This will allow you to have a different tsconfig.json file just for your cypress ts files:

```javascript
const cucumber = require('cypress-cucumber-preprocessor').default;
const browserify = require('@cypress/browserify-preprocessor');

module.exports = (on, config) => {
  const options = browserify.defaultOptions;

  options.browserifyOptions.extensions.unshift('.ts');
  options.browserifyOptions.plugin.unshift(['tsify', {project: './cypress/tsconfig.json'}]);

  on('file:preprocessor', cucumber(options))
}
```

**Comment by lgandecki** [comment]
Thanks a lot @mhodgson !

One question - are you sure you need to add 'ts'  to extensions? From what I remember that was somehow unnecessary when I was testing the setup.

Anyway - this looks like a better advise comparing to what we have in the README right now, would you like to doublecheck the above and possibly send a tiny PR with the change? :-)

**Comment by mhodgson** [comment]
@lgandecki huh, I actually didn't even see the instructions in the README. I looked here and I'm not entirely sure how this is working for you without the `.ts` extension since it isn't in the defaults:

https://github.com/cypress-io/cypress-browserify-preprocessor/blob/master/index.js#L16-L61

Happy to submit a PR for an updated README.

**Comment by KeithGillette** [comment]
Thanks, @mhodgson! Would you be willing to share your `cypress/tsconfig.json`, as well?

Does `tsify` respect the `tsconfig.json` `lib` property? Even though I have added `esnext.asynciterable` to `lib` in my `cypress/tsconfig.json`, I am still getting the following error with this setup, even when I'm just attempting to run a Cypress example `.js` spec:
```
Error TS2304: Cannot find name 'AsyncIterator'.
```

**Comment by mhodgson** [comment]
@KeithGillette unfortunately I don't think it's anything too fancy:
```json
{
  "extends": "../tsconfig.json",
  "compilerOptions": {
    "target": "ES6",
    "module": "commonjs",
    "sourceMap": true,
    "typeRoots": [
      "./typings",
      "../node_modules/@types"
    ],
    "types": [
      "cypress",
      "cypress-cucumber",
      "chai"
    ]
  },
  "include": ["./support/**/*.ts"]
}
```

**Comment by KeithGillette** [comment]
Thanks so much, @mhodgson.

I figured out the TS2304 error: I had a typo in the path to my `tsconfig.json` in the `project` key of the `tsify` plugin configuration, so `tsify` wasn't actually using it but didn't throw an error that it couldn't find the file, it just ran without one, apparently.

FYI, I tested and this line of the `cypress/plugins/index.js` configuration is unnecessary, presumably because `tsify` looks for `.ts` by default:
```
options.browserifyOptions.extensions.unshift('.ts');
```

**Comment by mhodgson** [comment]
Cool. I opened a PR to simplify the README: #92

**Comment by cookiescrumbs** [comment]
Does using ```'@cypress/browserify-preprocessor'```  fix this https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/61?
