### ISSUE TITLE
Hook to run before all the tests in Cypress

### ISSUE THREAD

**Issue by darasandeep91** [TheBrainFamily/cypress-cucumber-preprocessor#91]
I wrote a before hook and have places in support/Commands.js 

But the hook is running before each test in cypress. But i wanted it to run only once irrespective of the tests in cypress

Is there a functionality to achieve this ?

NOTE: I am creating a subscriber that i can use for the test in before hook

**Comment by kayvanbree** [comment]
Check out #25, there is no support  for before and after hooks yet.

**Comment by alexttransisland** [comment]
@darasandeep91 can you share your gist with `beforeEach` hook? I can't find a native way to write it using commands with cucumber

**Comment by lgandecki** [comment]
@darasandeep91 
create a before.js file in the folder with step_definitions and put
before(() => {
  dbHelper.connect('...')
  dbHelper.seed('...')
})

there. Take a look here: https://github.com/TheBrainFamily/cypress-cucumber-preprocessor/issues/25#issuecomment-443422175
